// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dota_gcmessages_common_craftworks.proto

#include "dota_gcmessages_common_craftworks.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR CMsgCraftworksComponents_ComponentQuantitiesEntry::CMsgCraftworksComponents_ComponentQuantitiesEntry(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.key_)*/0u
  , /*decltype(_impl_.value_)*/0u} {}
struct CMsgCraftworksComponents_ComponentQuantitiesEntryDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CMsgCraftworksComponents_ComponentQuantitiesEntryDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CMsgCraftworksComponents_ComponentQuantitiesEntryDefaultTypeInternal() {}
  union {
    CMsgCraftworksComponents_ComponentQuantitiesEntry _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CMsgCraftworksComponents_ComponentQuantitiesEntryDefaultTypeInternal _CMsgCraftworksComponents_ComponentQuantitiesEntry_default_instance_;
PROTOBUF_CONSTEXPR CMsgCraftworksComponents::CMsgCraftworksComponents(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.component_quantities_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CMsgCraftworksComponentsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CMsgCraftworksComponentsDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CMsgCraftworksComponentsDefaultTypeInternal() {}
  union {
    CMsgCraftworksComponents _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CMsgCraftworksComponentsDefaultTypeInternal _CMsgCraftworksComponents_default_instance_;
PROTOBUF_CONSTEXPR CMsgCraftworksQuestReward::CMsgCraftworksQuestReward(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.reward_components_)*/nullptr
  , /*decltype(_impl_.quest_id_)*/0u
  , /*decltype(_impl_.stat_value_)*/0u} {}
struct CMsgCraftworksQuestRewardDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CMsgCraftworksQuestRewardDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CMsgCraftworksQuestRewardDefaultTypeInternal() {}
  union {
    CMsgCraftworksQuestReward _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CMsgCraftworksQuestRewardDefaultTypeInternal _CMsgCraftworksQuestReward_default_instance_;
static ::_pb::Metadata file_level_metadata_dota_5fgcmessages_5fcommon_5fcraftworks_2eproto[3];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_dota_5fgcmessages_5fcommon_5fcraftworks_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_dota_5fgcmessages_5fcommon_5fcraftworks_2eproto = nullptr;

const uint32_t TableStruct_dota_5fgcmessages_5fcommon_5fcraftworks_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::CMsgCraftworksComponents_ComponentQuantitiesEntry, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::CMsgCraftworksComponents_ComponentQuantitiesEntry, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::CMsgCraftworksComponents_ComponentQuantitiesEntry, _impl_.key_),
  PROTOBUF_FIELD_OFFSET(::CMsgCraftworksComponents_ComponentQuantitiesEntry, _impl_.value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::CMsgCraftworksComponents, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::CMsgCraftworksComponents, _impl_.component_quantities_),
  PROTOBUF_FIELD_OFFSET(::CMsgCraftworksQuestReward, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::CMsgCraftworksQuestReward, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::CMsgCraftworksQuestReward, _impl_.quest_id_),
  PROTOBUF_FIELD_OFFSET(::CMsgCraftworksQuestReward, _impl_.reward_components_),
  PROTOBUF_FIELD_OFFSET(::CMsgCraftworksQuestReward, _impl_.stat_value_),
  1,
  0,
  2,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, -1, sizeof(::CMsgCraftworksComponents_ComponentQuantitiesEntry)},
  { 10, -1, -1, sizeof(::CMsgCraftworksComponents)},
  { 17, 26, -1, sizeof(::CMsgCraftworksQuestReward)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_CMsgCraftworksComponents_ComponentQuantitiesEntry_default_instance_._instance,
  &::_CMsgCraftworksComponents_default_instance_._instance,
  &::_CMsgCraftworksQuestReward_default_instance_._instance,
};

const char descriptor_table_protodef_dota_5fgcmessages_5fcommon_5fcraftworks_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\'dota_gcmessages_common_craftworks.prot"
  "o\032\023steammessages.proto\032\027dota_shared_enum"
  "s.proto\032\026gcsdk_gcmessages.proto\"\244\001\n\030CMsg"
  "CraftworksComponents\022P\n\024component_quanti"
  "ties\030\001 \003(\01322.CMsgCraftworksComponents.Co"
  "mponentQuantitiesEntry\0326\n\030ComponentQuant"
  "itiesEntry\022\013\n\003key\030\001 \001(\r\022\r\n\005value\030\002 \001(\r\"w"
  "\n\031CMsgCraftworksQuestReward\022\020\n\010quest_id\030"
  "\001 \001(\r\0224\n\021reward_components\030\002 \001(\0132\031.CMsgC"
  "raftworksComponents\022\022\n\nstat_value\030\003 \001(\r*"
  "m\n\026ECraftworksAuditAction\022\016\n\nk_eInvalid\020"
  "\000\022\024\n\020k_eRecipeCrafted\020\001\022\023\n\017k_eMatchRewar"
  "ds\020\002\022\030\n\024k_eMatchRewardsTurbo\020\003"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_dota_5fgcmessages_5fcommon_5fcraftworks_2eproto_deps[3] = {
  &::descriptor_table_dota_5fshared_5fenums_2eproto,
  &::descriptor_table_gcsdk_5fgcmessages_2eproto,
  &::descriptor_table_steammessages_2eproto,
};
static ::_pbi::once_flag descriptor_table_dota_5fgcmessages_5fcommon_5fcraftworks_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_dota_5fgcmessages_5fcommon_5fcraftworks_2eproto = {
    false, false, 510, descriptor_table_protodef_dota_5fgcmessages_5fcommon_5fcraftworks_2eproto,
    "dota_gcmessages_common_craftworks.proto",
    &descriptor_table_dota_5fgcmessages_5fcommon_5fcraftworks_2eproto_once, descriptor_table_dota_5fgcmessages_5fcommon_5fcraftworks_2eproto_deps, 3, 3,
    schemas, file_default_instances, TableStruct_dota_5fgcmessages_5fcommon_5fcraftworks_2eproto::offsets,
    file_level_metadata_dota_5fgcmessages_5fcommon_5fcraftworks_2eproto, file_level_enum_descriptors_dota_5fgcmessages_5fcommon_5fcraftworks_2eproto,
    file_level_service_descriptors_dota_5fgcmessages_5fcommon_5fcraftworks_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_dota_5fgcmessages_5fcommon_5fcraftworks_2eproto_getter() {
  return &descriptor_table_dota_5fgcmessages_5fcommon_5fcraftworks_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_dota_5fgcmessages_5fcommon_5fcraftworks_2eproto(&descriptor_table_dota_5fgcmessages_5fcommon_5fcraftworks_2eproto);
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ECraftworksAuditAction_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_dota_5fgcmessages_5fcommon_5fcraftworks_2eproto);
  return file_level_enum_descriptors_dota_5fgcmessages_5fcommon_5fcraftworks_2eproto[0];
}
bool ECraftworksAuditAction_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class CMsgCraftworksComponents_ComponentQuantitiesEntry::_Internal {
 public:
  using HasBits = decltype(std::declval<CMsgCraftworksComponents_ComponentQuantitiesEntry>()._impl_._has_bits_);
  static void set_has_key(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_value(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

CMsgCraftworksComponents_ComponentQuantitiesEntry::CMsgCraftworksComponents_ComponentQuantitiesEntry(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:CMsgCraftworksComponents.ComponentQuantitiesEntry)
}
CMsgCraftworksComponents_ComponentQuantitiesEntry::CMsgCraftworksComponents_ComponentQuantitiesEntry(const CMsgCraftworksComponents_ComponentQuantitiesEntry& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CMsgCraftworksComponents_ComponentQuantitiesEntry* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.key_){}
    , decltype(_impl_.value_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.key_, &from._impl_.key_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.value_) -
    reinterpret_cast<char*>(&_impl_.key_)) + sizeof(_impl_.value_));
  // @@protoc_insertion_point(copy_constructor:CMsgCraftworksComponents.ComponentQuantitiesEntry)
}

inline void CMsgCraftworksComponents_ComponentQuantitiesEntry::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.key_){0u}
    , decltype(_impl_.value_){0u}
  };
}

CMsgCraftworksComponents_ComponentQuantitiesEntry::~CMsgCraftworksComponents_ComponentQuantitiesEntry() {
  // @@protoc_insertion_point(destructor:CMsgCraftworksComponents.ComponentQuantitiesEntry)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CMsgCraftworksComponents_ComponentQuantitiesEntry::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void CMsgCraftworksComponents_ComponentQuantitiesEntry::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CMsgCraftworksComponents_ComponentQuantitiesEntry::Clear() {
// @@protoc_insertion_point(message_clear_start:CMsgCraftworksComponents.ComponentQuantitiesEntry)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    ::memset(&_impl_.key_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.value_) -
        reinterpret_cast<char*>(&_impl_.key_)) + sizeof(_impl_.value_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CMsgCraftworksComponents_ComponentQuantitiesEntry::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional uint32 key = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _Internal::set_has_key(&has_bits);
          _impl_.key_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional uint32 value = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _Internal::set_has_value(&has_bits);
          _impl_.value_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CMsgCraftworksComponents_ComponentQuantitiesEntry::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CMsgCraftworksComponents.ComponentQuantitiesEntry)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional uint32 key = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_key(), target);
  }

  // optional uint32 value = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_value(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CMsgCraftworksComponents.ComponentQuantitiesEntry)
  return target;
}

size_t CMsgCraftworksComponents_ComponentQuantitiesEntry::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CMsgCraftworksComponents.ComponentQuantitiesEntry)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional uint32 key = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_key());
    }

    // optional uint32 value = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_value());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CMsgCraftworksComponents_ComponentQuantitiesEntry::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CMsgCraftworksComponents_ComponentQuantitiesEntry::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CMsgCraftworksComponents_ComponentQuantitiesEntry::GetClassData() const { return &_class_data_; }


void CMsgCraftworksComponents_ComponentQuantitiesEntry::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CMsgCraftworksComponents_ComponentQuantitiesEntry*>(&to_msg);
  auto& from = static_cast<const CMsgCraftworksComponents_ComponentQuantitiesEntry&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:CMsgCraftworksComponents.ComponentQuantitiesEntry)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.key_ = from._impl_.key_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.value_ = from._impl_.value_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CMsgCraftworksComponents_ComponentQuantitiesEntry::CopyFrom(const CMsgCraftworksComponents_ComponentQuantitiesEntry& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CMsgCraftworksComponents.ComponentQuantitiesEntry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CMsgCraftworksComponents_ComponentQuantitiesEntry::IsInitialized() const {
  return true;
}

void CMsgCraftworksComponents_ComponentQuantitiesEntry::InternalSwap(CMsgCraftworksComponents_ComponentQuantitiesEntry* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CMsgCraftworksComponents_ComponentQuantitiesEntry, _impl_.value_)
      + sizeof(CMsgCraftworksComponents_ComponentQuantitiesEntry::_impl_.value_)
      - PROTOBUF_FIELD_OFFSET(CMsgCraftworksComponents_ComponentQuantitiesEntry, _impl_.key_)>(
          reinterpret_cast<char*>(&_impl_.key_),
          reinterpret_cast<char*>(&other->_impl_.key_));
}

::PROTOBUF_NAMESPACE_ID::Metadata CMsgCraftworksComponents_ComponentQuantitiesEntry::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_dota_5fgcmessages_5fcommon_5fcraftworks_2eproto_getter, &descriptor_table_dota_5fgcmessages_5fcommon_5fcraftworks_2eproto_once,
      file_level_metadata_dota_5fgcmessages_5fcommon_5fcraftworks_2eproto[0]);
}

// ===================================================================

class CMsgCraftworksComponents::_Internal {
 public:
};

CMsgCraftworksComponents::CMsgCraftworksComponents(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:CMsgCraftworksComponents)
}
CMsgCraftworksComponents::CMsgCraftworksComponents(const CMsgCraftworksComponents& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CMsgCraftworksComponents* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.component_quantities_){from._impl_.component_quantities_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:CMsgCraftworksComponents)
}

inline void CMsgCraftworksComponents::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.component_quantities_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

CMsgCraftworksComponents::~CMsgCraftworksComponents() {
  // @@protoc_insertion_point(destructor:CMsgCraftworksComponents)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CMsgCraftworksComponents::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.component_quantities_.~RepeatedPtrField();
}

void CMsgCraftworksComponents::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CMsgCraftworksComponents::Clear() {
// @@protoc_insertion_point(message_clear_start:CMsgCraftworksComponents)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.component_quantities_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CMsgCraftworksComponents::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .CMsgCraftworksComponents.ComponentQuantitiesEntry component_quantities = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_component_quantities(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CMsgCraftworksComponents::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CMsgCraftworksComponents)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .CMsgCraftworksComponents.ComponentQuantitiesEntry component_quantities = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_component_quantities_size()); i < n; i++) {
    const auto& repfield = this->_internal_component_quantities(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CMsgCraftworksComponents)
  return target;
}

size_t CMsgCraftworksComponents::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CMsgCraftworksComponents)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .CMsgCraftworksComponents.ComponentQuantitiesEntry component_quantities = 1;
  total_size += 1UL * this->_internal_component_quantities_size();
  for (const auto& msg : this->_impl_.component_quantities_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CMsgCraftworksComponents::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CMsgCraftworksComponents::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CMsgCraftworksComponents::GetClassData() const { return &_class_data_; }


void CMsgCraftworksComponents::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CMsgCraftworksComponents*>(&to_msg);
  auto& from = static_cast<const CMsgCraftworksComponents&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:CMsgCraftworksComponents)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.component_quantities_.MergeFrom(from._impl_.component_quantities_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CMsgCraftworksComponents::CopyFrom(const CMsgCraftworksComponents& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CMsgCraftworksComponents)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CMsgCraftworksComponents::IsInitialized() const {
  return true;
}

void CMsgCraftworksComponents::InternalSwap(CMsgCraftworksComponents* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.component_quantities_.InternalSwap(&other->_impl_.component_quantities_);
}

::PROTOBUF_NAMESPACE_ID::Metadata CMsgCraftworksComponents::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_dota_5fgcmessages_5fcommon_5fcraftworks_2eproto_getter, &descriptor_table_dota_5fgcmessages_5fcommon_5fcraftworks_2eproto_once,
      file_level_metadata_dota_5fgcmessages_5fcommon_5fcraftworks_2eproto[1]);
}

// ===================================================================

class CMsgCraftworksQuestReward::_Internal {
 public:
  using HasBits = decltype(std::declval<CMsgCraftworksQuestReward>()._impl_._has_bits_);
  static void set_has_quest_id(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static const ::CMsgCraftworksComponents& reward_components(const CMsgCraftworksQuestReward* msg);
  static void set_has_reward_components(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_stat_value(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
};

const ::CMsgCraftworksComponents&
CMsgCraftworksQuestReward::_Internal::reward_components(const CMsgCraftworksQuestReward* msg) {
  return *msg->_impl_.reward_components_;
}
CMsgCraftworksQuestReward::CMsgCraftworksQuestReward(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:CMsgCraftworksQuestReward)
}
CMsgCraftworksQuestReward::CMsgCraftworksQuestReward(const CMsgCraftworksQuestReward& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CMsgCraftworksQuestReward* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.reward_components_){nullptr}
    , decltype(_impl_.quest_id_){}
    , decltype(_impl_.stat_value_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_reward_components()) {
    _this->_impl_.reward_components_ = new ::CMsgCraftworksComponents(*from._impl_.reward_components_);
  }
  ::memcpy(&_impl_.quest_id_, &from._impl_.quest_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.stat_value_) -
    reinterpret_cast<char*>(&_impl_.quest_id_)) + sizeof(_impl_.stat_value_));
  // @@protoc_insertion_point(copy_constructor:CMsgCraftworksQuestReward)
}

inline void CMsgCraftworksQuestReward::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.reward_components_){nullptr}
    , decltype(_impl_.quest_id_){0u}
    , decltype(_impl_.stat_value_){0u}
  };
}

CMsgCraftworksQuestReward::~CMsgCraftworksQuestReward() {
  // @@protoc_insertion_point(destructor:CMsgCraftworksQuestReward)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CMsgCraftworksQuestReward::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.reward_components_;
}

void CMsgCraftworksQuestReward::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CMsgCraftworksQuestReward::Clear() {
// @@protoc_insertion_point(message_clear_start:CMsgCraftworksQuestReward)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    GOOGLE_DCHECK(_impl_.reward_components_ != nullptr);
    _impl_.reward_components_->Clear();
  }
  if (cached_has_bits & 0x00000006u) {
    ::memset(&_impl_.quest_id_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.stat_value_) -
        reinterpret_cast<char*>(&_impl_.quest_id_)) + sizeof(_impl_.stat_value_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CMsgCraftworksQuestReward::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional uint32 quest_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _Internal::set_has_quest_id(&has_bits);
          _impl_.quest_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional .CMsgCraftworksComponents reward_components = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_reward_components(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional uint32 stat_value = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _Internal::set_has_stat_value(&has_bits);
          _impl_.stat_value_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CMsgCraftworksQuestReward::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CMsgCraftworksQuestReward)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional uint32 quest_id = 1;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_quest_id(), target);
  }

  // optional .CMsgCraftworksComponents reward_components = 2;
  if (cached_has_bits & 0x00000001u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::reward_components(this),
        _Internal::reward_components(this).GetCachedSize(), target, stream);
  }

  // optional uint32 stat_value = 3;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_stat_value(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CMsgCraftworksQuestReward)
  return target;
}

size_t CMsgCraftworksQuestReward::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CMsgCraftworksQuestReward)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    // optional .CMsgCraftworksComponents reward_components = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.reward_components_);
    }

    // optional uint32 quest_id = 1;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_quest_id());
    }

    // optional uint32 stat_value = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_stat_value());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CMsgCraftworksQuestReward::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CMsgCraftworksQuestReward::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CMsgCraftworksQuestReward::GetClassData() const { return &_class_data_; }


void CMsgCraftworksQuestReward::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CMsgCraftworksQuestReward*>(&to_msg);
  auto& from = static_cast<const CMsgCraftworksQuestReward&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:CMsgCraftworksQuestReward)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_mutable_reward_components()->::CMsgCraftworksComponents::MergeFrom(
          from._internal_reward_components());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.quest_id_ = from._impl_.quest_id_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.stat_value_ = from._impl_.stat_value_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CMsgCraftworksQuestReward::CopyFrom(const CMsgCraftworksQuestReward& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CMsgCraftworksQuestReward)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CMsgCraftworksQuestReward::IsInitialized() const {
  return true;
}

void CMsgCraftworksQuestReward::InternalSwap(CMsgCraftworksQuestReward* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CMsgCraftworksQuestReward, _impl_.stat_value_)
      + sizeof(CMsgCraftworksQuestReward::_impl_.stat_value_)
      - PROTOBUF_FIELD_OFFSET(CMsgCraftworksQuestReward, _impl_.reward_components_)>(
          reinterpret_cast<char*>(&_impl_.reward_components_),
          reinterpret_cast<char*>(&other->_impl_.reward_components_));
}

::PROTOBUF_NAMESPACE_ID::Metadata CMsgCraftworksQuestReward::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_dota_5fgcmessages_5fcommon_5fcraftworks_2eproto_getter, &descriptor_table_dota_5fgcmessages_5fcommon_5fcraftworks_2eproto_once,
      file_level_metadata_dota_5fgcmessages_5fcommon_5fcraftworks_2eproto[2]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::CMsgCraftworksComponents_ComponentQuantitiesEntry*
Arena::CreateMaybeMessage< ::CMsgCraftworksComponents_ComponentQuantitiesEntry >(Arena* arena) {
  return Arena::CreateMessageInternal< ::CMsgCraftworksComponents_ComponentQuantitiesEntry >(arena);
}
template<> PROTOBUF_NOINLINE ::CMsgCraftworksComponents*
Arena::CreateMaybeMessage< ::CMsgCraftworksComponents >(Arena* arena) {
  return Arena::CreateMessageInternal< ::CMsgCraftworksComponents >(arena);
}
template<> PROTOBUF_NOINLINE ::CMsgCraftworksQuestReward*
Arena::CreateMaybeMessage< ::CMsgCraftworksQuestReward >(Arena* arena) {
  return Arena::CreateMessageInternal< ::CMsgCraftworksQuestReward >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
