// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dota_gcmessages_msgid.proto

#include "dota_gcmessages_msgid.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

static const ::_pb::EnumDescriptor* file_level_enum_descriptors_dota_5fgcmessages_5fmsgid_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_dota_5fgcmessages_5fmsgid_2eproto = nullptr;
const uint32_t TableStruct_dota_5fgcmessages_5fmsgid_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_dota_5fgcmessages_5fmsgid_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\033dota_gcmessages_msgid.proto*\202\324\002\n\nEDOTA"
  "GCMsg\022\025\n\020k_EMsgGCDOTABase\020\3306\022\035\n\030k_EMsgGC"
  "GameMatchSignOut\020\3346\022%\n k_EMsgGCGameMatch"
  "SignOutResponse\020\3356\022\034\n\027k_EMsgGCJoinChatCh"
  "annel\020\3416\022$\n\037k_EMsgGCJoinChatChannelRespo"
  "nse\020\3426\022\037\n\032k_EMsgGCOtherJoinedChannel\020\3456\022"
  "\035\n\030k_EMsgGCOtherLeftChannel\020\3466\022\"\n\035k_EMsg"
  "ServerToGCRequestStatus\020\3626\022\036\n\031k_EMsgGCSt"
  "artFindingMatch\020\3716\022\035\n\030k_EMsgGCConnectedP"
  "layers\020\3726\022\037\n\032k_EMsgGCAbandonCurrentGame\020"
  "\3736\022\035\n\030k_EMsgGCStopFindingMatch\020\3746\022 \n\033k_E"
  "MsgGCPracticeLobbyCreate\020\3766\022\037\n\032k_EMsgGCP"
  "racticeLobbyLeave\020\2007\022 \n\033k_EMsgGCPractice"
  "LobbyLaunch\020\2017\022\036\n\031k_EMsgGCPracticeLobbyL"
  "ist\020\2027\022&\n!k_EMsgGCPracticeLobbyListRespo"
  "nse\020\2037\022\036\n\031k_EMsgGCPracticeLobbyJoin\020\2047\022$"
  "\n\037k_EMsgGCPracticeLobbySetDetails\020\2067\022%\n "
  "k_EMsgGCPracticeLobbySetTeamSlot\020\2077\022)\n$k"
  "_EMsgGCInitialQuestionnaireResponse\020\2117\022\""
  "\n\035k_EMsgGCPracticeLobbyResponse\020\2177\022\"\n\035k_"
  "EMsgGCBroadcastNotification\020\2207\022!\n\034k_EMsg"
  "GCLiveScoreboardUpdate\020\2217\022#\n\036k_EMsgGCReq"
  "uestChatChannelList\020\2247\022+\n&k_EMsgGCReques"
  "tChatChannelListResponse\020\2257\022\024\n\017k_EMsgGCR"
  "eadyUp\020\2367\022\'\n\"k_EMsgGCKickedFromMatchmaki"
  "ngQueue\020\2377\022\033\n\026k_EMsgGCLeaverDetected\020\2407\022"
  "\037\n\032k_EMsgGCSpectateFriendGame\020\2417\022\'\n\"k_EM"
  "sgGCSpectateFriendGameResponse\020\2427\022$\n\037k_E"
  "MsgGCReportsRemainingRequest\020\2447\022%\n k_EMs"
  "gGCReportsRemainingResponse\020\2457\022\037\n\032k_EMsg"
  "GCSubmitPlayerReport\020\2467\022\'\n\"k_EMsgGCSubmi"
  "tPlayerReportResponse\020\2477\022\036\n\031k_EMsgGCPrac"
  "ticeLobbyKick\020\2517\022!\n\034k_EMsgGCSubmitPlayer"
  "ReportV2\020\2527\022)\n$k_EMsgGCSubmitPlayerRepor"
  "tResponseV2\020\2537\022\035\n\030k_EMsgGCRequestSaveGam"
  "es\020\2547\022#\n\036k_EMsgGCRequestSaveGamesServer\020"
  "\2557\022%\n k_EMsgGCRequestSaveGamesResponse\020\256"
  "7\022#\n\036k_EMsgGCLeaverDetectedResponse\020\2577\022\""
  "\n\035k_EMsgGCPlayerFailedToConnect\020\2607\022\035\n\030k_"
  "EMsgGCGCToRelayConnect\020\2617\022%\n k_EMsgGCGCT"
  "oRelayConnectresponse\020\2627\022\026\n\021k_EMsgGCWatc"
  "hGame\020\2637\022\036\n\031k_EMsgGCWatchGameResponse\020\2647"
  "\022\035\n\030k_EMsgGCBanStatusRequest\020\2657\022\036\n\031k_EMs"
  "gGCBanStatusResponse\020\2667\022 \n\033k_EMsgGCMatch"
  "DetailsRequest\020\2677\022!\n\034k_EMsgGCMatchDetail"
  "sResponse\020\2707\022\034\n\027k_EMsgGCCancelWatchGame\020"
  "\2717\022\022\n\rk_EMsgGCPopup\020\2767\022+\n&k_EMsgGCFriend"
  "PracticeLobbyListRequest\020\3077\022,\n\'k_EMsgGCF"
  "riendPracticeLobbyListResponse\020\3107\022&\n!k_E"
  "MsgGCPracticeLobbyJoinResponse\020\3117\022\027\n\022k_E"
  "MsgGCCreateTeam\020\3137\022\037\n\032k_EMsgGCCreateTeam"
  "Response\020\3147\022#\n\036k_EMsgGCTeamInvite_Invite"
  "rToGC\020\3227\0224\n/k_EMsgGCTeamInvite_GCImmedia"
  "teResponseToInviter\020\3237\022*\n%k_EMsgGCTeamIn"
  "vite_GCRequestToInvitee\020\3247\022+\n&k_EMsgGCTe"
  "amInvite_InviteeResponseToGC\020\3257\022+\n&k_EMs"
  "gGCTeamInvite_GCResponseToInviter\020\3267\022+\n&"
  "k_EMsgGCTeamInvite_GCResponseToInvitee\020\327"
  "7\022\033\n\026k_EMsgGCKickTeamMember\020\3307\022#\n\036k_EMsg"
  "GCKickTeamMemberResponse\020\3317\022\026\n\021k_EMsgGCL"
  "eaveTeam\020\3327\022\036\n\031k_EMsgGCLeaveTeamResponse"
  "\020\3337\022%\n k_EMsgGCApplyTeamToPracticeLobby\020"
  "\3467\022\036\n\031k_EMsgGCTransferTeamAdmin\020\3507\022.\n)k_"
  "EMsgGCPracticeLobbyJoinBroadcastChannel\020"
  "\3557\022!\n\034k_EMsgGC_TournamentItemEvent\020\3567\022)\n"
  "$k_EMsgGC_TournamentItemEventResponse\020\3577"
  "\022\026\n\021k_EMsgTeamFanfare\020\3647\022\036\n\031k_EMsgRespon"
  "seTeamFanfare\020\3657\022\034\n\027k_EMsgGCEditTeamDeta"
  "ils\020\3767\022$\n\037k_EMsgGCEditTeamDetailsRespons"
  "e\020\3777\022\032\n\025k_EMsgGCReadyUpStatus\020\2028\022\037\n\032k_EM"
  "sgGCToGCMatchCompleted\020\2228\022!\n\034k_EMsgGCBal"
  "ancedShuffleLobby\020\2248\022$\n\037k_EMsgGCMatchmak"
  "ingStatsRequest\020\2358\022%\n k_EMsgGCMatchmakin"
  "gStatsResponse\020\2368\022\032\n\025k_EMsgGCBotGameCrea"
  "te\020\2378\022\"\n\035k_EMsgGCSetMatchHistoryAccess\020\240"
  "8\022*\n%k_EMsgGCSetMatchHistoryAccessRespon"
  "se\020\2418\022\034\n\027k_EMsgUpgradeLeagueItem\020\2438\022$\n\037k"
  "_EMsgUpgradeLeagueItemResponse\020\2448\022\"\n\035k_E"
  "MsgGCWatchDownloadedReplay\020\2468\022$\n\037k_EMsgC"
  "lientsRejoinChatChannels\020\2618\022 \n\033k_EMsgGCT"
  "oGCGetUserChatInfo\020\2628\022(\n#k_EMsgGCToGCGet"
  "UserChatInfoResponse\020\2638\022%\n k_EMsgGCToGCL"
  "eaveAllChatChannels\020\2648\022%\n k_EMsgGCToGCUp"
  "dateAccountChatBan\020\2658\022$\n\037k_EMsgGCToGCCan"
  "InviteUserToTeam\020\3028\022,\n\'k_EMsgGCToGCCanIn"
  "viteUserToTeamResponse\020\3038\022\034\n\027k_EMsgGCToG"
  "CGetUserRank\020\3048\022$\n\037k_EMsgGCToGCGetUserRa"
  "nkResponse\020\3058\022\037\n\032k_EMsgGCToGCAdjustUserR"
  "ank\020\3068\022\'\n\"k_EMsgGCToGCAdjustUserRankResp"
  "onse\020\3078\022 \n\033k_EMsgGCToGCUpdateTeamStats\020\310"
  "8\022\035\n\030k_EMsgGCToGCValidateTeam\020\3118\022%\n k_EM"
  "sgGCToGCValidateTeamResponse\020\3128\022\037\n\032k_EMs"
  "gGCToGCGetLeagueAdmin\020\3278\022\'\n\"k_EMsgGCToGC"
  "GetLeagueAdminResponse\020\3308\022\035\n\030k_EMsgGCLea"
  "veChatChannel\020\3508\022\030\n\023k_EMsgGCChatMessage\020"
  "\3518\022\035\n\030k_EMsgGCGetHeroStandings\020\3528\022%\n k_E"
  "MsgGCGetHeroStandingsResponse\020\3538\022*\n%k_EM"
  "sgGCItemEditorReservationsRequest\020\3638\022+\n&"
  "k_EMsgGCItemEditorReservationsResponse\020\364"
  "8\022%\n k_EMsgGCItemEditorReserveItemDef\020\3658"
  "\022-\n(k_EMsgGCItemEditorReserveItemDefResp"
  "onse\020\3668\022)\n$k_EMsgGCItemEditorReleaseRese"
  "rvation\020\3678\0221\n,k_EMsgGCItemEditorReleaseR"
  "eservationResponse\020\3708\022#\n\036k_EMsgGCFantasy"
  "LivePlayerStats\020\2149\022$\n\037k_EMsgGCFantasyFin"
  "alPlayerStats\020\2159\022\033\n\026k_EMsgGCFlipLobbyTea"
  "ms\020\2309\022\'\n\"k_EMsgGCToGCEvaluateReportedPla"
  "yer\020\2329\022/\n*k_EMsgGCToGCEvaluateReportedPl"
  "ayerResponse\020\2339\022-\n(k_EMsgGCToGCProcessPl"
  "ayerReportForTarget\020\2349\022%\n k_EMsgGCToGCPr"
  "ocessReportSuccess\020\2359\022%\n k_EMsgGCNotifyA"
  "ccountFlagsChange\020\2369\022\036\n\031k_EMsgGCSetProfi"
  "lePrivacy\020\2379\022&\n!k_EMsgGCSetProfilePrivac"
  "yResponse\020\2409\022\034\n\027k_EMsgGCClientSuspended\020"
  "\2569\022 \n\033k_EMsgGCPartyMemberSetCoach\020\2579\022\"\n\035"
  "k_EMsgGCPracticeLobbySetCoach\020\2629\022\035\n\030k_EM"
  "sgGCChatModeratorBan\020\2779\022,\n\'k_EMsgGCLobby"
  "UpdateBroadcastChannelInfo\020\3079\022$\n\037k_EMsgG"
  "CToGCGrantTournamentItem\020\3149\022)\n$k_EMsgGCT"
  "oGCUpgradeTwitchViewerItems\020\3179\022\'\n\"k_EMsg"
  "GCToGCGetLiveMatchAffiliates\020\3209\022/\n*k_EMs"
  "gGCToGCGetLiveMatchAffiliatesResponse\020\3219"
  "\022*\n%k_EMsgGCToGCUpdatePlayerPennantCount"
  "s\020\3229\022\'\n\"k_EMsgGCToGCGetPlayerPennantCoun"
  "ts\020\3239\022/\n*k_EMsgGCToGCGetPlayerPennantCou"
  "ntsResponse\020\3249\022.\n)k_EMsgGCGameMatchSignO"
  "utPermissionRequest\020\3259\022/\n*k_EMsgGCGameMa"
  "tchSignOutPermissionResponse\020\3269\022\037\n\032k_EMs"
  "gDOTAAwardEventPoints\020\3309\022\035\n\030k_EMsgDOTAGe"
  "tEventPoints\020\3339\022%\n k_EMsgDOTAGetEventPoi"
  "ntsResponse\020\3349\022\'\n\"k_EMsgGCPartyLeaderWat"
  "chGamePrompt\020\3459\022#\n\036k_EMsgGCCompendiumSet"
  "Selection\020\3559\022\"\n\035k_EMsgGCCompendiumDataRe"
  "quest\020\3569\022#\n\036k_EMsgGCCompendiumDataRespon"
  "se\020\3579\022$\n\037k_EMsgDOTAGetPlayerMatchHistory"
  "\020\3609\022,\n\'k_EMsgDOTAGetPlayerMatchHistoryRe"
  "sponse\020\3619\022$\n\037k_EMsgGCToGCMatchmakingAddP"
  "arty\020\3629\022\'\n\"k_EMsgGCToGCMatchmakingRemove"
  "Party\020\3639\022,\n\'k_EMsgGCToGCMatchmakingRemov"
  "eAllParties\020\3649\022&\n!k_EMsgGCToGCMatchmakin"
  "gMatchFound\020\3659\022+\n&k_EMsgGCToGCUpdateMatc"
  "hManagementStats\020\3669\022\'\n\"k_EMsgGCToGCUpdat"
  "eMatchmakingStats\020\3679\022 \n\033k_EMsgGCToServer"
  "PingRequest\020\3709\022!\n\034k_EMsgGCToServerPingRe"
  "sponse\020\3719\022&\n!k_EMsgGCToServerEvaluateTox"
  "icChat\020\3729\022&\n!k_EMsgServerToGCEvaluateTox"
  "icChat\020\3739\022.\n)k_EMsgServerToGCEvaluateTox"
  "icChatResponse\020\3749\022#\n\036k_EMsgGCToGCProcess"
  "MatchLeaver\020\202:\022!\n\034k_EMsgGCNotificationsR"
  "equest\020\203:\022\"\n\035k_EMsgGCNotificationsRespon"
  "se\020\204:\022#\n\036k_EMsgGCToGCModifyNotification\020"
  "\205:\022\034\n\027k_EMsgGCLeagueAdminList\020\212:\022)\n$k_EM"
  "sgGCNotificationsMarkReadRequest\020\213:\0220\n+k"
  "_EMsgServerToGCRequestBatchPlayerResourc"
  "es\020\232:\0228\n3k_EMsgServerToGCRequestBatchPla"
  "yerResourcesResponse\020\233:\022+\n&k_EMsgGCCompe"
  "ndiumSetSelectionResponse\020\235:\022#\n\036k_EMsgGC"
  "RankedPlayerInfoSubmit\020\236:\022+\n&k_EMsgGCRan"
  "kedPlayerInfoSubmitResponse\020\237:\022\035\n\030k_EMsg"
  "GCPlayerInfoSubmit\020\240:\022%\n k_EMsgGCPlayerI"
  "nfoSubmitResponse\020\241:\022 \n\033k_EMsgGCToGCGetA"
  "ccountLevel\020\242:\022(\n#k_EMsgGCToGCGetAccount"
  "LevelResponse\020\243:\022(\n#k_EMsgDOTAGetWeekend"
  "TourneySchedule\020\250:\022%\n k_EMsgDOTAWeekendT"
  "ourneySchedule\020\251:\022+\n&k_EMsgGCJoinableCus"
  "tomGameModesRequest\020\252:\022,\n\'k_EMsgGCJoinab"
  "leCustomGameModesResponse\020\253:\022)\n$k_EMsgGC"
  "JoinableCustomLobbiesRequest\020\254:\022*\n%k_EMs"
  "gGCJoinableCustomLobbiesResponse\020\255:\022!\n\034k"
  "_EMsgGCQuickJoinCustomLobby\020\256:\022)\n$k_EMsg"
  "GCQuickJoinCustomLobbyResponse\020\257:\022&\n!k_E"
  "MsgGCToGCGrantEventPointAction\020\260:\022\'\n\"k_E"
  "MsgGCToGCSetCompendiumSelection\020\266:\022\031\n\024k_"
  "EMsgGCHasItemQuery\020\274:\022\034\n\027k_EMsgGCHasItem"
  "Response\020\275:\022)\n$k_EMsgGCToGCGrantEventPoi"
  "ntActionMsg\020\300:\022(\n#k_EMsgGCToGCGetCompend"
  "iumSelections\020\304:\0220\n+k_EMsgGCToGCGetCompe"
  "ndiumSelectionsResponse\020\305:\022)\n$k_EMsgServ"
  "erToGCMatchConnectionStats\020\306:\022\'\n\"k_EMsgG"
  "CToClientTournamentItemDrop\020\307:\022$\n\037k_EMsg"
  "SQLDelayedGrantLeagueDrop\020\310:\022\'\n\"k_EMsgSe"
  "rverGCUpdateSpectatorCount\020\311:\022\037\n\032k_EMsgG"
  "CToGCEmoticonUnlock\020\315:\022\033\n\026k_EMsgSignOutD"
  "raftInfo\020\316:\022(\n#k_EMsgClientToGCEmoticonD"
  "ataRequest\020\317:\022!\n\034k_EMsgGCToClientEmotico"
  "nData\020\320:\022\?\n:k_EMsgGCPracticeLobbyToggleB"
  "roadcastChannelCameramanStatus\020\321:\022\031\n\024k_E"
  "MsgDOTARedeemItem\020\336:\022!\n\034k_EMsgDOTARedeem"
  "ItemResponse\020\337:\022\'\n\"k_EMsgClientToGCGetAl"
  "lHeroProgress\020\341:\022/\n*k_EMsgClientToGCGetA"
  "llHeroProgressResponse\020\342:\022#\n\036k_EMsgGCToG"
  "CGetServerForClient\020\343:\022+\n&k_EMsgGCToGCGe"
  "tServerForClientResponse\020\344:\022*\n%k_EMsgSQL"
  "ProcessTournamentGameOutcome\020\345:\022\"\n\035k_EMs"
  "gSQLGrantTrophyToAccount\020\346:\022\"\n\035k_EMsgCli"
  "entToGCGetTrophyList\020\347:\022*\n%k_EMsgClientT"
  "oGCGetTrophyListResponse\020\350:\022\"\n\035k_EMsgGCT"
  "oClientTrophyAwarded\020\351:\022 \n\033k_EMsgGCGameB"
  "otMatchSignOut\020\352:\0221\n,k_EMsgGCGameBotMatc"
  "hSignOutPermissionRequest\020\353:\022\031\n\024k_EMsgSi"
  "gnOutBotInfo\020\354:\022#\n\036k_EMsgGCToGCUpdatePro"
  "fileCards\020\355:\022#\n\036k_EMsgClientToGCGetProfi"
  "leCard\020\356:\022+\n&k_EMsgClientToGCGetProfileC"
  "ardResponse\020\357:\022$\n\037k_EMsgClientToGCGetBat"
  "tleReport\020\360:\022,\n\'k_EMsgClientToGCGetBattl"
  "eReportResponse\020\361:\022(\n#k_EMsgClientToGCSe"
  "tProfileCardSlots\020\362:\022\'\n\"k_EMsgGCToClient"
  "ProfileCardUpdated\020\363:\022\'\n\"k_EMsgServerToG"
  "CVictoryPredictions\020\364:\0222\n-k_EMsgClientTo"
  "GCGetBattleReportAggregateStats\020\365:\022:\n5k_"
  "EMsgClientToGCGetBattleReportAggregateSt"
  "atsResponse\020\366:\022(\n#k_EMsgClientToGCGetBat"
  "tleReportInfo\020\367:\0220\n+k_EMsgClientToGCGetB"
  "attleReportInfoResponse\020\370:\022&\n!k_EMsgSign"
  "OutCommunicationSummary\020\371:\022+\n&k_EMsgServ"
  "erToGCRequestStatus_Response\020\372:\022%\n k_EMs"
  "gClientToGCCreateHeroStatue\020\373:\022+\n&k_EMsg"
  "GCToClientHeroStatueCreateResult\020\374:\022&\n!k"
  "_EMsgGCGCToLANServerRelayConnect\020\375:\022,\n\'k"
  "_EMsgClientToGCAcknowledgeBattleReport\020\376"
  ":\0224\n/k_EMsgClientToGCAcknowledgeBattleRe"
  "portResponse\020\377:\0220\n+k_EMsgClientToGCGetBa"
  "ttleReportMatchHistory\020\200;\0228\n3k_EMsgClien"
  "tToGCGetBattleReportMatchHistoryResponse"
  "\020\201;\022(\n#k_EMsgServerToGCReportKillSummari"
  "es\020\202;\022(\n#k_EMsgGCToGCUpdatePlayerPredict"
  "ions\020\211;\022%\n k_EMsgGCToServerPredictionRes"
  "ult\020\212;\022,\n\'k_EMsgGCToGCReplayMonitorValid"
  "ateReplay\020\221;\022\033\n\026k_EMsgLobbyEventPoints\020\224"
  ";\022%\n k_EMsgGCToGCGetCustomGameTickets\020\225;"
  "\022-\n(k_EMsgGCToGCGetCustomGameTicketsResp"
  "onse\020\226;\022!\n\034k_EMsgGCToGCCustomGamePlayed\020"
  "\230;\022\'\n\"k_EMsgGCToGCGrantEventPointsToUser"
  "\020\231;\022 \n\033k_EMsgGameserverCrashReport\020\233;\022(\n"
  "#k_EMsgGameserverCrashReportResponse\020\234;\022"
  "(\n#k_EMsgGCToClientSteamDatagramTicket\020\235"
  ";\022(\n#k_EMsgGCToGCSendAccountsEventPoints"
  "\020\237;\022*\n%k_EMsgClientToGCRerollPlayerChall"
  "enge\020\240;\022*\n%k_EMsgServerToGCRerollPlayerC"
  "hallenge\020\241;\022*\n%k_EMsgGCRerollPlayerChall"
  "engeResponse\020\242;\022\'\n\"k_EMsgSignOutUpdatePl"
  "ayerChallenge\020\243;\022#\n\036k_EMsgClientToGCSetP"
  "artyLeader\020\244;\022\'\n\"k_EMsgClientToGCCancelP"
  "artyInvites\020\245;\022-\n(k_EMsgSQLGrantLeagueMa"
  "tchToTicketHolders\020\250;\022)\n$k_EMsgGCToGCEmo"
  "ticonUnlockNoRollback\020\252;\022%\n k_EMsgClient"
  "ToGCApplyGemCombiner\020\263;\022$\n\037k_EMsgClientT"
  "oGCGetAllHeroOrder\020\266;\022,\n\'k_EMsgClientToG"
  "CGetAllHeroOrderResponse\020\267;\022$\n\037k_EMsgSQL"
  "GCToGCGrantBadgePoints\020\270;\022-\n(k_EMsgGCToG"
  "CCheckOwnsEntireEmoticonRange\020\273;\0225\n0k_EM"
  "sgGCToGCCheckOwnsEntireEmoticonRangeResp"
  "onse\020\274;\022)\n$k_EMsgGCToClientRequestLaneSe"
  "lection\020\307;\0221\n,k_EMsgGCToClientRequestLan"
  "eSelectionResponse\020\310;\022,\n\'k_EMsgServerToG"
  "CCavernCrawlIsHeroActive\020\311;\0224\n/k_EMsgSer"
  "verToGCCavernCrawlIsHeroActiveResponse\020\312"
  ";\0226\n1k_EMsgClientToGCPlayerCardSpecificP"
  "urchaseRequest\020\313;\0227\n2k_EMsgClientToGCPla"
  "yerCardSpecificPurchaseResponse\020\314;\022\036\n\031k_"
  "EMsgSQLSetIsLeagueAdmin\020\316;\022%\n k_EMsgGCTo"
  "GCGetLiveLeagueMatches\020\317;\022-\n(k_EMsgGCToG"
  "CGetLiveLeagueMatchesResponse\020\320;\022*\n%k_EM"
  "sgDOTALeagueInfoListAdminsRequest\020\321;\022*\n%"
  "k_EMsgDOTALeagueInfoListAdminsReponse\020\322;"
  "\022#\n\036k_EMsgGCToGCLeagueMatchStarted\020\335;\022%\n"
  " k_EMsgGCToGCLeagueMatchCompleted\020\336;\022+\n&"
  "k_EMsgGCToGCLeagueMatchStartedResponse\020\337"
  ";\022/\n*k_EMsgDOTALeagueAvailableLobbyNodes"
  "Request\020\342;\022(\n#k_EMsgDOTALeagueAvailableL"
  "obbyNodes\020\343;\022\036\n\031k_EMsgGCToGCLeagueReques"
  "t\020\344;\022\037\n\032k_EMsgGCToGCLeagueResponse\020\345;\022\'\n"
  "\"k_EMsgGCToGCLeagueNodeGroupRequest\020\346;\022("
  "\n#k_EMsgGCToGCLeagueNodeGroupResponse\020\347;"
  "\022\"\n\035k_EMsgGCToGCLeagueNodeRequest\020\350;\022#\n\036"
  "k_EMsgGCToGCLeagueNodeResponse\020\351;\022*\n%k_E"
  "MsgGCToGCRealtimeStatsTerseRequest\020\352;\022+\n"
  "&k_EMsgGCToGCRealtimeStatsTerseResponse\020"
  "\353;\022%\n k_EMsgGCToGCGetTopMatchesRequest\020\354"
  ";\022&\n!k_EMsgGCToGCGetTopMatchesResponse\020\355"
  ";\022\'\n\"k_EMsgClientToGCGetFilteredPlayers\020"
  "\356;\022/\n*k_EMsgGCToClientGetFilteredPlayers"
  "Response\020\357;\022)\n$k_EMsgClientToGCRemoveFil"
  "teredPlayer\020\360;\0221\n,k_EMsgGCToClientRemove"
  "FilteredPlayerResponse\020\361;\022&\n!k_EMsgGCToC"
  "lientPlayerBeaconState\020\362;\022&\n!k_EMsgGCToC"
  "lientPartyBeaconUpdate\020\363;\022&\n!k_EMsgGCToC"
  "lientPartySearchInvite\020\364;\022&\n!k_EMsgClien"
  "tToGCUpdatePartyBeacon\020\365;\022/\n*k_EMsgClien"
  "tToGCRequestActiveBeaconParties\020\366;\0227\n2k_"
  "EMsgGCToClientRequestActiveBeaconParties"
  "Response\020\367;\022$\n\037k_EMsgClientToGCManageFav"
  "orites\020\370;\022,\n\'k_EMsgGCToClientManageFavor"
  "itesResponse\020\371;\022(\n#k_EMsgClientToGCJoinP"
  "artyFromBeacon\020\372;\0220\n+k_EMsgGCToClientJoi"
  "nPartyFromBeaconResponse\020\373;\022\'\n\"k_EMsgCli"
  "entToGCGetFavoritePlayers\020\374;\022/\n*k_EMsgGC"
  "ToClientGetFavoritePlayersResponse\020\375;\022*\n"
  "%k_EMsgClientToGCVerifyFavoritePlayers\020\376"
  ";\0222\n-k_EMsgGCToClientVerifyFavoritePlaye"
  "rsResponse\020\377;\022\'\n\"k_EMsgGCToClientPartySe"
  "archInvites\020\200<\022\"\n\035k_EMsgGCToClientReques"
  "tMMInfo\020\201<\022\033\n\026k_EMsgClientToGCMMInfo\020\202<\022"
  "\036\n\031k_EMsgSignOutTextMuteInfo\020\203<\022/\n*k_EMs"
  "gClientToGCPurchaseLabyrinthBlessings\020\204<"
  "\0227\n2k_EMsgClientToGCPurchaseLabyrinthBle"
  "ssingsResponse\020\205<\022/\n*k_EMsgClientToGCPur"
  "chaseFilteredPlayerSlot\020\206<\0227\n2k_EMsgGCTo"
  "ClientPurchaseFilteredPlayerSlotResponse"
  "\020\207<\022-\n(k_EMsgClientToGCUpdateFilteredPla"
  "yerNote\020\210<\0225\n0k_EMsgGCToClientUpdateFilt"
  "eredPlayerNoteResponse\020\211<\022\036\n\031k_EMsgClien"
  "tToGCClaimSwag\020\212<\022&\n!k_EMsgGCToClientCla"
  "imSwagResponse\020\213<\022%\n k_EMsgServerToGCLoc"
  "kCharmTrading\020\304>\022\'\n\"k_EMsgClientToGCPlay"
  "erStatsRequest\020\306>\022(\n#k_EMsgGCToClientPla"
  "yerStatsResponse\020\307>\022#\n\036k_EMsgGCClearPrac"
  "ticeLobbyTeam\020\310>\022)\n$k_EMsgClientToGCFind"
  "TopSourceTVGames\020\311>\0221\n,k_EMsgGCToClientF"
  "indTopSourceTVGamesResponse\020\312>\022\026\n\021k_EMsg"
  "GCLobbyList\020\313>\022\036\n\031k_EMsgGCLobbyListRespo"
  "nse\020\314>\022$\n\037k_EMsgGCPlayerStatsMatchSignOu"
  "t\020\315>\0221\n,k_EMsgClientToGCSocialFeedPostCo"
  "mmentRequest\020\320>\0222\n-k_EMsgGCToClientSocia"
  "lFeedPostCommentResponse\020\321>\0224\n/k_EMsgCli"
  "entToGCCustomGamesFriendsPlayedRequest\020\322"
  ">\0225\n0k_EMsgGCToClientCustomGamesFriendsP"
  "layedResponse\020\323>\0223\n.k_EMsgClientToGCFrie"
  "ndsPlayedCustomGameRequest\020\324>\0224\n/k_EMsgG"
  "CToClientFriendsPlayedCustomGameResponse"
  "\020\325>\022\037\n\032k_EMsgGCTopCustomGamesList\020\330>\022!\n\034"
  "k_EMsgClientToGCSetPartyOpen\020\335>\022%\n k_EMs"
  "gClientToGCMergePartyInvite\020\336>\022*\n%k_EMsg"
  "GCToClientMergeGroupInviteReply\020\337>\022\'\n\"k_"
  "EMsgClientToGCMergePartyResponse\020\340>\022,\n\'k"
  "_EMsgGCToClientMergePartyResponseReply\020\341"
  ">\022(\n#k_EMsgClientToGCGetProfileCardStats"
  "\020\342>\0220\n+k_EMsgClientToGCGetProfileCardSta"
  "tsResponse\020\343>\022,\n\'k_EMsgClientToGCTopLeag"
  "ueMatchesRequest\020\344>\022,\n\'k_EMsgClientToGCT"
  "opFriendMatchesRequest\020\345>\022,\n\'k_EMsgGCToC"
  "lientProfileCardStatsUpdated\020\350>\022\"\n\035k_EMs"
  "gServerToGCRealtimeStats\020\351>\022+\n&k_EMsgGCT"
  "oServerRealtimeStatsStartStop\020\352>\022%\n k_EM"
  "sgGCToGCGetServersForClients\020\355>\022-\n(k_EMs"
  "gGCToGCGetServersForClientsResponse\020\356>\022&"
  "\n!k_EMsgGCPracticeLobbyKickFromTeam\020\357>\022!"
  "\n\034k_EMsgDOTAChatGetMemberCount\020\360>\022)\n$k_E"
  "MsgDOTAChatGetMemberCountResponse\020\361>\0221\n,"
  "k_EMsgClientToGCSocialFeedPostMessageReq"
  "uest\020\362>\0222\n-k_EMsgGCToClientSocialFeedPos"
  "tMessageResponse\020\363>\022/\n*k_EMsgCustomGameL"
  "istenServerStartedLoading\020\364>\022*\n%k_EMsgCu"
  "stomGameClientFinishedLoading\020\365>\022/\n*k_EM"
  "sgGCPracticeLobbyCloseBroadcastChannel\020\366"
  ">\022&\n!k_EMsgGCStartFindingMatchResponse\020\367"
  ">\022$\n\037k_EMsgSQLGCToGCGrantAccountFlag\020\371>\022"
  "-\n(k_EMsgGCToClientTopLeagueMatchesRespo"
  "nse\020\375>\022-\n(k_EMsgGCToClientTopFriendMatch"
  "esResponse\020\376>\022*\n%k_EMsgClientToGCMatches"
  "MinimalRequest\020\377>\022+\n&k_EMsgClientToGCMat"
  "chesMinimalResponse\020\200\?\022\'\n\"k_EMsgGCToClie"
  "ntChatRegionsEnabled\020\203\?\022\035\n\030k_EMsgClientT"
  "oGCPingData\020\204\?\022%\n k_EMsgGCToGCEnsureAcco"
  "untInParty\020\207\?\022-\n(k_EMsgGCToGCEnsureAccou"
  "ntInPartyResponse\020\210\?\022&\n!k_EMsgClientToGC"
  "GetProfileTickets\020\211\?\022.\n)k_EMsgClientToGC"
  "GetProfileTicketsResponse\020\212\?\022\'\n\"k_EMsgGC"
  "ToClientMatchGroupsVersion\020\213\?\022$\n\037k_EMsgC"
  "lientToGCH264Unsupported\020\214\?\022&\n!k_EMsgCli"
  "entToGCWatchingBroadcast\020\215\?\022%\n k_EMsgCli"
  "entToGCGetQuestProgress\020\216\?\022-\n(k_EMsgClie"
  "ntToGCGetQuestProgressResponse\020\217\?\022\031\n\024k_E"
  "MsgSignOutXPCoins\020\220\?\022#\n\036k_EMsgGCToClient"
  "MatchSignedOut\020\221\?\022 \n\033k_EMsgGCGetHeroStat"
  "sHistory\020\222\?\022(\n#k_EMsgGCGetHeroStatsHisto"
  "ryResponse\020\223\?\022&\n!k_EMsgClientToGCPrivate"
  "ChatInvite\020\224\?\022$\n\037k_EMsgClientToGCPrivate"
  "ChatKick\020\230\?\022\'\n\"k_EMsgClientToGCPrivateCh"
  "atPromote\020\231\?\022&\n!k_EMsgClientToGCPrivateC"
  "hatDemote\020\232\?\022(\n#k_EMsgGCToClientPrivateC"
  "hatResponse\020\233\?\0222\n-k_EMsgClientToGCLatest"
  "ConductScorecardRequest\020\237\?\022+\n&k_EMsgClie"
  "ntToGCLatestConductScorecard\020\240\?\022$\n\037k_EMs"
  "gClientToGCWageringRequest\020\243\?\022%\n k_EMsgG"
  "CToClientWageringResponse\020\244\?\022&\n!k_EMsgCl"
  "ientToGCEventGoalsRequest\020\247\?\022\'\n\"k_EMsgCl"
  "ientToGCEventGoalsResponse\020\250\?\022(\n#k_EMsgG"
  "CToGCLeaguePredictionsUpdate\020\254\?\022&\n!k_EMs"
  "gGCToGCAddUserToPostGameChat\020\256\?\022)\n$k_EMs"
  "gClientToGCHasPlayerVotedForMVP\020\257\?\0221\n,k_"
  "EMsgClientToGCHasPlayerVotedForMVPRespon"
  "se\020\260\?\022\037\n\032k_EMsgClientToGCVoteForMVP\020\261\?\022\'"
  "\n\"k_EMsgClientToGCVoteForMVPResponse\020\262\?\022"
  "&\n!k_EMsgGCToGCGetEventParticipation\020\263\?\022"
  ".\n)k_EMsgGCToGCGetEventParticipationResp"
  "onse\020\264\?\0223\n.k_EMsgGCToClientAutomatedTour"
  "namentStateChange\020\265\?\022\'\n\"k_EMsgClientToGC"
  "WeekendTourneyOpts\020\266\?\022/\n*k_EMsgClientToG"
  "CWeekendTourneyOptsResponse\020\267\?\022(\n#k_EMsg"
  "ClientToGCWeekendTourneyLeave\020\270\?\0220\n+k_EM"
  "sgClientToGCWeekendTourneyLeaveResponse\020"
  "\271\?\022)\n$k_EMsgClientToGCTeammateStatsReque"
  "st\020\274\?\022*\n%k_EMsgClientToGCTeammateStatsRe"
  "sponse\020\275\?\022\'\n\"k_EMsgClientToGCGetGiftPerm"
  "issions\020\276\?\022/\n*k_EMsgClientToGCGetGiftPer"
  "missionsResponse\020\277\?\022\"\n\035k_EMsgClientToGCV"
  "oteForArcana\020\300\?\022*\n%k_EMsgClientToGCVoteF"
  "orArcanaResponse\020\301\?\0220\n+k_EMsgClientToGCR"
  "equestArcanaVotesRemaining\020\302\?\0228\n3k_EMsgC"
  "lientToGCRequestArcanaVotesRemainingResp"
  "onse\020\303\?\022&\n!k_EMsgGCTransferTeamAdminResp"
  "onse\020\304\?\022\035\n\030k_EMsgGCToClientTeamInfo\020\307\?\022\036"
  "\n\031k_EMsgGCToClientTeamsInfo\020\310\?\022&\n!k_EMsg"
  "ClientToGCMyTeamInfoRequest\020\311\?\022$\n\037k_EMsg"
  "ClientToGCPublishUserStat\020\314\?\022\"\n\035k_EMsgGC"
  "ToGCSignoutSpendWager\020\315\?\022\037\n\032k_EMsgGCSubm"
  "itLobbyMVPVote\020\320\?\022\'\n\"k_EMsgGCSubmitLobby"
  "MVPVoteResponse\020\321\?\022\'\n\"k_EMsgSignOutCommu"
  "nityGoalProgress\020\326\?\022$\n\037k_EMsgGCToClientL"
  "obbyMVPAwarded\020\330\?\022)\n$k_EMsgGCToClientQue"
  "stProgressUpdated\020\331\?\022#\n\036k_EMsgGCToClient"
  "WageringUpdate\020\332\?\022&\n!k_EMsgGCToClientArc"
  "anaVotesUpdate\020\333\?\022-\n(k_EMsgClientToGCSet"
  "SpectatorLobbyDetails\020\335\?\0225\n0k_EMsgClient"
  "ToGCSetSpectatorLobbyDetailsResponse\020\336\?\022"
  ")\n$k_EMsgClientToGCCreateSpectatorLobby\020"
  "\337\?\0221\n,k_EMsgClientToGCCreateSpectatorLob"
  "byResponse\020\340\?\022\'\n\"k_EMsgClientToGCSpectat"
  "orLobbyList\020\341\?\022/\n*k_EMsgClientToGCSpecta"
  "torLobbyListResponse\020\342\?\022$\n\037k_EMsgSpectat"
  "orLobbyGameDetails\020\343\?\0226\n1k_EMsgServerToG"
  "CCompendiumInGamePredictionResults\020\346\?\022:\n"
  "5k_EMsgServerToGCCloseCompendiumInGamePr"
  "edictionVoting\020\347\?\022\'\n\"k_EMsgClientToGCOpe"
  "nPlayerCardPack\020\350\?\022/\n*k_EMsgClientToGCOp"
  "enPlayerCardPackResponse\020\351\?\0225\n0k_EMsgCli"
  "entToGCSelectCompendiumInGamePrediction\020"
  "\352\?\022=\n8k_EMsgClientToGCSelectCompendiumIn"
  "GamePredictionResponse\020\353\?\0221\n,k_EMsgClien"
  "tToGCWeekendTourneyGetPlayerStats\020\354\?\0229\n4"
  "k_EMsgClientToGCWeekendTourneyGetPlayerS"
  "tatsResponse\020\355\?\022&\n!k_EMsgClientToGCRecyc"
  "lePlayerCard\020\356\?\022.\n)k_EMsgClientToGCRecyc"
  "lePlayerCardResponse\020\357\?\022)\n$k_EMsgClientT"
  "oGCCreatePlayerCardPack\020\360\?\0221\n,k_EMsgClie"
  "ntToGCCreatePlayerCardPackResponse\020\361\?\022/\n"
  "*k_EMsgClientToGCGetPlayerCardRosterRequ"
  "est\020\362\?\0220\n+k_EMsgClientToGCGetPlayerCardR"
  "osterResponse\020\363\?\022/\n*k_EMsgClientToGCSetP"
  "layerCardRosterRequest\020\364\?\0220\n+k_EMsgClien"
  "tToGCSetPlayerCardRosterResponse\020\365\?\022B\n=k"
  "_EMsgServerToGCCloseCompendiumInGamePred"
  "ictionVotingResponse\020\367\?\022 \n\033k_EMsgLobbyBa"
  "ttleCupVictory\020\372\?\022\"\n\035k_EMsgGCGetPlayerCa"
  "rdItemInfo\020\373\?\022*\n%k_EMsgGCGetPlayerCardIt"
  "emInfoResponse\020\374\?\022/\n*k_EMsgClientToGCReq"
  "uestSteamDatagramTicket\020\375\?\0227\n2k_EMsgClie"
  "ntToGCRequestSteamDatagramTicketResponse"
  "\020\376\?\022,\n\'k_EMsgGCToClientBattlePassRollupR"
  "equest\020\377\?\022-\n(k_EMsgGCToClientBattlePassR"
  "ollupResponse\020\200@\022/\n*k_EMsgClientToGCTran"
  "sferSeasonalMMRRequest\020\201@\0220\n+k_EMsgClien"
  "tToGCTransferSeasonalMMRResponse\020\202@\022+\n&k"
  "_EMsgGCToGCPublicChatCommunicationBan\020\203@"
  "\022\"\n\035k_EMsgGCToGCUpdateAccountInfo\020\204@\022!\n\034"
  "k_EMsgGCChatReportPublicSpam\020\205@\022+\n&k_EMs"
  "gClientToGCSetPartyBuilderOptions\020\206@\0223\n."
  "k_EMsgClientToGCSetPartyBuilderOptionsRe"
  "sponse\020\207@\022#\n\036k_EMsgGCToClientPlaytestSta"
  "tus\020\210@\022!\n\034k_EMsgClientToGCJoinPlaytest\020\211"
  "@\022)\n$k_EMsgClientToGCJoinPlaytestRespons"
  "e\020\212@\022\037\n\032k_EMsgLobbyPlaytestDetails\020\213@\022\036\n"
  "\031k_EMsgDOTASetFavoriteTeam\020\214@\0220\n+k_EMsgG"
  "CToClientBattlePassRollupListRequest\020\215@\022"
  "1\n,k_EMsgGCToClientBattlePassRollupListR"
  "esponse\020\216@\022\037\n\032k_EMsgDOTAClaimEventAction"
  "\020\221@\022\'\n\"k_EMsgDOTAClaimEventActionRespons"
  "e\020\222@\022\"\n\035k_EMsgDOTAGetPeriodicResource\020\223@"
  "\022*\n%k_EMsgDOTAGetPeriodicResourceRespons"
  "e\020\224@\022&\n!k_EMsgDOTAPeriodicResourceUpdate"
  "d\020\225@\022\037\n\032k_EMsgServerToGCSpendWager\020\226@\022\'\n"
  "\"k_EMsgGCToGCSignoutSpendWagerToken\020\227@\022%"
  "\n k_EMsgSubmitTriviaQuestionAnswer\020\230@\022-\n"
  "(k_EMsgSubmitTriviaQuestionAnswerRespons"
  "e\020\231@\022\034\n\027k_EMsgClientToGCGiveTip\020\232@\022$\n\037k_"
  "EMsgClientToGCGiveTipResponse\020\233@\022\035\n\030k_EM"
  "sgStartTriviaSession\020\234@\022%\n k_EMsgStartTr"
  "iviaSessionResponse\020\235@\022#\n\036k_EMsgAnchorPh"
  "oneNumberRequest\020\236@\022$\n\037k_EMsgAnchorPhone"
  "NumberResponse\020\237@\022%\n k_EMsgUnanchorPhone"
  "NumberRequest\020\240@\022&\n!k_EMsgUnanchorPhoneN"
  "umberResponse\020\241@\022&\n!k_EMsgGCToGCSignoutS"
  "pendRankWager\020\245@\022 \n\033k_EMsgGCToGCGetFavor"
  "iteTeam\020\246@\022(\n#k_EMsgGCToGCGetFavoriteTea"
  "mResponse\020\247@\022\037\n\032k_EMsgSignOutEventGameDa"
  "ta\020\250@\022&\n!k_EMsgClientToGCQuickStatsReque"
  "st\020\256@\022\'\n\"k_EMsgClientToGCQuickStatsRespo"
  "nse\020\257@\022,\n\'k_EMsgGCToGCSubtractEventPoint"
  "sFromUser\020\260@\022)\n$k_EMsgSelectionPriorityC"
  "hoiceRequest\020\261@\022*\n%k_EMsgSelectionPriori"
  "tyChoiceResponse\020\262@\0222\n-k_EMsgGCToGCCompe"
  "ndiumInGamePredictionResults\020\263@\022\036\n\031k_EMs"
  "gGameAutographReward\020\264@\022&\n!k_EMsgGameAut"
  "ographRewardResponse\020\265@\022\036\n\031k_EMsgDestroy"
  "LobbyRequest\020\266@\022\037\n\032k_EMsgDestroyLobbyRes"
  "ponse\020\267@\022&\n!k_EMsgPurchaseItemWithEventP"
  "oints\020\270@\022.\n)k_EMsgPurchaseItemWithEventP"
  "ointsResponse\020\271@\0223\n.k_EMsgServerToGCMatc"
  "hPlayerItemPurchaseHistory\020\272@\022*\n%k_EMsgG"
  "CToGCGrantPlusHeroMatchResults\020\273@\022&\n!k_E"
  "MsgServerToGCMatchStateHistory\020\277@\022\"\n\035k_E"
  "MsgPurchaseHeroRandomRelic\020\302@\022*\n%k_EMsgP"
  "urchaseHeroRandomRelicResponse\020\303@\022.\n)k_E"
  "MsgClientToGCClaimEventActionUsingItem\020\304"
  "@\0226\n1k_EMsgClientToGCClaimEventActionUsi"
  "ngItemResponse\020\305@\022!\n\034k_EMsgPartyReadyChe"
  "ckRequest\020\306@\022\"\n\035k_EMsgPartyReadyCheckRes"
  "ponse\020\307@\022%\n k_EMsgPartyReadyCheckAcknowl"
  "edge\020\310@\022*\n%k_EMsgGetRecentPlayTimeFriend"
  "sRequest\020\311@\022+\n&k_EMsgGetRecentPlayTimeFr"
  "iendsResponse\020\312@\022(\n#k_EMsgGCToClientComm"
  "endNotification\020\313@\022\031\n\024k_EMsgProfileReque"
  "st\020\314@\022\032\n\025k_EMsgProfileResponse\020\315@\022\030\n\023k_E"
  "MsgProfileUpdate\020\316@\022 \n\033k_EMsgProfileUpda"
  "teResponse\020\317@\022 \n\033k_EMsgHeroGlobalDataReq"
  "uest\020\322@\022!\n\034k_EMsgHeroGlobalDataResponse\020"
  "\323@\0225\n0k_EMsgClientToGCRequestPlusWeeklyC"
  "hallengeResult\020\324@\022=\n8k_EMsgClientToGCReq"
  "uestPlusWeeklyChallengeResultResponse\020\325@"
  "\022%\n k_EMsgGCToGCGrantPlusPrepaidTime\020\326@\022"
  "$\n\037k_EMsgPrivateMetadataKeyRequest\020\327@\022%\n"
  " k_EMsgPrivateMetadataKeyResponse\020\330@\022$\n\037"
  "k_EMsgGCToGCReconcilePlusStatus\020\331@\022 \n\033k_"
  "EMsgGCToGCCheckPlusStatus\020\332@\022(\n#k_EMsgGC"
  "ToGCCheckPlusStatusResponse\020\333@\022,\n\'k_EMsg"
  "GCToGCReconcilePlusAutoGrantItems\020\334@\022.\n)"
  "k_EMsgGCToGCReconcilePlusStatusUnreliabl"
  "e\020\335@\0220\n+k_EMsgGCToClientCavernCrawlMapPa"
  "thCompleted\020\340@\022)\n$k_EMsgClientToGCCavern"
  "CrawlClaimRoom\020\341@\0221\n,k_EMsgClientToGCCav"
  "ernCrawlClaimRoomResponse\020\342@\022-\n(k_EMsgCl"
  "ientToGCCavernCrawlUseItemOnRoom\020\343@\0225\n0k"
  "_EMsgClientToGCCavernCrawlUseItemOnRoomR"
  "esponse\020\344@\022-\n(k_EMsgClientToGCCavernCraw"
  "lUseItemOnPath\020\345@\0225\n0k_EMsgClientToGCCav"
  "ernCrawlUseItemOnPathResponse\020\346@\022/\n*k_EM"
  "sgClientToGCCavernCrawlRequestMapState\020\347"
  "@\0227\n2k_EMsgClientToGCCavernCrawlRequestM"
  "apStateResponse\020\350@\022\026\n\021k_EMsgSignOutTips\020"
  "\351@\022+\n&k_EMsgClientToGCRequestEventPointL"
  "ogV2\020\352@\0223\n.k_EMsgClientToGCRequestEventP"
  "ointLogResponseV2\020\353@\022,\n\'k_EMsgClientToGC"
  "RequestEventTipsSummary\020\354@\0224\n/k_EMsgClie"
  "ntToGCRequestEventTipsSummaryResponse\020\355@"
  "\022&\n!k_EMsgClientToGCRequestSocialFeed\020\357@"
  "\022.\n)k_EMsgClientToGCRequestSocialFeedRes"
  "ponse\020\360@\022.\n)k_EMsgClientToGCRequestSocia"
  "lFeedComments\020\361@\0226\n1k_EMsgClientToGCRequ"
  "estSocialFeedCommentsResponse\020\362@\0223\n.k_EM"
  "sgClientToGCCavernCrawlGetClaimedRoomCou"
  "nt\020\364@\022;\n6k_EMsgClientToGCCavernCrawlGetC"
  "laimedRoomCountResponse\020\365@\0226\n1k_EMsgGCTo"
  "GCReconcilePlusAutoGrantItemsUnreliable\020"
  "\366@\022.\n)k_EMsgServerToGCAddBroadcastTimeli"
  "neEvent\020\367@\022,\n\'k_EMsgGCToServerUpdateStea"
  "mBroadcasting\020\370@\022&\n!k_EMsgClientToGCReco"
  "rdContestVote\020\371@\022.\n)k_EMsgGCToClientReco"
  "rdContestVoteResponse\020\372@\022\037\n\032k_EMsgGCToGC"
  "GrantAutograph\020\373@\022\'\n\"k_EMsgGCToGCGrantAu"
  "tographResponse\020\374@\022!\n\034k_EMsgSignOutConsu"
  "mableUsage\020\375@\022 \n\033k_EMsgLobbyEventGameDet"
  "ails\020\376@\022\036\n\031k_EMsgDevGrantEventPoints\020\377@\022"
  "&\n!k_EMsgDevGrantEventPointsResponse\020\200A\022"
  "\036\n\031k_EMsgDevGrantEventAction\020\201A\022&\n!k_EMs"
  "gDevGrantEventActionResponse\020\202A\022\035\n\030k_EMs"
  "gDevResetEventState\020\203A\022%\n k_EMsgDevReset"
  "EventStateResponse\020\204A\022(\n#k_EMsgGCToGCRec"
  "oncileEventOwnership\020\205A\022\'\n\"k_EMsgConsume"
  "EventSupportGrantItem\020\206A\022/\n*k_EMsgConsum"
  "eEventSupportGrantItemResponse\020\207A\0227\n2k_E"
  "MsgGCToClientClaimEventActionUsingItemCo"
  "mpleted\020\210A\022*\n%k_EMsgGCToClientCavernCraw"
  "lMapUpdated\020\211A\0227\n2k_EMsgServerToGCReques"
  "tPlayerRecentAccomplishments\020\212A\022\?\n:k_EMs"
  "gServerToGCRequestPlayerRecentAccomplish"
  "mentsResponse\020\213A\0227\n2k_EMsgClientToGCRequ"
  "estPlayerRecentAccomplishments\020\214A\022\?\n:k_E"
  "MsgClientToGCRequestPlayerRecentAccompli"
  "shmentsResponse\020\215A\022;\n6k_EMsgClientToGCRe"
  "questPlayerHeroRecentAccomplishments\020\216A\022"
  "C\n>k_EMsgClientToGCRequestPlayerHeroRece"
  "ntAccomplishmentsResponse\020\217A\022#\n\036k_EMsgSi"
  "gnOutEventActionGrants\020\220A\022.\n)k_EMsgClien"
  "tToGCRequestPlayerCoachMatches\020\221A\0226\n1k_E"
  "MsgClientToGCRequestPlayerCoachMatchesRe"
  "sponse\020\222A\022.\n)k_EMsgClientToGCSubmitCoach"
  "TeammateRating\020\225A\0226\n1k_EMsgClientToGCSub"
  "mitCoachTeammateRatingResponse\020\226A\0220\n+k_E"
  "MsgGCToClientCoachTeammateRatingsChanged"
  "\020\227A\022,\n\'k_EMsgClientToGCRequestPlayerCoac"
  "hMatch\020\231A\0224\n/k_EMsgClientToGCRequestPlay"
  "erCoachMatchResponse\020\232A\022(\n#k_EMsgClientT"
  "oGCRequestContestVotes\020\233A\0220\n+k_EMsgClien"
  "tToGCRequestContestVotesResponse\020\234A\022#\n\036k"
  "_EMsgClientToGCMVPVoteTimeout\020\235A\022+\n&k_EM"
  "sgClientToGCMVPVoteTimeoutResponse\020\236A\022 \n"
  "\033k_EMsgMatchMatchmakingStats\020\250A\022,\n\'k_EMs"
  "gClientToGCSubmitPlayerMatchSurvey\020\251A\0224\n"
  "/k_EMsgClientToGCSubmitPlayerMatchSurvey"
  "Response\020\252A\022/\n*k_EMsgSQLGCToGCGrantAllHe"
  "roProgressAccount\020\253A\022/\n*k_EMsgSQLGCToGCG"
  "rantAllHeroProgressVictory\020\254A\022 \n\033k_EMsgD"
  "evDeleteEventActions\020\255A\022(\n#k_EMsgDevDele"
  "teEventActionsResponse\020\256A\022\035\n\030k_EMsgDevRe"
  "loadAllEvents\020\257A\022%\n k_EMsgDevReloadAllEv"
  "entsResponse\020\260A\022\"\n\035k_EMsgGCToGCGetAllHer"
  "oCurrent\020\273C\022*\n%k_EMsgGCToGCGetAllHeroCur"
  "rentResponse\020\274C\022%\n k_EMsgGCSubmitPlayerA"
  "voidRequest\020\275C\022-\n(k_EMsgGCSubmitPlayerAv"
  "oidRequestResponse\020\276C\022)\n$k_EMsgGCToClien"
  "tNotificationsUpdated\020\277C\022/\n*k_EMsgGCtoGC"
  "AssociatedExploiterAccountInfo\020\300C\0227\n2k_E"
  "MsgGCtoGCAssociatedExploiterAccountInfoR"
  "esponse\020\301C\022*\n%k_EMsgGCtoGCRequestRecalib"
  "rationCheck\020\302C\022 \n\033k_EMsgGCToClientVACRem"
  "inder\020\303C\022\"\n\035k_EMsgClientToGCUnderDraftBu"
  "y\020\304C\022*\n%k_EMsgClientToGCUnderDraftBuyRes"
  "ponse\020\305C\022%\n k_EMsgClientToGCUnderDraftRe"
  "roll\020\306C\022-\n(k_EMsgClientToGCUnderDraftRer"
  "ollResponse\020\307C\022\033\n\026k_EMsgNeutralItemStats"
  "\020\310C\022 \n\033k_EMsgClientToGCCreateGuild\020\311C\022(\n"
  "#k_EMsgClientToGCCreateGuildResponse\020\312C\022"
  "!\n\034k_EMsgClientToGCSetGuildInfo\020\313C\022)\n$k_"
  "EMsgClientToGCSetGuildInfoResponse\020\314C\022!\n"
  "\034k_EMsgClientToGCAddGuildRole\020\315C\022)\n$k_EM"
  "sgClientToGCAddGuildRoleResponse\020\316C\022$\n\037k"
  "_EMsgClientToGCModifyGuildRole\020\317C\022,\n\'k_E"
  "MsgClientToGCModifyGuildRoleResponse\020\320C\022"
  "$\n\037k_EMsgClientToGCRemoveGuildRole\020\321C\022,\n"
  "\'k_EMsgClientToGCRemoveGuildRoleResponse"
  "\020\322C\022\036\n\031k_EMsgClientToGCJoinGuild\020\323C\022&\n!k"
  "_EMsgClientToGCJoinGuildResponse\020\324C\022\037\n\032k"
  "_EMsgClientToGCLeaveGuild\020\325C\022\'\n\"k_EMsgCl"
  "ientToGCLeaveGuildResponse\020\326C\022\"\n\035k_EMsgC"
  "lientToGCInviteToGuild\020\327C\022*\n%k_EMsgClien"
  "tToGCInviteToGuildResponse\020\330C\022)\n$k_EMsgC"
  "lientToGCDeclineInviteToGuild\020\331C\0221\n,k_EM"
  "sgClientToGCDeclineInviteToGuildResponse"
  "\020\332C\022(\n#k_EMsgClientToGCCancelInviteToGui"
  "ld\020\333C\0220\n+k_EMsgClientToGCCancelInviteToG"
  "uildResponse\020\334C\022$\n\037k_EMsgClientToGCKickG"
  "uildMember\020\335C\022,\n\'k_EMsgClientToGCKickGui"
  "ldMemberResponse\020\336C\022\'\n\"k_EMsgClientToGCS"
  "etGuildMemberRole\020\337C\022/\n*k_EMsgClientToGC"
  "SetGuildMemberRoleResponse\020\340C\022%\n k_EMsgC"
  "lientToGCRequestGuildData\020\341C\022-\n(k_EMsgCl"
  "ientToGCRequestGuildDataResponse\020\342C\022%\n k"
  "_EMsgGCToClientGuildDataUpdated\020\343C\022+\n&k_"
  "EMsgClientToGCRequestGuildMembership\020\344C\022"
  "3\n.k_EMsgClientToGCRequestGuildMembershi"
  "pResponse\020\345C\022+\n&k_EMsgGCToClientGuildMem"
  "bershipUpdated\020\346C\022(\n#k_EMsgClientToGCAcc"
  "eptInviteToGuild\020\351C\0220\n+k_EMsgClientToGCA"
  "cceptInviteToGuildResponse\020\352C\022&\n!k_EMsgC"
  "lientToGCSetGuildRoleOrder\020\353C\022.\n)k_EMsgC"
  "lientToGCSetGuildRoleOrderResponse\020\354C\022%\n"
  " k_EMsgClientToGCRequestGuildFeed\020\355C\022-\n("
  "k_EMsgClientToGCRequestGuildFeedResponse"
  "\020\356C\0221\n,k_EMsgClientToGCRequestAccountGui"
  "ldEventData\020\357C\0229\n4k_EMsgClientToGCReques"
  "tAccountGuildEventDataResponse\020\360C\0221\n,k_E"
  "MsgGCToClientAccountGuildEventDataUpdate"
  "d\020\361C\0220\n+k_EMsgClientToGCRequestActiveGui"
  "ldContracts\020\362C\0228\n3k_EMsgClientToGCReques"
  "tActiveGuildContractsResponse\020\363C\0220\n+k_EM"
  "sgGCToClientActiveGuildContractsUpdated\020"
  "\364C\022%\n k_EMsgGCToClientGuildFeedUpdated\020\365"
  "C\022(\n#k_EMsgClientToGCSelectGuildContract"
  "\020\366C\0220\n+k_EMsgClientToGCSelectGuildContra"
  "ctResponse\020\367C\022\'\n\"k_EMsgGCToGCCompleteGui"
  "ldContracts\020\370C\022)\n$k_EMsgClientToGCAddPla"
  "yerToGuildChat\020\372C\0221\n,k_EMsgClientToGCAdd"
  "PlayerToGuildChatResponse\020\373C\022#\n\036k_EMsgCl"
  "ientToGCUnderDraftSell\020\374C\022+\n&k_EMsgClien"
  "tToGCUnderDraftSellResponse\020\375C\022&\n!k_EMsg"
  "ClientToGCUnderDraftRequest\020\376C\022\'\n\"k_EMsg"
  "ClientToGCUnderDraftResponse\020\377C\022+\n&k_EMs"
  "gClientToGCUnderDraftRedeemReward\020\200D\0223\n."
  "k_EMsgClientToGCUnderDraftRedeemRewardRe"
  "sponse\020\201D\022&\n!k_EMsgGCToServerLobbyHeroBa"
  "nRates\020\204D\022\'\n\"k_EMsgSignOutGuildContractP"
  "rogress\020\207D\022\032\n\025k_EMsgSignOutMVPStats\020\210D\0220"
  "\n+k_EMsgClientToGCRequestActiveGuildChal"
  "lenge\020\211D\0228\n3k_EMsgClientToGCRequestActiv"
  "eGuildChallengeResponse\020\212D\0220\n+k_EMsgGCTo"
  "ClientActiveGuildChallengeUpdated\020\213D\022+\n&"
  "k_EMsgClientToGCRequestReporterUpdates\020\214"
  "D\0223\n.k_EMsgClientToGCRequestReporterUpda"
  "tesResponse\020\215D\022/\n*k_EMsgClientToGCAcknow"
  "ledgeReporterUpdates\020\216D\022(\n#k_EMsgSignOut"
  "GuildChallengeProgress\020\220D\022-\n(k_EMsgClien"
  "tToGCRequestGuildEventMembers\020\221D\0225\n0k_EM"
  "sgClientToGCRequestGuildEventMembersResp"
  "onse\020\222D\022\'\n\"k_EMsgClientToGCReportGuildCo"
  "ntent\020\225D\022/\n*k_EMsgClientToGCReportGuildC"
  "ontentResponse\020\226D\0223\n.k_EMsgClientToGCReq"
  "uestAccountGuildPersonaInfo\020\227D\022;\n6k_EMsg"
  "ClientToGCRequestAccountGuildPersonaInfo"
  "Response\020\230D\0228\n3k_EMsgClientToGCRequestAc"
  "countGuildPersonaInfoBatch\020\231D\022@\n;k_EMsgC"
  "lientToGCRequestAccountGuildPersonaInfoB"
  "atchResponse\020\232D\022*\n%k_EMsgGCToClientUnder"
  "DraftGoldUpdated\020\233D\022\032\n\025k_EMsgSignOutBoun"
  "ties\020\235D\022(\n#k_EMsgLobbyFeaturedGamemodePr"
  "ogress\020\236D\022 \n\033k_EMsgLobbyGauntletProgress"
  "\020\237D\0221\n,k_EMsgClientToGCSubmitDraftTrivia"
  "MatchAnswer\020\240D\0229\n4k_EMsgClientToGCSubmit"
  "DraftTriviaMatchAnswerResponse\020\241D\022#\n\036k_E"
  "MsgGCToGCSignoutSpendBounty\020\242D\022(\n#k_EMsg"
  "ClientToGCApplyGauntletTicket\020\243D\022,\n\'k_EM"
  "sgClientToGCUnderDraftRollBackBench\020\244D\0224"
  "\n/k_EMsgClientToGCUnderDraftRollBackBenc"
  "hResponse\020\245D\022$\n\037k_EMsgGCToGCGetEventActi"
  "onScore\020\246D\022,\n\'k_EMsgGCToGCGetEventAction"
  "ScoreResponse\020\247D\022&\n!k_EMsgServerToGCGetG"
  "uildContracts\020\250D\022.\n)k_EMsgServerToGCGetG"
  "uildContractsResponse\020\251D\022\035\n\030k_EMsgLobbyE"
  "ventGameData\020\252D\022,\n\'k_EMsgGCToClientGuild"
  "MembersDataUpdated\020\253D\022\'\n\"k_EMsgSignOutRe"
  "portActivityMarkers\020\254D\022\037\n\032k_EMsgSignOutD"
  "iretideCandy\020\255D\0222\n-k_EMsgGCToClientPostG"
  "ameItemAwardNotification\020\256D\022&\n!k_EMsgCli"
  "entToGCGetOWMatchDetails\020\257D\022.\n)k_EMsgCli"
  "entToGCGetOWMatchDetailsResponse\020\260D\022\'\n\"k"
  "_EMsgClientToGCSubmitOWConviction\020\261D\022/\n*"
  "k_EMsgClientToGCSubmitOWConvictionRespon"
  "se\020\262D\022%\n k_EMsgGCToGCGetAccountSteamChin"
  "a\020\263D\022-\n(k_EMsgGCToGCGetAccountSteamChina"
  "Response\020\264D\022,\n\'k_EMsgClientToGCClaimLead"
  "erboardRewards\020\265D\0224\n/k_EMsgClientToGCCla"
  "imLeaderboardRewardsResponse\020\266D\022#\n\036k_EMs"
  "gClientToGCRecalibrateMMR\020\267D\022+\n&k_EMsgCl"
  "ientToGCRecalibrateMMRResponse\020\270D\022*\n%k_E"
  "MsgGCToGCGrantEventPointActionList\020\271D\022\'\n"
  "\"k_EMsgClientToGCChinaSSAURLRequest\020\274D\022("
  "\n#k_EMsgClientToGCChinaSSAURLResponse\020\275D"
  "\022,\n\'k_EMsgClientToGCChinaSSAAcceptedRequ"
  "est\020\276D\022-\n(k_EMsgClientToGCChinaSSAAccept"
  "edResponse\020\277D\022$\n\037k_EMsgSignOutOverwatchS"
  "uspicion\020\300D\022\'\n\"k_EMsgServerToGCGetSuspic"
  "ionConfig\020\301D\022/\n*k_EMsgServerToGCGetSuspi"
  "cionConfigResponse\020\302D\0223\n.k_EMsgGCToGCGra"
  "ntPlusHeroChallengeMatchResults\020\303D\022,\n\'k_"
  "EMsgGCToClientOverwatchCasesAvailable\020\304D"
  "\022!\n\034k_EMsgServerToGCAccountCheck\020\305D\022+\n&k"
  "_EMsgClientToGCStartWatchingOverwatch\020\306D"
  "\022*\n%k_EMsgClientToGCStopWatchingOverwatc"
  "h\020\307D\022\032\n\025k_EMsgSignOutPerfData\020\310D\022$\n\037k_EM"
  "sgClientToGCGetDPCFavorites\020\311D\022,\n\'k_EMsg"
  "ClientToGCGetDPCFavoritesResponse\020\312D\022(\n#"
  "k_EMsgClientToGCSetDPCFavoriteState\020\313D\0220"
  "\n+k_EMsgClientToGCSetDPCFavoriteStateRes"
  "ponse\020\314D\022)\n$k_EMsgClientToGCOverwatchRep"
  "layError\020\315D\022+\n&k_EMsgServerToGCPlayerCha"
  "llengeHistory\020\316D\022\031\n\024k_EMsgSignOutBanData"
  "\020\317D\022!\n\034k_EMsgWebapiDPCSeasonResults\020\320D\022 "
  "\n\033k_EMsgClientToGCCoachFriend\020\321D\022(\n#k_EM"
  "sgClientToGCCoachFriendResponse\020\322D\0222\n-k_"
  "EMsgClientToGCRequestPrivateCoachingSess"
  "ion\020\323D\022:\n5k_EMsgClientToGCRequestPrivate"
  "CoachingSessionResponse\020\324D\0221\n,k_EMsgClie"
  "ntToGCAcceptPrivateCoachingSession\020\325D\0229\n"
  "4k_EMsgClientToGCAcceptPrivateCoachingSe"
  "ssionResponse\020\326D\0220\n+k_EMsgClientToGCLeav"
  "ePrivateCoachingSession\020\327D\0228\n3k_EMsgClie"
  "ntToGCLeavePrivateCoachingSessionRespons"
  "e\020\330D\0225\n0k_EMsgClientToGCGetCurrentPrivat"
  "eCoachingSession\020\331D\022=\n8k_EMsgClientToGCG"
  "etCurrentPrivateCoachingSessionResponse\020"
  "\332D\0222\n-k_EMsgGCToClientPrivateCoachingSes"
  "sionUpdated\020\333D\0227\n2k_EMsgClientToGCSubmit"
  "PrivateCoachingSessionRating\020\334D\022\?\n:k_EMs"
  "gClientToGCSubmitPrivateCoachingSessionR"
  "atingResponse\020\335D\0228\n3k_EMsgClientToGCGetA"
  "vailablePrivateCoachingSessions\020\336D\022@\n;k_"
  "EMsgClientToGCGetAvailablePrivateCoachin"
  "gSessionsResponse\020\337D\022\?\n:k_EMsgClientToGC"
  "GetAvailablePrivateCoachingSessionsSumma"
  "ry\020\340D\022G\nBk_EMsgClientToGCGetAvailablePri"
  "vateCoachingSessionsSummaryResponse\020\341D\0224"
  "\n/k_EMsgClientToGCJoinPrivateCoachingSes"
  "sionLobby\020\342D\022<\n7k_EMsgClientToGCJoinPriv"
  "ateCoachingSessionLobbyResponse\020\343D\0220\n+k_"
  "EMsgClientToGCRespondToCoachFriendReques"
  "t\020\344D\0228\n3k_EMsgClientToGCRespondToCoachFr"
  "iendRequestResponse\020\345D\022+\n&k_EMsgClientTo"
  "GCSetEventActiveSeasonID\020\346D\0223\n.k_EMsgCli"
  "entToGCSetEventActiveSeasonIDResponse\020\347D"
  "\0227\n2k_EMsgServerToGCMatchPlayerNeutralIt"
  "emEquipHistory\020\350D\0226\n1k_EMsgServerToGCCom"
  "pendiumChosenInGamePredictions\020\351D\022-\n(k_E"
  "MsgClientToGCCreateTeamPlayerCardPack\020\352D"
  "\0225\n0k_EMsgClientToGCCreateTeamPlayerCard"
  "PackResponse\020\353D\022$\n\037k_EMsgGCToServerSubmi"
  "tCheerData\020\354D\022 \n\033k_EMsgGCToServerCheerCo"
  "nfig\020\355D\022#\n\036k_EMsgServerToGCGetCheerConfi"
  "g\020\356D\022+\n&k_EMsgServerToGCGetCheerConfigRe"
  "sponse\020\357D\022#\n\036k_EMsgGCToGCGrantAutographB"
  "yID\020\360D\022(\n#k_EMsgGCToServerCheerScalesOve"
  "rride\020\361D\022\"\n\035k_EMsgGCToServerGetCheerStat"
  "e\020\362D\022%\n k_EMsgServerToGCReportCheerState"
  "\020\363D\022!\n\034k_EMsgGCToServerScenarioSave\020\364D\022*"
  "\n%k_EMsgGCToServerAbilityDraftLobbyData\020"
  "\365D\022&\n!k_EMsgSignOutReportCommunications\020"
  "\366D\0224\n/k_EMsgClientToGCBatchGetPlayerCard"
  "RosterRequest\020\367D\0225\n0k_EMsgClientToGCBatc"
  "hGetPlayerCardRosterResponse\020\370D\022*\n%k_EMs"
  "gClientToGCGetStickerbookRequest\020\371D\022+\n&k"
  "_EMsgClientToGCGetStickerbookResponse\020\372D"
  "\0221\n,k_EMsgClientToGCCreateStickerbookPag"
  "eRequest\020\373D\0222\n-k_EMsgClientToGCCreateSti"
  "ckerbookPageResponse\020\374D\0221\n,k_EMsgClientT"
  "oGCDeleteStickerbookPageRequest\020\375D\0222\n-k_"
  "EMsgClientToGCDeleteStickerbookPageRespo"
  "nse\020\376D\022)\n$k_EMsgClientToGCPlaceStickersR"
  "equest\020\377D\022*\n%k_EMsgClientToGCPlaceSticke"
  "rsResponse\020\200E\0223\n.k_EMsgClientToGCPlaceCo"
  "llectionStickersRequest\020\201E\0224\n/k_EMsgClie"
  "ntToGCPlaceCollectionStickersResponse\020\202E"
  "\0224\n/k_EMsgClientToGCOrderStickerbookTeam"
  "PageRequest\020\203E\0225\n0k_EMsgClientToGCOrderS"
  "tickerbookTeamPageResponse\020\204E\022%\n k_EMsgS"
  "erverToGCGetStickerHeroes\020\205E\022-\n(k_EMsgSe"
  "rverToGCGetStickerHeroesResponse\020\206E\022)\n$k"
  "_EMsgClientToGCCandyShopGetUserData\020\210E\0221"
  "\n,k_EMsgClientToGCCandyShopGetUserDataRe"
  "sponse\020\211E\022-\n(k_EMsgGCToClientCandyShopUs"
  "erDataUpdated\020\212E\022,\n\'k_EMsgClientToGCCand"
  "yShopPurchaseReward\020\213E\0224\n/k_EMsgClientTo"
  "GCCandyShopPurchaseRewardResponse\020\214E\022(\n#"
  "k_EMsgClientToGCCandyShopDoExchange\020\215E\0220"
  "\n+k_EMsgClientToGCCandyShopDoExchangeRes"
  "ponse\020\216E\0220\n+k_EMsgClientToGCCandyShopDoV"
  "ariableExchange\020\217E\0228\n3k_EMsgClientToGCCa"
  "ndyShopDoVariableExchangeResponse\020\220E\022+\n&"
  "k_EMsgClientToGCCandyShopRerollRewards\020\221"
  "E\0223\n.k_EMsgClientToGCCandyShopRerollRewa"
  "rdsResponse\020\222E\022#\n\036k_EMsgClientToGCSetHer"
  "oSticker\020\223E\022+\n&k_EMsgClientToGCSetHeroSt"
  "ickerResponse\020\224E\022$\n\037k_EMsgClientToGCGetH"
  "eroStickers\020\225E\022,\n\'k_EMsgClientToGCGetHer"
  "oStickersResponse\020\226E\022$\n\037k_EMsgClientToGC"
  "SetFavoritePage\020\227E\022,\n\'k_EMsgClientToGCSe"
  "tFavoritePageResponse\020\230E\022+\n&k_EMsgClient"
  "ToGCCandyShopDevGrantCandy\020\231E\0223\n.k_EMsgC"
  "lientToGCCandyShopDevGrantCandyResponse\020"
  "\232E\022/\n*k_EMsgClientToGCCandyShopDevClearI"
  "nventory\020\233E\0227\n2k_EMsgClientToGCCandyShop"
  "DevClearInventoryResponse\020\234E\022&\n!k_EMsgCl"
  "ientToGCCandyShopOpenBags\020\235E\022.\n)k_EMsgCl"
  "ientToGCCandyShopOpenBagsResponse\020\236E\022/\n*"
  "k_EMsgClientToGCCandyShopDevGrantCandyBa"
  "gs\020\237E\0227\n2k_EMsgClientToGCCandyShopDevGra"
  "ntCandyBagsResponse\020\240E\0220\n+k_EMsgClientTo"
  "GCCandyShopDevShuffleExchange\020\241E\0228\n3k_EM"
  "sgClientToGCCandyShopDevShuffleExchangeR"
  "esponse\020\242E\0223\n.k_EMsgClientToGCCandyShopD"
  "evGrantRerollCharges\020\243E\022;\n6k_EMsgClientT"
  "oGCCandyShopDevGrantRerollChargesRespons"
  "e\020\244E\022%\n k_EMsgLobbyAdditionalAccountData"
  "\020\245E\022%\n k_EMsgServerToGCLobbyInitialized\020"
  "\246E\0228\n3k_EMsgClientToGCCollectorsCacheAva"
  "ilableDataRequest\020\247E\0229\n4k_EMsgGCToClient"
  "CollectorsCacheAvailableDataResponse\020\250E\022"
  "$\n\037k_EMsgClientToGCUploadMatchClip\020\251E\022,\n"
  "\'k_EMsgGCToClientUploadMatchClipResponse"
  "\020\252E\022 \n\033k_EMsgSignOutMuertaMinigame\020\255E\022\'\n"
  "\"k_EMsgGCToServerLobbyHeroRoleStats\020\256E\022 "
  "\n\033k_EMsgClientToGCRankRequest\020\257E\022!\n\034k_EM"
  "sgGCToClientRankResponse\020\260E\022\037\n\032k_EMsgGCT"
  "oClientRankUpdate\020\261E\022\032\n\025k_EMsgSignOutMap"
  "Stats\020\262E\022$\n\037k_EMsgClientToGCMapStatsRequ"
  "est\020\263E\022%\n k_EMsgGCToClientMapStatsRespon"
  "se\020\264E\022(\n#k_EMsgClientToGCShowcaseGetUser"
  "Data\020\266E\0220\n+k_EMsgClientToGCShowcaseGetUs"
  "erDataResponse\020\267E\022(\n#k_EMsgClientToGCSho"
  "wcaseSetUserData\020\270E\0220\n+k_EMsgClientToGCS"
  "howcaseSetUserDataResponse\020\271E\022+\n&k_EMsgC"
  "lientToGCFantasyCraftingGetData\020\272E\0223\n.k_"
  "EMsgClientToGCFantasyCraftingGetDataResp"
  "onse\020\273E\0224\n/k_EMsgClientToGCFantasyCrafti"
  "ngPerformOperation\020\274E\022<\n7k_EMsgClientToG"
  "CFantasyCraftingPerformOperationResponse"
  "\020\275E\0222\n-k_EMsgGCToClientFantasyCraftingGe"
  "tDataUpdated\020\276E\0223\n.k_EMsgClientToGCFanta"
  "syCraftingDevModifyTablet\020\277E\022;\n6k_EMsgCl"
  "ientToGCFantasyCraftingDevModifyTabletRe"
  "sponse\020\300E\022&\n!k_EMsgClientToGCRoadToTIGet"
  "Quests\020\301E\022.\n)k_EMsgClientToGCRoadToTIGet"
  "QuestsResponse\020\302E\022+\n&k_EMsgClientToGCRoa"
  "dToTIGetActiveQuest\020\303E\0223\n.k_EMsgClientTo"
  "GCRoadToTIGetActiveQuestResponse\020\304E\022%\n k"
  "_EMsgClientToGCBingoGetUserData\020\305E\022-\n(k_"
  "EMsgClientToGCBingoGetUserDataResponse\020\306"
  "E\022\"\n\035k_EMsgClientToGCBingoClaimRow\020\307E\022*\n"
  "%k_EMsgClientToGCBingoClaimRowResponse\020\310"
  "E\022\'\n\"k_EMsgClientToGCBingoDevRerollCard\020"
  "\311E\022/\n*k_EMsgClientToGCBingoDevRerollCard"
  "Response\020\312E\022&\n!k_EMsgClientToGCBingoGetS"
  "tatsData\020\313E\022.\n)k_EMsgClientToGCBingoGetS"
  "tatsDataResponse\020\314E\022)\n$k_EMsgGCToClientB"
  "ingoUserDataUpdated\020\315E\022-\n(k_EMsgGCToClie"
  "ntRoadToTIQuestDataUpdated\020\316E\022$\n\037k_EMsgC"
  "lientToGCRoadToTIUseItem\020\317E\022,\n\'k_EMsgCli"
  "entToGCRoadToTIUseItemResponse\020\320E\022)\n$k_E"
  "MsgClientToGCShowcaseSubmitReport\020\321E\0221\n,"
  "k_EMsgClientToGCShowcaseSubmitReportResp"
  "onse\020\322E\0226\n1k_EMsgClientToGCShowcaseAdmin"
  "GetReportsRollupList\020\323E\022>\n9k_EMsgClientT"
  "oGCShowcaseAdminGetReportsRollupListResp"
  "onse\020\324E\0222\n-k_EMsgClientToGCShowcaseAdmin"
  "GetReportsRollup\020\325E\022:\n5k_EMsgClientToGCS"
  "howcaseAdminGetReportsRollupResponse\020\326E\022"
  "0\n+k_EMsgClientToGCShowcaseAdminGetUserD"
  "etails\020\327E\0228\n3k_EMsgClientToGCShowcaseAdm"
  "inGetUserDetailsResponse\020\330E\022)\n$k_EMsgCli"
  "entToGCShowcaseAdminConvict\020\331E\0221\n,k_EMsg"
  "ClientToGCShowcaseAdminConvictResponse\020\332"
  "E\022+\n&k_EMsgClientToGCShowcaseAdminExoner"
  "ate\020\333E\0223\n.k_EMsgClientToGCShowcaseAdminE"
  "xonerateResponse\020\334E\022\'\n\"k_EMsgClientToGCS"
  "howcaseAdminReset\020\335E\022/\n*k_EMsgClientToGC"
  "ShowcaseAdminResetResponse\020\336E\022-\n(k_EMsgC"
  "lientToGCShowcaseAdminLockAccount\020\337E\0225\n0"
  "k_EMsgClientToGCShowcaseAdminLockAccount"
  "Response\020\340E\0220\n+k_EMsgClientToGCFantasyCr"
  "aftingSelectPlayer\020\341E\0228\n3k_EMsgClientToG"
  "CFantasyCraftingSelectPlayerResponse\020\342E\022"
  "3\n.k_EMsgClientToGCFantasyCraftingGenera"
  "teTablets\020\343E\022;\n6k_EMsgClientToGCFantasyC"
  "raftingGenerateTabletsResponse\020\344E\0222\n-k_E"
  "MsgClientToGcFantasyCraftingUpgradeTable"
  "ts\020\345E\022:\n5k_EMsgClientToGcFantasyCrafting"
  "UpgradeTabletsResponse\020\346E\0221\n,k_EMsgClien"
  "tToGCFantasyCraftingRerollOptions\020\350E\0229\n4"
  "k_EMsgClientToGCFantasyCraftingRerollOpt"
  "ionsResponse\020\351E\022*\n%k_EMsgClientToGCRoadT"
  "oTIDevForceQuest\020\347E\022&\n!k_EMsgLobbyRoadTo"
  "TIMatchQuestData\020\353E\022/\n*k_EMsgClientToGCS"
  "howcaseModerationGetQueue\020\354E\0227\n2k_EMsgCl"
  "ientToGCShowcaseModerationGetQueueRespon"
  "se\020\355E\0226\n1k_EMsgClientToGCShowcaseModerat"
  "ionApplyModeration\020\356E\022>\n9k_EMsgClientToG"
  "CShowcaseModerationApplyModerationRespon"
  "se\020\357E\022)\n$k_EMsgClientToGCOverworldGetUse"
  "rData\020\360E\0221\n,k_EMsgClientToGCOverworldGet"
  "UserDataResponse\020\361E\022*\n%k_EMsgClientToGCO"
  "verworldCompletePath\020\362E\0222\n-k_EMsgClientT"
  "oGCOverworldCompletePathResponse\020\363E\0222\n-k"
  "_EMsgClientToGCOverworldClaimEncounterRe"
  "ward\020\364E\022:\n5k_EMsgClientToGCOverworldClai"
  "mEncounterRewardResponse\020\365E\022)\n$k_EMsgCli"
  "entToGCOverworldDevResetAll\020\366E\0221\n,k_EMsg"
  "ClientToGCOverworldDevResetAllResponse\020\367"
  "E\022*\n%k_EMsgClientToGCOverworldDevResetNo"
  "de\020\370E\0222\n-k_EMsgClientToGCOverworldDevRes"
  "etNodeResponse\020\371E\022*\n%k_EMsgClientToGCOve"
  "rworldDevResetPath\020\372E\0222\n-k_EMsgClientToG"
  "COverworldDevResetPathResponse\020\373E\022,\n\'k_E"
  "MsgClientToGCOverworldDevGrantTokens\020\374E\022"
  "4\n/k_EMsgClientToGCOverworldDevGrantToke"
  "nsResponse\020\375E\022/\n*k_EMsgClientToGCOverwor"
  "ldDevClearInventory\020\376E\0227\n2k_EMsgClientTo"
  "GCOverworldDevClearInventoryResponse\020\377E\022"
  "!\n\034k_EMsgServerToGCNewBloomGift\020\200F\022)\n$k_"
  "EMsgServerToGCNewBloomGiftResponse\020\201F\022-\n"
  "(k_EMsgGCToClientOverworldUserDataUpdate"
  "d\020\202F\022(\n#k_EMsgClientToGCOverworldMoveToN"
  "ode\020\203F\0220\n+k_EMsgClientToGCOverworldMoveT"
  "oNodeResponse\020\204F\022!\n\034k_EMsgClientToGCNewB"
  "loomGift\020\205F\022)\n$k_EMsgClientToGCNewBloomG"
  "iftResponse\020\206F\022\033\n\026k_EMsgSignOutOverworld"
  "\020\207F\022$\n\037k_EMsgClientToGCSetBannedHeroes\020\211"
  "F\022)\n$k_EMsgClientToGCOverworldTradeToken"
  "s\020\212F\0221\n,k_EMsgClientToGCOverworldTradeTo"
  "kensResponse\020\213F\022.\n)k_EMsgOverworldEncoun"
  "terTokenTreasureData\020\214F\022+\n&k_EMsgOverwor"
  "ldEncounterTokenQuestData\020\215F\022+\n&k_EMsgOv"
  "erworldEncounterChooseHeroData\020\216F\022)\n$k_E"
  "MsgClientToGCUpdateComicBookStats\020\217F\022*\n%"
  "k_EMsgClientToGCCandyShopDevResetShop\020\220F"
  "\0222\n-k_EMsgClientToGCCandyShopDevResetSho"
  "pResponse\020\221F\022)\n$k_EMsgOverworldEncounter"
  "ProgressData\020\222F\022&\n!k_EMsgClientToGCOverw"
  "orldFeedback\020\223F\022.\n)k_EMsgClientToGCOverw"
  "orldFeedbackResponse\020\224F\022,\n\'k_EMsgClientT"
  "oGCOverworldVisitEncounter\020\225F\0224\n/k_EMsgC"
  "lientToGCOverworldVisitEncounterResponse"
  "\020\226F\022(\n#k_EMsgClientToGCOverworldGiftToke"
  "ns\020\227F\0220\n+k_EMsgClientToGCOverworldGiftTo"
  "kensResponse\020\230F\022%\n k_EMsgClientToGCDotaL"
  "absFeedback\020\231F\022-\n(k_EMsgClientToGCDotaLa"
  "bsFeedbackResponse\020\232F\0221\n,k_EMsgOverworld"
  "EncounterPitFighterRewardData\020\233F\022-\n(k_EM"
  "sgClientToGCOverworldGetDynamicImage\020\234F\022"
  "5\n0k_EMsgClientToGCOverworldGetDynamicIm"
  "ageResponse\020\235F\0220\n+k_EMsgClientToGCFighti"
  "ngGameChallengeFriend\020\236F\0228\n3k_EMsgClient"
  "ToGCFightingGameChallengeFriendResponse\020"
  "\237F\0226\n1k_EMsgClientToGCFightingGameCancel"
  "ChallengeFriend\020\240F\0220\n+k_EMsgClientToGCFi"
  "ghtingGameAnswerChallenge\020\241F\0228\n3k_EMsgCl"
  "ientToGCFightingGameAnswerChallengeRespo"
  "nse\020\242F\022*\n%k_EMsgGCToClientFightingGameCh"
  "allenge\020\243F\022+\n&k_EMsgGCToClientFightingGa"
  "meStartMatch\020\244F\0222\n-k_EMsgGCToClientFight"
  "ingGameChallengeCanceled\020\245F\022%\n k_EMsgCli"
  "entToGCBingoShuffleCard\020\247F\022-\n(k_EMsgClie"
  "ntToGCBingoShuffleCardResponse\020\250F\022&\n!k_E"
  "MsgClientToGCBingoModifySquare\020\251F\022.\n)k_E"
  "MsgClientToGCBingoModifySquareResponse\020\252"
  "F\022&\n!k_EMsgClientToGCBingoDevAddTokens\020\253"
  "F\022.\n)k_EMsgClientToGCBingoDevAddTokensRe"
  "sponse\020\254F\022+\n&k_EMsgClientToGCBingoDevCle"
  "arInventory\020\255F\0223\n.k_EMsgClientToGCBingoD"
  "evClearInventoryResponse\020\256F\022*\n%k_EMsgGCC"
  "ompendiumRemoveAllSelections\020\257F\0222\n-k_EMs"
  "gGCCompendiumRemoveAllSelectionsResponse"
  "\020\260F\022,\n\'k_EMsgClientToGCOverworldMinigame"
  "Action\020\261F\0224\n/k_EMsgClientToGCOverworldMi"
  "nigameActionResponse\020\262F\022\'\n\"k_EMsgClientT"
  "oGCSurvivorsTelemetry\020\263F\022/\n*k_EMsgClient"
  "ToGCSurvivorsTelemetryResponse\020\264F\0229\n4k_E"
  "MsgClientToGCOverworldRequestTokensNeede"
  "dByFriend\020\265F\022A\n<k_EMsgClientToGCOverworl"
  "dRequestTokensNeededByFriendResponse\020\266F\022"
  "*\n%k_EMsgClientToGCCraftworksGetUserData"
  "\020\267F\0222\n-k_EMsgClientToGCCraftworksGetUser"
  "DataResponse\020\270F\022.\n)k_EMsgGCToClientCraft"
  "worksUserDataUpdated\020\271F\022*\n%k_EMsgClientT"
  "oGCCraftworksCraftRecipe\020\272F\0222\n-k_EMsgCli"
  "entToGCCraftworksCraftRecipeResponse\020\273F\022"
  "2\n-k_EMsgClientToGCCraftworksDevModifyCo"
  "mponents\020\274F\022:\n5k_EMsgClientToGCCraftwork"
  "sDevModifyComponentsResponse\020\275F\022\034\n\027k_EMs"
  "gSignOutCraftworks\020\276F\022-\n(k_EMsgClientToG"
  "CMonsterHunterGetUserData\020\277F\0225\n0k_EMsgCl"
  "ientToGCMonsterHunterGetUserDataResponse"
  "\020\300F\022-\n(k_EMsgClientToGCMonsterHunterClai"
  "mReward\020\301F\0225\n0k_EMsgClientToGCMonsterHun"
  "terClaimRewardResponse\020\302F\0220\n+k_EMsgClien"
  "tToGCMonsterHunterTradeMaterials\020\303F\0228\n3k"
  "_EMsgClientToGCMonsterHunterTradeMateria"
  "lsResponse\020\304F\022/\n*k_EMsgClientToGCMonster"
  "HunterGiftMaterials\020\305F\0227\n2k_EMsgClientTo"
  "GCMonsterHunterGiftMaterialsResponse\020\306F\022"
  "@\n;k_EMsgClientToGCMonsterHunterRequestM"
  "aterialsNeededByFriend\020\307F\022H\nCk_EMsgClien"
  "tToGCMonsterHunterRequestMaterialsNeeded"
  "ByFriendResponse\020\310F\022-\n(k_EMsgClientToGCM"
  "onsterHunterDevResetAll\020\311F\0225\n0k_EMsgClie"
  "ntToGCMonsterHunterDevResetAllResponse\020\312"
  "F\0223\n.k_EMsgClientToGCMonsterHunterDevGra"
  "ntMaterials\020\313F\022;\n6k_EMsgClientToGCMonste"
  "rHunterDevGrantMaterialsResponse\020\314F\0223\n.k"
  "_EMsgClientToGCMonsterHunterDevClearInve"
  "ntory\020\315F\022;\n6k_EMsgClientToGCMonsterHunte"
  "rDevClearInventoryResponse\020\316F\022>\n9k_EMsgC"
  "lientToGCMonsterHunterDevClaimInvestigat"
  "ionRewards\020\317F\022F\nAk_EMsgClientToGCMonster"
  "HunterDevClaimInvestigationRewardsRespon"
  "se\020\320F\0221\n,k_EMsgGCToClientMonsterHunterUs"
  "erDataUpdated\020\321F\022\037\n\032k_EMsgSignOutMonster"
  "Hunter\020\322F\022$\n\037k_EMsgClientToGCClaimGatedE"
  "vent\020\323F\022,\n\'k_EMsgClientToGCClaimGatedEve"
  "ntResponse\020\324F\0224\n/k_EMsgClientToGCMonster"
  "HunterDevModifyHeroCodex\020\325F\022<\n7k_EMsgCli"
  "entToGCMonsterHunterDevModifyHeroCodexRe"
  "sponse\020\326F\0222\n-k_EMsgClientToGCMonsterHunt"
  "erClaimCodexReward\020\327F\022:\n5k_EMsgClientToG"
  "CMonsterHunterClaimCodexRewardResponse\020\330"
  "F\0220\n+k_EMsgClientToGCMonsterHunterClaimS"
  "etReward\020\331F\0228\n3k_EMsgClientToGCMonsterHu"
  "nterClaimSetRewardResponse\020\332F\022$\n\037k_EMsgC"
  "lientToGCGetEventRanking\020\223G\022,\n\'k_EMsgCli"
  "entToGCGetEventRankingResponse\020\224G\022#\n\036k_E"
  "MsgClientToGCGetEventCoupon\020\225G\022+\n&k_EMsg"
  "ClientToGCGetEventCouponResponse\020\226G"
  ;
static ::_pbi::once_flag descriptor_table_dota_5fgcmessages_5fmsgid_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_dota_5fgcmessages_5fmsgid_2eproto = {
    false, false, 43555, descriptor_table_protodef_dota_5fgcmessages_5fmsgid_2eproto,
    "dota_gcmessages_msgid.proto",
    &descriptor_table_dota_5fgcmessages_5fmsgid_2eproto_once, nullptr, 0, 0,
    schemas, file_default_instances, TableStruct_dota_5fgcmessages_5fmsgid_2eproto::offsets,
    nullptr, file_level_enum_descriptors_dota_5fgcmessages_5fmsgid_2eproto,
    file_level_service_descriptors_dota_5fgcmessages_5fmsgid_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_dota_5fgcmessages_5fmsgid_2eproto_getter() {
  return &descriptor_table_dota_5fgcmessages_5fmsgid_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_dota_5fgcmessages_5fmsgid_2eproto(&descriptor_table_dota_5fgcmessages_5fmsgid_2eproto);
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EDOTAGCMsg_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_dota_5fgcmessages_5fmsgid_2eproto);
  return file_level_enum_descriptors_dota_5fgcmessages_5fmsgid_2eproto[0];
}
bool EDOTAGCMsg_IsValid(int value) {
  switch (value) {
    case 7000:
    case 7004:
    case 7005:
    case 7009:
    case 7010:
    case 7013:
    case 7014:
    case 7026:
    case 7033:
    case 7034:
    case 7035:
    case 7036:
    case 7038:
    case 7040:
    case 7041:
    case 7042:
    case 7043:
    case 7044:
    case 7046:
    case 7047:
    case 7049:
    case 7055:
    case 7056:
    case 7057:
    case 7060:
    case 7061:
    case 7070:
    case 7071:
    case 7072:
    case 7073:
    case 7074:
    case 7076:
    case 7077:
    case 7078:
    case 7079:
    case 7081:
    case 7082:
    case 7083:
    case 7084:
    case 7085:
    case 7086:
    case 7087:
    case 7088:
    case 7089:
    case 7090:
    case 7091:
    case 7092:
    case 7093:
    case 7094:
    case 7095:
    case 7096:
    case 7097:
    case 7102:
    case 7111:
    case 7112:
    case 7113:
    case 7115:
    case 7116:
    case 7122:
    case 7123:
    case 7124:
    case 7125:
    case 7126:
    case 7127:
    case 7128:
    case 7129:
    case 7130:
    case 7131:
    case 7142:
    case 7144:
    case 7149:
    case 7150:
    case 7151:
    case 7156:
    case 7157:
    case 7166:
    case 7167:
    case 7170:
    case 7186:
    case 7188:
    case 7197:
    case 7198:
    case 7199:
    case 7200:
    case 7201:
    case 7203:
    case 7204:
    case 7206:
    case 7217:
    case 7218:
    case 7219:
    case 7220:
    case 7221:
    case 7234:
    case 7235:
    case 7236:
    case 7237:
    case 7238:
    case 7239:
    case 7240:
    case 7241:
    case 7242:
    case 7255:
    case 7256:
    case 7272:
    case 7273:
    case 7274:
    case 7275:
    case 7283:
    case 7284:
    case 7285:
    case 7286:
    case 7287:
    case 7288:
    case 7308:
    case 7309:
    case 7320:
    case 7322:
    case 7323:
    case 7324:
    case 7325:
    case 7326:
    case 7327:
    case 7328:
    case 7342:
    case 7343:
    case 7346:
    case 7359:
    case 7367:
    case 7372:
    case 7375:
    case 7376:
    case 7377:
    case 7378:
    case 7379:
    case 7380:
    case 7381:
    case 7382:
    case 7384:
    case 7387:
    case 7388:
    case 7397:
    case 7405:
    case 7406:
    case 7407:
    case 7408:
    case 7409:
    case 7410:
    case 7411:
    case 7412:
    case 7413:
    case 7414:
    case 7415:
    case 7416:
    case 7417:
    case 7418:
    case 7419:
    case 7420:
    case 7426:
    case 7427:
    case 7428:
    case 7429:
    case 7434:
    case 7435:
    case 7450:
    case 7451:
    case 7453:
    case 7454:
    case 7455:
    case 7456:
    case 7457:
    case 7458:
    case 7459:
    case 7464:
    case 7465:
    case 7466:
    case 7467:
    case 7468:
    case 7469:
    case 7470:
    case 7471:
    case 7472:
    case 7478:
    case 7484:
    case 7485:
    case 7488:
    case 7492:
    case 7493:
    case 7494:
    case 7495:
    case 7496:
    case 7497:
    case 7501:
    case 7502:
    case 7503:
    case 7504:
    case 7505:
    case 7518:
    case 7519:
    case 7521:
    case 7522:
    case 7523:
    case 7524:
    case 7525:
    case 7526:
    case 7527:
    case 7528:
    case 7529:
    case 7530:
    case 7531:
    case 7532:
    case 7533:
    case 7534:
    case 7535:
    case 7536:
    case 7537:
    case 7538:
    case 7539:
    case 7540:
    case 7541:
    case 7542:
    case 7543:
    case 7544:
    case 7545:
    case 7546:
    case 7547:
    case 7548:
    case 7549:
    case 7550:
    case 7551:
    case 7552:
    case 7553:
    case 7554:
    case 7561:
    case 7562:
    case 7569:
    case 7572:
    case 7573:
    case 7574:
    case 7576:
    case 7577:
    case 7579:
    case 7580:
    case 7581:
    case 7583:
    case 7584:
    case 7585:
    case 7586:
    case 7587:
    case 7588:
    case 7589:
    case 7592:
    case 7594:
    case 7603:
    case 7606:
    case 7607:
    case 7608:
    case 7611:
    case 7612:
    case 7623:
    case 7624:
    case 7625:
    case 7626:
    case 7627:
    case 7628:
    case 7630:
    case 7631:
    case 7632:
    case 7633:
    case 7634:
    case 7645:
    case 7646:
    case 7647:
    case 7650:
    case 7651:
    case 7652:
    case 7653:
    case 7654:
    case 7655:
    case 7656:
    case 7657:
    case 7658:
    case 7659:
    case 7660:
    case 7661:
    case 7662:
    case 7663:
    case 7664:
    case 7665:
    case 7666:
    case 7667:
    case 7668:
    case 7669:
    case 7670:
    case 7671:
    case 7672:
    case 7673:
    case 7674:
    case 7675:
    case 7676:
    case 7677:
    case 7678:
    case 7679:
    case 7680:
    case 7681:
    case 7682:
    case 7683:
    case 7684:
    case 7685:
    case 7686:
    case 7687:
    case 7688:
    case 7689:
    case 7690:
    case 7691:
    case 8004:
    case 8006:
    case 8007:
    case 8008:
    case 8009:
    case 8010:
    case 8011:
    case 8012:
    case 8013:
    case 8016:
    case 8017:
    case 8018:
    case 8019:
    case 8020:
    case 8021:
    case 8024:
    case 8029:
    case 8030:
    case 8031:
    case 8032:
    case 8033:
    case 8034:
    case 8035:
    case 8036:
    case 8037:
    case 8040:
    case 8041:
    case 8042:
    case 8045:
    case 8046:
    case 8047:
    case 8048:
    case 8049:
    case 8050:
    case 8051:
    case 8052:
    case 8053:
    case 8054:
    case 8055:
    case 8057:
    case 8061:
    case 8062:
    case 8063:
    case 8064:
    case 8067:
    case 8068:
    case 8071:
    case 8072:
    case 8073:
    case 8074:
    case 8075:
    case 8076:
    case 8077:
    case 8078:
    case 8079:
    case 8080:
    case 8081:
    case 8082:
    case 8083:
    case 8084:
    case 8088:
    case 8089:
    case 8090:
    case 8091:
    case 8095:
    case 8096:
    case 8099:
    case 8100:
    case 8103:
    case 8104:
    case 8108:
    case 8110:
    case 8111:
    case 8112:
    case 8113:
    case 8114:
    case 8115:
    case 8116:
    case 8117:
    case 8118:
    case 8119:
    case 8120:
    case 8121:
    case 8124:
    case 8125:
    case 8126:
    case 8127:
    case 8128:
    case 8129:
    case 8130:
    case 8131:
    case 8132:
    case 8135:
    case 8136:
    case 8137:
    case 8140:
    case 8141:
    case 8144:
    case 8145:
    case 8150:
    case 8152:
    case 8153:
    case 8154:
    case 8155:
    case 8157:
    case 8158:
    case 8159:
    case 8160:
    case 8161:
    case 8162:
    case 8163:
    case 8166:
    case 8167:
    case 8168:
    case 8169:
    case 8170:
    case 8171:
    case 8172:
    case 8173:
    case 8174:
    case 8175:
    case 8176:
    case 8177:
    case 8178:
    case 8179:
    case 8180:
    case 8181:
    case 8183:
    case 8186:
    case 8187:
    case 8188:
    case 8189:
    case 8190:
    case 8191:
    case 8192:
    case 8193:
    case 8194:
    case 8195:
    case 8196:
    case 8197:
    case 8198:
    case 8199:
    case 8200:
    case 8201:
    case 8202:
    case 8203:
    case 8204:
    case 8205:
    case 8206:
    case 8209:
    case 8210:
    case 8211:
    case 8212:
    case 8213:
    case 8214:
    case 8215:
    case 8216:
    case 8217:
    case 8218:
    case 8219:
    case 8220:
    case 8221:
    case 8222:
    case 8223:
    case 8224:
    case 8225:
    case 8229:
    case 8230:
    case 8231:
    case 8232:
    case 8238:
    case 8239:
    case 8240:
    case 8241:
    case 8242:
    case 8243:
    case 8244:
    case 8245:
    case 8246:
    case 8247:
    case 8248:
    case 8249:
    case 8250:
    case 8251:
    case 8255:
    case 8258:
    case 8259:
    case 8260:
    case 8261:
    case 8262:
    case 8263:
    case 8264:
    case 8265:
    case 8266:
    case 8267:
    case 8268:
    case 8269:
    case 8270:
    case 8271:
    case 8274:
    case 8275:
    case 8276:
    case 8277:
    case 8278:
    case 8279:
    case 8280:
    case 8281:
    case 8282:
    case 8283:
    case 8284:
    case 8285:
    case 8288:
    case 8289:
    case 8290:
    case 8291:
    case 8292:
    case 8293:
    case 8294:
    case 8295:
    case 8296:
    case 8297:
    case 8298:
    case 8299:
    case 8300:
    case 8301:
    case 8303:
    case 8304:
    case 8305:
    case 8306:
    case 8308:
    case 8309:
    case 8310:
    case 8311:
    case 8312:
    case 8313:
    case 8314:
    case 8315:
    case 8316:
    case 8317:
    case 8318:
    case 8319:
    case 8320:
    case 8321:
    case 8322:
    case 8323:
    case 8324:
    case 8325:
    case 8326:
    case 8327:
    case 8328:
    case 8329:
    case 8330:
    case 8331:
    case 8332:
    case 8333:
    case 8334:
    case 8335:
    case 8336:
    case 8337:
    case 8338:
    case 8341:
    case 8342:
    case 8343:
    case 8345:
    case 8346:
    case 8347:
    case 8348:
    case 8349:
    case 8350:
    case 8360:
    case 8361:
    case 8362:
    case 8363:
    case 8364:
    case 8365:
    case 8366:
    case 8367:
    case 8368:
    case 8635:
    case 8636:
    case 8637:
    case 8638:
    case 8639:
    case 8640:
    case 8641:
    case 8642:
    case 8643:
    case 8644:
    case 8645:
    case 8646:
    case 8647:
    case 8648:
    case 8649:
    case 8650:
    case 8651:
    case 8652:
    case 8653:
    case 8654:
    case 8655:
    case 8656:
    case 8657:
    case 8658:
    case 8659:
    case 8660:
    case 8661:
    case 8662:
    case 8663:
    case 8664:
    case 8665:
    case 8666:
    case 8667:
    case 8668:
    case 8669:
    case 8670:
    case 8671:
    case 8672:
    case 8673:
    case 8674:
    case 8675:
    case 8676:
    case 8677:
    case 8678:
    case 8681:
    case 8682:
    case 8683:
    case 8684:
    case 8685:
    case 8686:
    case 8687:
    case 8688:
    case 8689:
    case 8690:
    case 8691:
    case 8692:
    case 8693:
    case 8694:
    case 8695:
    case 8696:
    case 8698:
    case 8699:
    case 8700:
    case 8701:
    case 8702:
    case 8703:
    case 8704:
    case 8705:
    case 8708:
    case 8711:
    case 8712:
    case 8713:
    case 8714:
    case 8715:
    case 8716:
    case 8717:
    case 8718:
    case 8720:
    case 8721:
    case 8722:
    case 8725:
    case 8726:
    case 8727:
    case 8728:
    case 8729:
    case 8730:
    case 8731:
    case 8733:
    case 8734:
    case 8735:
    case 8736:
    case 8737:
    case 8738:
    case 8739:
    case 8740:
    case 8741:
    case 8742:
    case 8743:
    case 8744:
    case 8745:
    case 8746:
    case 8747:
    case 8748:
    case 8749:
    case 8750:
    case 8751:
    case 8752:
    case 8753:
    case 8754:
    case 8755:
    case 8756:
    case 8757:
    case 8758:
    case 8759:
    case 8760:
    case 8761:
    case 8764:
    case 8765:
    case 8766:
    case 8767:
    case 8768:
    case 8769:
    case 8770:
    case 8771:
    case 8772:
    case 8773:
    case 8774:
    case 8775:
    case 8776:
    case 8777:
    case 8778:
    case 8779:
    case 8780:
    case 8781:
    case 8782:
    case 8783:
    case 8784:
    case 8785:
    case 8786:
    case 8787:
    case 8788:
    case 8789:
    case 8790:
    case 8791:
    case 8792:
    case 8793:
    case 8794:
    case 8795:
    case 8796:
    case 8797:
    case 8798:
    case 8799:
    case 8800:
    case 8801:
    case 8802:
    case 8803:
    case 8804:
    case 8805:
    case 8806:
    case 8807:
    case 8808:
    case 8809:
    case 8810:
    case 8811:
    case 8812:
    case 8813:
    case 8814:
    case 8815:
    case 8816:
    case 8817:
    case 8818:
    case 8819:
    case 8820:
    case 8821:
    case 8822:
    case 8823:
    case 8824:
    case 8825:
    case 8826:
    case 8827:
    case 8828:
    case 8829:
    case 8830:
    case 8831:
    case 8832:
    case 8833:
    case 8834:
    case 8835:
    case 8836:
    case 8837:
    case 8838:
    case 8840:
    case 8841:
    case 8842:
    case 8843:
    case 8844:
    case 8845:
    case 8846:
    case 8847:
    case 8848:
    case 8849:
    case 8850:
    case 8851:
    case 8852:
    case 8853:
    case 8854:
    case 8855:
    case 8856:
    case 8857:
    case 8858:
    case 8859:
    case 8860:
    case 8861:
    case 8862:
    case 8863:
    case 8864:
    case 8865:
    case 8866:
    case 8867:
    case 8868:
    case 8869:
    case 8870:
    case 8871:
    case 8872:
    case 8873:
    case 8874:
    case 8877:
    case 8878:
    case 8879:
    case 8880:
    case 8881:
    case 8882:
    case 8883:
    case 8884:
    case 8886:
    case 8887:
    case 8888:
    case 8889:
    case 8890:
    case 8891:
    case 8892:
    case 8893:
    case 8894:
    case 8895:
    case 8896:
    case 8897:
    case 8898:
    case 8899:
    case 8900:
    case 8901:
    case 8902:
    case 8903:
    case 8904:
    case 8905:
    case 8906:
    case 8907:
    case 8908:
    case 8909:
    case 8910:
    case 8911:
    case 8912:
    case 8913:
    case 8914:
    case 8915:
    case 8916:
    case 8917:
    case 8918:
    case 8919:
    case 8920:
    case 8921:
    case 8922:
    case 8923:
    case 8924:
    case 8925:
    case 8926:
    case 8927:
    case 8928:
    case 8929:
    case 8930:
    case 8931:
    case 8932:
    case 8933:
    case 8934:
    case 8935:
    case 8936:
    case 8937:
    case 8939:
    case 8940:
    case 8941:
    case 8942:
    case 8943:
    case 8944:
    case 8945:
    case 8946:
    case 8947:
    case 8948:
    case 8949:
    case 8950:
    case 8951:
    case 8952:
    case 8953:
    case 8954:
    case 8955:
    case 8956:
    case 8957:
    case 8958:
    case 8959:
    case 8960:
    case 8961:
    case 8962:
    case 8963:
    case 8964:
    case 8965:
    case 8966:
    case 8967:
    case 8969:
    case 8970:
    case 8971:
    case 8972:
    case 8973:
    case 8974:
    case 8975:
    case 8976:
    case 8977:
    case 8978:
    case 8979:
    case 8980:
    case 8981:
    case 8982:
    case 8983:
    case 8984:
    case 8985:
    case 8986:
    case 8987:
    case 8988:
    case 8989:
    case 8990:
    case 8991:
    case 8992:
    case 8993:
    case 8994:
    case 8995:
    case 8996:
    case 8997:
    case 8999:
    case 9000:
    case 9001:
    case 9002:
    case 9003:
    case 9004:
    case 9005:
    case 9006:
    case 9007:
    case 9008:
    case 9009:
    case 9010:
    case 9011:
    case 9012:
    case 9013:
    case 9014:
    case 9015:
    case 9016:
    case 9017:
    case 9018:
    case 9019:
    case 9020:
    case 9021:
    case 9022:
    case 9023:
    case 9024:
    case 9025:
    case 9026:
    case 9027:
    case 9028:
    case 9029:
    case 9030:
    case 9031:
    case 9032:
    case 9033:
    case 9034:
    case 9035:
    case 9036:
    case 9037:
    case 9038:
    case 9039:
    case 9040:
    case 9041:
    case 9042:
    case 9043:
    case 9044:
    case 9045:
    case 9046:
    case 9047:
    case 9048:
    case 9049:
    case 9050:
    case 9107:
    case 9108:
    case 9109:
    case 9110:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
