// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dota_gcmessages_common_survivors.proto

#include "dota_gcmessages_common_survivors.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR CMsgSurvivorsUserData_AttributeLevelsEntry::CMsgSurvivorsUserData_AttributeLevelsEntry(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.key_)*/0
  , /*decltype(_impl_.value_)*/0u} {}
struct CMsgSurvivorsUserData_AttributeLevelsEntryDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CMsgSurvivorsUserData_AttributeLevelsEntryDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CMsgSurvivorsUserData_AttributeLevelsEntryDefaultTypeInternal() {}
  union {
    CMsgSurvivorsUserData_AttributeLevelsEntry _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CMsgSurvivorsUserData_AttributeLevelsEntryDefaultTypeInternal _CMsgSurvivorsUserData_AttributeLevelsEntry_default_instance_;
PROTOBUF_CONSTEXPR CMsgSurvivorsUserData::CMsgSurvivorsUserData(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.attribute_levels_)*/{}
  , /*decltype(_impl_.unlocked_difficulty_)*/0u} {}
struct CMsgSurvivorsUserDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CMsgSurvivorsUserDataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CMsgSurvivorsUserDataDefaultTypeInternal() {}
  union {
    CMsgSurvivorsUserData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CMsgSurvivorsUserDataDefaultTypeInternal _CMsgSurvivorsUserData_default_instance_;
PROTOBUF_CONSTEXPR CMsgClientToGCSurvivorsPowerUpTelemetryData::CMsgClientToGCSurvivorsPowerUpTelemetryData(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.powerup_id_)*/0u
  , /*decltype(_impl_.level_)*/0u
  , /*decltype(_impl_.time_received_)*/0u
  , /*decltype(_impl_.time_held_)*/0u
  , /*decltype(_impl_.total_damage_)*/uint64_t{0u}
  , /*decltype(_impl_.dps_)*/0u
  , /*decltype(_impl_.has_scepter_)*/0u} {}
struct CMsgClientToGCSurvivorsPowerUpTelemetryDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CMsgClientToGCSurvivorsPowerUpTelemetryDataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CMsgClientToGCSurvivorsPowerUpTelemetryDataDefaultTypeInternal() {}
  union {
    CMsgClientToGCSurvivorsPowerUpTelemetryData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CMsgClientToGCSurvivorsPowerUpTelemetryDataDefaultTypeInternal _CMsgClientToGCSurvivorsPowerUpTelemetryData_default_instance_;
PROTOBUF_CONSTEXPR CMsgClientToGCSurvivorsGameTelemetryData::CMsgClientToGCSurvivorsGameTelemetryData(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.powerups_)*/{}
  , /*decltype(_impl_.time_survived_)*/0u
  , /*decltype(_impl_.player_level_)*/0u
  , /*decltype(_impl_.game_result_)*/0u
  , /*decltype(_impl_.gold_earned_)*/0u
  , /*decltype(_impl_.difficulty_)*/0u
  , /*decltype(_impl_.metaprogression_level_)*/0u} {}
struct CMsgClientToGCSurvivorsGameTelemetryDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CMsgClientToGCSurvivorsGameTelemetryDataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CMsgClientToGCSurvivorsGameTelemetryDataDefaultTypeInternal() {}
  union {
    CMsgClientToGCSurvivorsGameTelemetryData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CMsgClientToGCSurvivorsGameTelemetryDataDefaultTypeInternal _CMsgClientToGCSurvivorsGameTelemetryData_default_instance_;
PROTOBUF_CONSTEXPR CMsgClientToGCSurvivorsGameTelemetryDataResponse::CMsgClientToGCSurvivorsGameTelemetryDataResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.response_)*/0} {}
struct CMsgClientToGCSurvivorsGameTelemetryDataResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CMsgClientToGCSurvivorsGameTelemetryDataResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CMsgClientToGCSurvivorsGameTelemetryDataResponseDefaultTypeInternal() {}
  union {
    CMsgClientToGCSurvivorsGameTelemetryDataResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CMsgClientToGCSurvivorsGameTelemetryDataResponseDefaultTypeInternal _CMsgClientToGCSurvivorsGameTelemetryDataResponse_default_instance_;
static ::_pb::Metadata file_level_metadata_dota_5fgcmessages_5fcommon_5fsurvivors_2eproto[5];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_dota_5fgcmessages_5fcommon_5fsurvivors_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_dota_5fgcmessages_5fcommon_5fsurvivors_2eproto = nullptr;

const uint32_t TableStruct_dota_5fgcmessages_5fcommon_5fsurvivors_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::CMsgSurvivorsUserData_AttributeLevelsEntry, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::CMsgSurvivorsUserData_AttributeLevelsEntry, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::CMsgSurvivorsUserData_AttributeLevelsEntry, _impl_.key_),
  PROTOBUF_FIELD_OFFSET(::CMsgSurvivorsUserData_AttributeLevelsEntry, _impl_.value_),
  0,
  1,
  PROTOBUF_FIELD_OFFSET(::CMsgSurvivorsUserData, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::CMsgSurvivorsUserData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::CMsgSurvivorsUserData, _impl_.attribute_levels_),
  PROTOBUF_FIELD_OFFSET(::CMsgSurvivorsUserData, _impl_.unlocked_difficulty_),
  ~0u,
  0,
  PROTOBUF_FIELD_OFFSET(::CMsgClientToGCSurvivorsPowerUpTelemetryData, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::CMsgClientToGCSurvivorsPowerUpTelemetryData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::CMsgClientToGCSurvivorsPowerUpTelemetryData, _impl_.powerup_id_),
  PROTOBUF_FIELD_OFFSET(::CMsgClientToGCSurvivorsPowerUpTelemetryData, _impl_.level_),
  PROTOBUF_FIELD_OFFSET(::CMsgClientToGCSurvivorsPowerUpTelemetryData, _impl_.time_received_),
  PROTOBUF_FIELD_OFFSET(::CMsgClientToGCSurvivorsPowerUpTelemetryData, _impl_.time_held_),
  PROTOBUF_FIELD_OFFSET(::CMsgClientToGCSurvivorsPowerUpTelemetryData, _impl_.total_damage_),
  PROTOBUF_FIELD_OFFSET(::CMsgClientToGCSurvivorsPowerUpTelemetryData, _impl_.dps_),
  PROTOBUF_FIELD_OFFSET(::CMsgClientToGCSurvivorsPowerUpTelemetryData, _impl_.has_scepter_),
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  PROTOBUF_FIELD_OFFSET(::CMsgClientToGCSurvivorsGameTelemetryData, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::CMsgClientToGCSurvivorsGameTelemetryData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::CMsgClientToGCSurvivorsGameTelemetryData, _impl_.time_survived_),
  PROTOBUF_FIELD_OFFSET(::CMsgClientToGCSurvivorsGameTelemetryData, _impl_.player_level_),
  PROTOBUF_FIELD_OFFSET(::CMsgClientToGCSurvivorsGameTelemetryData, _impl_.game_result_),
  PROTOBUF_FIELD_OFFSET(::CMsgClientToGCSurvivorsGameTelemetryData, _impl_.gold_earned_),
  PROTOBUF_FIELD_OFFSET(::CMsgClientToGCSurvivorsGameTelemetryData, _impl_.powerups_),
  PROTOBUF_FIELD_OFFSET(::CMsgClientToGCSurvivorsGameTelemetryData, _impl_.difficulty_),
  PROTOBUF_FIELD_OFFSET(::CMsgClientToGCSurvivorsGameTelemetryData, _impl_.metaprogression_level_),
  0,
  1,
  2,
  3,
  ~0u,
  4,
  5,
  PROTOBUF_FIELD_OFFSET(::CMsgClientToGCSurvivorsGameTelemetryDataResponse, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::CMsgClientToGCSurvivorsGameTelemetryDataResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::CMsgClientToGCSurvivorsGameTelemetryDataResponse, _impl_.response_),
  0,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, -1, sizeof(::CMsgSurvivorsUserData_AttributeLevelsEntry)},
  { 10, 18, -1, sizeof(::CMsgSurvivorsUserData)},
  { 20, 33, -1, sizeof(::CMsgClientToGCSurvivorsPowerUpTelemetryData)},
  { 40, 53, -1, sizeof(::CMsgClientToGCSurvivorsGameTelemetryData)},
  { 60, 67, -1, sizeof(::CMsgClientToGCSurvivorsGameTelemetryDataResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_CMsgSurvivorsUserData_AttributeLevelsEntry_default_instance_._instance,
  &::_CMsgSurvivorsUserData_default_instance_._instance,
  &::_CMsgClientToGCSurvivorsPowerUpTelemetryData_default_instance_._instance,
  &::_CMsgClientToGCSurvivorsGameTelemetryData_default_instance_._instance,
  &::_CMsgClientToGCSurvivorsGameTelemetryDataResponse_default_instance_._instance,
};

const char descriptor_table_protodef_dota_5fgcmessages_5fcommon_5fsurvivors_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n&dota_gcmessages_common_survivors.proto"
  "\032\023steammessages.proto\032\027dota_shared_enums"
  ".proto\032\034dota_gcmessages_common.proto\032\026gc"
  "sdk_gcmessages.proto\"\257\001\n\025CMsgSurvivorsUs"
  "erData\022E\n\020attribute_levels\030\001 \003(\0132+.CMsgS"
  "urvivorsUserData.AttributeLevelsEntry\022\033\n"
  "\023unlocked_difficulty\030\002 \001(\r\0322\n\024AttributeL"
  "evelsEntry\022\013\n\003key\030\001 \001(\005\022\r\n\005value\030\002 \001(\r\"\262"
  "\001\n+CMsgClientToGCSurvivorsPowerUpTelemet"
  "ryData\022\022\n\npowerup_id\030\001 \001(\r\022\r\n\005level\030\002 \001("
  "\r\022\025\n\rtime_received\030\003 \001(\r\022\021\n\ttime_held\030\004 "
  "\001(\r\022\024\n\014total_damage\030\005 \001(\004\022\013\n\003dps\030\006 \001(\r\022\023"
  "\n\013has_scepter\030\007 \001(\r\"\364\001\n(CMsgClientToGCSu"
  "rvivorsGameTelemetryData\022\025\n\rtime_survive"
  "d\030\001 \001(\r\022\024\n\014player_level\030\002 \001(\r\022\023\n\013game_re"
  "sult\030\003 \001(\r\022\023\n\013gold_earned\030\004 \001(\r\022>\n\010power"
  "ups\030\005 \003(\0132,.CMsgClientToGCSurvivorsPower"
  "UpTelemetryData\022\022\n\ndifficulty\030\006 \001(\r\022\035\n\025m"
  "etaprogression_level\030\007 \001(\r\"\237\002\n0CMsgClien"
  "tToGCSurvivorsGameTelemetryDataResponse\022"
  "_\n\010response\030\001 \001(\0162;.CMsgClientToGCSurviv"
  "orsGameTelemetryDataResponse.EResponse:\020"
  "k_eInternalError\"\211\001\n\tEResponse\022\024\n\020k_eInt"
  "ernalError\020\000\022\016\n\nk_eSuccess\020\001\022\016\n\nk_eTooBu"
  "sy\020\002\022\017\n\013k_eDisabled\020\003\022\016\n\nk_eTimeout\020\004\022\021\n"
  "\rk_eNotAllowed\020\005\022\022\n\016k_eInvalidItem\020\006"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_dota_5fgcmessages_5fcommon_5fsurvivors_2eproto_deps[4] = {
  &::descriptor_table_dota_5fgcmessages_5fcommon_2eproto,
  &::descriptor_table_dota_5fshared_5fenums_2eproto,
  &::descriptor_table_gcsdk_5fgcmessages_2eproto,
  &::descriptor_table_steammessages_2eproto,
};
static ::_pbi::once_flag descriptor_table_dota_5fgcmessages_5fcommon_5fsurvivors_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_dota_5fgcmessages_5fcommon_5fsurvivors_2eproto = {
    false, false, 1036, descriptor_table_protodef_dota_5fgcmessages_5fcommon_5fsurvivors_2eproto,
    "dota_gcmessages_common_survivors.proto",
    &descriptor_table_dota_5fgcmessages_5fcommon_5fsurvivors_2eproto_once, descriptor_table_dota_5fgcmessages_5fcommon_5fsurvivors_2eproto_deps, 4, 5,
    schemas, file_default_instances, TableStruct_dota_5fgcmessages_5fcommon_5fsurvivors_2eproto::offsets,
    file_level_metadata_dota_5fgcmessages_5fcommon_5fsurvivors_2eproto, file_level_enum_descriptors_dota_5fgcmessages_5fcommon_5fsurvivors_2eproto,
    file_level_service_descriptors_dota_5fgcmessages_5fcommon_5fsurvivors_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_dota_5fgcmessages_5fcommon_5fsurvivors_2eproto_getter() {
  return &descriptor_table_dota_5fgcmessages_5fcommon_5fsurvivors_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_dota_5fgcmessages_5fcommon_5fsurvivors_2eproto(&descriptor_table_dota_5fgcmessages_5fcommon_5fsurvivors_2eproto);
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_dota_5fgcmessages_5fcommon_5fsurvivors_2eproto);
  return file_level_enum_descriptors_dota_5fgcmessages_5fcommon_5fsurvivors_2eproto[0];
}
bool CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse CMsgClientToGCSurvivorsGameTelemetryDataResponse::k_eInternalError;
constexpr CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse CMsgClientToGCSurvivorsGameTelemetryDataResponse::k_eSuccess;
constexpr CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse CMsgClientToGCSurvivorsGameTelemetryDataResponse::k_eTooBusy;
constexpr CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse CMsgClientToGCSurvivorsGameTelemetryDataResponse::k_eDisabled;
constexpr CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse CMsgClientToGCSurvivorsGameTelemetryDataResponse::k_eTimeout;
constexpr CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse CMsgClientToGCSurvivorsGameTelemetryDataResponse::k_eNotAllowed;
constexpr CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse CMsgClientToGCSurvivorsGameTelemetryDataResponse::k_eInvalidItem;
constexpr CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse CMsgClientToGCSurvivorsGameTelemetryDataResponse::EResponse_MIN;
constexpr CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse CMsgClientToGCSurvivorsGameTelemetryDataResponse::EResponse_MAX;
constexpr int CMsgClientToGCSurvivorsGameTelemetryDataResponse::EResponse_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

// ===================================================================

class CMsgSurvivorsUserData_AttributeLevelsEntry::_Internal {
 public:
  using HasBits = decltype(std::declval<CMsgSurvivorsUserData_AttributeLevelsEntry>()._impl_._has_bits_);
  static void set_has_key(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_value(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

CMsgSurvivorsUserData_AttributeLevelsEntry::CMsgSurvivorsUserData_AttributeLevelsEntry(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:CMsgSurvivorsUserData.AttributeLevelsEntry)
}
CMsgSurvivorsUserData_AttributeLevelsEntry::CMsgSurvivorsUserData_AttributeLevelsEntry(const CMsgSurvivorsUserData_AttributeLevelsEntry& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CMsgSurvivorsUserData_AttributeLevelsEntry* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.key_){}
    , decltype(_impl_.value_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.key_, &from._impl_.key_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.value_) -
    reinterpret_cast<char*>(&_impl_.key_)) + sizeof(_impl_.value_));
  // @@protoc_insertion_point(copy_constructor:CMsgSurvivorsUserData.AttributeLevelsEntry)
}

inline void CMsgSurvivorsUserData_AttributeLevelsEntry::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.key_){0}
    , decltype(_impl_.value_){0u}
  };
}

CMsgSurvivorsUserData_AttributeLevelsEntry::~CMsgSurvivorsUserData_AttributeLevelsEntry() {
  // @@protoc_insertion_point(destructor:CMsgSurvivorsUserData.AttributeLevelsEntry)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CMsgSurvivorsUserData_AttributeLevelsEntry::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void CMsgSurvivorsUserData_AttributeLevelsEntry::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CMsgSurvivorsUserData_AttributeLevelsEntry::Clear() {
// @@protoc_insertion_point(message_clear_start:CMsgSurvivorsUserData.AttributeLevelsEntry)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    ::memset(&_impl_.key_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.value_) -
        reinterpret_cast<char*>(&_impl_.key_)) + sizeof(_impl_.value_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CMsgSurvivorsUserData_AttributeLevelsEntry::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional int32 key = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _Internal::set_has_key(&has_bits);
          _impl_.key_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional uint32 value = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _Internal::set_has_value(&has_bits);
          _impl_.value_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CMsgSurvivorsUserData_AttributeLevelsEntry::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CMsgSurvivorsUserData.AttributeLevelsEntry)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional int32 key = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_key(), target);
  }

  // optional uint32 value = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_value(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CMsgSurvivorsUserData.AttributeLevelsEntry)
  return target;
}

size_t CMsgSurvivorsUserData_AttributeLevelsEntry::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CMsgSurvivorsUserData.AttributeLevelsEntry)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional int32 key = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_key());
    }

    // optional uint32 value = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_value());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CMsgSurvivorsUserData_AttributeLevelsEntry::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CMsgSurvivorsUserData_AttributeLevelsEntry::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CMsgSurvivorsUserData_AttributeLevelsEntry::GetClassData() const { return &_class_data_; }


void CMsgSurvivorsUserData_AttributeLevelsEntry::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CMsgSurvivorsUserData_AttributeLevelsEntry*>(&to_msg);
  auto& from = static_cast<const CMsgSurvivorsUserData_AttributeLevelsEntry&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:CMsgSurvivorsUserData.AttributeLevelsEntry)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.key_ = from._impl_.key_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.value_ = from._impl_.value_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CMsgSurvivorsUserData_AttributeLevelsEntry::CopyFrom(const CMsgSurvivorsUserData_AttributeLevelsEntry& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CMsgSurvivorsUserData.AttributeLevelsEntry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CMsgSurvivorsUserData_AttributeLevelsEntry::IsInitialized() const {
  return true;
}

void CMsgSurvivorsUserData_AttributeLevelsEntry::InternalSwap(CMsgSurvivorsUserData_AttributeLevelsEntry* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CMsgSurvivorsUserData_AttributeLevelsEntry, _impl_.value_)
      + sizeof(CMsgSurvivorsUserData_AttributeLevelsEntry::_impl_.value_)
      - PROTOBUF_FIELD_OFFSET(CMsgSurvivorsUserData_AttributeLevelsEntry, _impl_.key_)>(
          reinterpret_cast<char*>(&_impl_.key_),
          reinterpret_cast<char*>(&other->_impl_.key_));
}

::PROTOBUF_NAMESPACE_ID::Metadata CMsgSurvivorsUserData_AttributeLevelsEntry::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_dota_5fgcmessages_5fcommon_5fsurvivors_2eproto_getter, &descriptor_table_dota_5fgcmessages_5fcommon_5fsurvivors_2eproto_once,
      file_level_metadata_dota_5fgcmessages_5fcommon_5fsurvivors_2eproto[0]);
}

// ===================================================================

class CMsgSurvivorsUserData::_Internal {
 public:
  using HasBits = decltype(std::declval<CMsgSurvivorsUserData>()._impl_._has_bits_);
  static void set_has_unlocked_difficulty(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

CMsgSurvivorsUserData::CMsgSurvivorsUserData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:CMsgSurvivorsUserData)
}
CMsgSurvivorsUserData::CMsgSurvivorsUserData(const CMsgSurvivorsUserData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CMsgSurvivorsUserData* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.attribute_levels_){from._impl_.attribute_levels_}
    , decltype(_impl_.unlocked_difficulty_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.unlocked_difficulty_ = from._impl_.unlocked_difficulty_;
  // @@protoc_insertion_point(copy_constructor:CMsgSurvivorsUserData)
}

inline void CMsgSurvivorsUserData::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.attribute_levels_){arena}
    , decltype(_impl_.unlocked_difficulty_){0u}
  };
}

CMsgSurvivorsUserData::~CMsgSurvivorsUserData() {
  // @@protoc_insertion_point(destructor:CMsgSurvivorsUserData)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CMsgSurvivorsUserData::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.attribute_levels_.~RepeatedPtrField();
}

void CMsgSurvivorsUserData::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CMsgSurvivorsUserData::Clear() {
// @@protoc_insertion_point(message_clear_start:CMsgSurvivorsUserData)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.attribute_levels_.Clear();
  _impl_.unlocked_difficulty_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CMsgSurvivorsUserData::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .CMsgSurvivorsUserData.AttributeLevelsEntry attribute_levels = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_attribute_levels(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      // optional uint32 unlocked_difficulty = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _Internal::set_has_unlocked_difficulty(&has_bits);
          _impl_.unlocked_difficulty_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CMsgSurvivorsUserData::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CMsgSurvivorsUserData)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .CMsgSurvivorsUserData.AttributeLevelsEntry attribute_levels = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_attribute_levels_size()); i < n; i++) {
    const auto& repfield = this->_internal_attribute_levels(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // optional uint32 unlocked_difficulty = 2;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_unlocked_difficulty(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CMsgSurvivorsUserData)
  return target;
}

size_t CMsgSurvivorsUserData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CMsgSurvivorsUserData)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .CMsgSurvivorsUserData.AttributeLevelsEntry attribute_levels = 1;
  total_size += 1UL * this->_internal_attribute_levels_size();
  for (const auto& msg : this->_impl_.attribute_levels_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // optional uint32 unlocked_difficulty = 2;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_unlocked_difficulty());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CMsgSurvivorsUserData::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CMsgSurvivorsUserData::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CMsgSurvivorsUserData::GetClassData() const { return &_class_data_; }


void CMsgSurvivorsUserData::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CMsgSurvivorsUserData*>(&to_msg);
  auto& from = static_cast<const CMsgSurvivorsUserData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:CMsgSurvivorsUserData)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.attribute_levels_.MergeFrom(from._impl_.attribute_levels_);
  if (from._internal_has_unlocked_difficulty()) {
    _this->_internal_set_unlocked_difficulty(from._internal_unlocked_difficulty());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CMsgSurvivorsUserData::CopyFrom(const CMsgSurvivorsUserData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CMsgSurvivorsUserData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CMsgSurvivorsUserData::IsInitialized() const {
  return true;
}

void CMsgSurvivorsUserData::InternalSwap(CMsgSurvivorsUserData* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.attribute_levels_.InternalSwap(&other->_impl_.attribute_levels_);
  swap(_impl_.unlocked_difficulty_, other->_impl_.unlocked_difficulty_);
}

::PROTOBUF_NAMESPACE_ID::Metadata CMsgSurvivorsUserData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_dota_5fgcmessages_5fcommon_5fsurvivors_2eproto_getter, &descriptor_table_dota_5fgcmessages_5fcommon_5fsurvivors_2eproto_once,
      file_level_metadata_dota_5fgcmessages_5fcommon_5fsurvivors_2eproto[1]);
}

// ===================================================================

class CMsgClientToGCSurvivorsPowerUpTelemetryData::_Internal {
 public:
  using HasBits = decltype(std::declval<CMsgClientToGCSurvivorsPowerUpTelemetryData>()._impl_._has_bits_);
  static void set_has_powerup_id(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_level(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_time_received(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_time_held(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_total_damage(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static void set_has_dps(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static void set_has_has_scepter(HasBits* has_bits) {
    (*has_bits)[0] |= 64u;
  }
};

CMsgClientToGCSurvivorsPowerUpTelemetryData::CMsgClientToGCSurvivorsPowerUpTelemetryData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:CMsgClientToGCSurvivorsPowerUpTelemetryData)
}
CMsgClientToGCSurvivorsPowerUpTelemetryData::CMsgClientToGCSurvivorsPowerUpTelemetryData(const CMsgClientToGCSurvivorsPowerUpTelemetryData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CMsgClientToGCSurvivorsPowerUpTelemetryData* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.powerup_id_){}
    , decltype(_impl_.level_){}
    , decltype(_impl_.time_received_){}
    , decltype(_impl_.time_held_){}
    , decltype(_impl_.total_damage_){}
    , decltype(_impl_.dps_){}
    , decltype(_impl_.has_scepter_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.powerup_id_, &from._impl_.powerup_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.has_scepter_) -
    reinterpret_cast<char*>(&_impl_.powerup_id_)) + sizeof(_impl_.has_scepter_));
  // @@protoc_insertion_point(copy_constructor:CMsgClientToGCSurvivorsPowerUpTelemetryData)
}

inline void CMsgClientToGCSurvivorsPowerUpTelemetryData::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.powerup_id_){0u}
    , decltype(_impl_.level_){0u}
    , decltype(_impl_.time_received_){0u}
    , decltype(_impl_.time_held_){0u}
    , decltype(_impl_.total_damage_){uint64_t{0u}}
    , decltype(_impl_.dps_){0u}
    , decltype(_impl_.has_scepter_){0u}
  };
}

CMsgClientToGCSurvivorsPowerUpTelemetryData::~CMsgClientToGCSurvivorsPowerUpTelemetryData() {
  // @@protoc_insertion_point(destructor:CMsgClientToGCSurvivorsPowerUpTelemetryData)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CMsgClientToGCSurvivorsPowerUpTelemetryData::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void CMsgClientToGCSurvivorsPowerUpTelemetryData::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CMsgClientToGCSurvivorsPowerUpTelemetryData::Clear() {
// @@protoc_insertion_point(message_clear_start:CMsgClientToGCSurvivorsPowerUpTelemetryData)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000007fu) {
    ::memset(&_impl_.powerup_id_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.has_scepter_) -
        reinterpret_cast<char*>(&_impl_.powerup_id_)) + sizeof(_impl_.has_scepter_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CMsgClientToGCSurvivorsPowerUpTelemetryData::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional uint32 powerup_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _Internal::set_has_powerup_id(&has_bits);
          _impl_.powerup_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional uint32 level = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _Internal::set_has_level(&has_bits);
          _impl_.level_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional uint32 time_received = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _Internal::set_has_time_received(&has_bits);
          _impl_.time_received_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional uint32 time_held = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _Internal::set_has_time_held(&has_bits);
          _impl_.time_held_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional uint64 total_damage = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _Internal::set_has_total_damage(&has_bits);
          _impl_.total_damage_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional uint32 dps = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _Internal::set_has_dps(&has_bits);
          _impl_.dps_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional uint32 has_scepter = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _Internal::set_has_has_scepter(&has_bits);
          _impl_.has_scepter_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CMsgClientToGCSurvivorsPowerUpTelemetryData::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CMsgClientToGCSurvivorsPowerUpTelemetryData)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional uint32 powerup_id = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_powerup_id(), target);
  }

  // optional uint32 level = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_level(), target);
  }

  // optional uint32 time_received = 3;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_time_received(), target);
  }

  // optional uint32 time_held = 4;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(4, this->_internal_time_held(), target);
  }

  // optional uint64 total_damage = 5;
  if (cached_has_bits & 0x00000010u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(5, this->_internal_total_damage(), target);
  }

  // optional uint32 dps = 6;
  if (cached_has_bits & 0x00000020u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(6, this->_internal_dps(), target);
  }

  // optional uint32 has_scepter = 7;
  if (cached_has_bits & 0x00000040u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(7, this->_internal_has_scepter(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CMsgClientToGCSurvivorsPowerUpTelemetryData)
  return target;
}

size_t CMsgClientToGCSurvivorsPowerUpTelemetryData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CMsgClientToGCSurvivorsPowerUpTelemetryData)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000007fu) {
    // optional uint32 powerup_id = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_powerup_id());
    }

    // optional uint32 level = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_level());
    }

    // optional uint32 time_received = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_time_received());
    }

    // optional uint32 time_held = 4;
    if (cached_has_bits & 0x00000008u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_time_held());
    }

    // optional uint64 total_damage = 5;
    if (cached_has_bits & 0x00000010u) {
      total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_total_damage());
    }

    // optional uint32 dps = 6;
    if (cached_has_bits & 0x00000020u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_dps());
    }

    // optional uint32 has_scepter = 7;
    if (cached_has_bits & 0x00000040u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_has_scepter());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CMsgClientToGCSurvivorsPowerUpTelemetryData::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CMsgClientToGCSurvivorsPowerUpTelemetryData::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CMsgClientToGCSurvivorsPowerUpTelemetryData::GetClassData() const { return &_class_data_; }


void CMsgClientToGCSurvivorsPowerUpTelemetryData::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CMsgClientToGCSurvivorsPowerUpTelemetryData*>(&to_msg);
  auto& from = static_cast<const CMsgClientToGCSurvivorsPowerUpTelemetryData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:CMsgClientToGCSurvivorsPowerUpTelemetryData)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000007fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.powerup_id_ = from._impl_.powerup_id_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.level_ = from._impl_.level_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.time_received_ = from._impl_.time_received_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.time_held_ = from._impl_.time_held_;
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_impl_.total_damage_ = from._impl_.total_damage_;
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_impl_.dps_ = from._impl_.dps_;
    }
    if (cached_has_bits & 0x00000040u) {
      _this->_impl_.has_scepter_ = from._impl_.has_scepter_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CMsgClientToGCSurvivorsPowerUpTelemetryData::CopyFrom(const CMsgClientToGCSurvivorsPowerUpTelemetryData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CMsgClientToGCSurvivorsPowerUpTelemetryData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CMsgClientToGCSurvivorsPowerUpTelemetryData::IsInitialized() const {
  return true;
}

void CMsgClientToGCSurvivorsPowerUpTelemetryData::InternalSwap(CMsgClientToGCSurvivorsPowerUpTelemetryData* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CMsgClientToGCSurvivorsPowerUpTelemetryData, _impl_.has_scepter_)
      + sizeof(CMsgClientToGCSurvivorsPowerUpTelemetryData::_impl_.has_scepter_)
      - PROTOBUF_FIELD_OFFSET(CMsgClientToGCSurvivorsPowerUpTelemetryData, _impl_.powerup_id_)>(
          reinterpret_cast<char*>(&_impl_.powerup_id_),
          reinterpret_cast<char*>(&other->_impl_.powerup_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata CMsgClientToGCSurvivorsPowerUpTelemetryData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_dota_5fgcmessages_5fcommon_5fsurvivors_2eproto_getter, &descriptor_table_dota_5fgcmessages_5fcommon_5fsurvivors_2eproto_once,
      file_level_metadata_dota_5fgcmessages_5fcommon_5fsurvivors_2eproto[2]);
}

// ===================================================================

class CMsgClientToGCSurvivorsGameTelemetryData::_Internal {
 public:
  using HasBits = decltype(std::declval<CMsgClientToGCSurvivorsGameTelemetryData>()._impl_._has_bits_);
  static void set_has_time_survived(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_player_level(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_game_result(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_gold_earned(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_difficulty(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static void set_has_metaprogression_level(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
};

CMsgClientToGCSurvivorsGameTelemetryData::CMsgClientToGCSurvivorsGameTelemetryData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:CMsgClientToGCSurvivorsGameTelemetryData)
}
CMsgClientToGCSurvivorsGameTelemetryData::CMsgClientToGCSurvivorsGameTelemetryData(const CMsgClientToGCSurvivorsGameTelemetryData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CMsgClientToGCSurvivorsGameTelemetryData* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.powerups_){from._impl_.powerups_}
    , decltype(_impl_.time_survived_){}
    , decltype(_impl_.player_level_){}
    , decltype(_impl_.game_result_){}
    , decltype(_impl_.gold_earned_){}
    , decltype(_impl_.difficulty_){}
    , decltype(_impl_.metaprogression_level_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.time_survived_, &from._impl_.time_survived_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.metaprogression_level_) -
    reinterpret_cast<char*>(&_impl_.time_survived_)) + sizeof(_impl_.metaprogression_level_));
  // @@protoc_insertion_point(copy_constructor:CMsgClientToGCSurvivorsGameTelemetryData)
}

inline void CMsgClientToGCSurvivorsGameTelemetryData::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.powerups_){arena}
    , decltype(_impl_.time_survived_){0u}
    , decltype(_impl_.player_level_){0u}
    , decltype(_impl_.game_result_){0u}
    , decltype(_impl_.gold_earned_){0u}
    , decltype(_impl_.difficulty_){0u}
    , decltype(_impl_.metaprogression_level_){0u}
  };
}

CMsgClientToGCSurvivorsGameTelemetryData::~CMsgClientToGCSurvivorsGameTelemetryData() {
  // @@protoc_insertion_point(destructor:CMsgClientToGCSurvivorsGameTelemetryData)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CMsgClientToGCSurvivorsGameTelemetryData::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.powerups_.~RepeatedPtrField();
}

void CMsgClientToGCSurvivorsGameTelemetryData::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CMsgClientToGCSurvivorsGameTelemetryData::Clear() {
// @@protoc_insertion_point(message_clear_start:CMsgClientToGCSurvivorsGameTelemetryData)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.powerups_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    ::memset(&_impl_.time_survived_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.metaprogression_level_) -
        reinterpret_cast<char*>(&_impl_.time_survived_)) + sizeof(_impl_.metaprogression_level_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CMsgClientToGCSurvivorsGameTelemetryData::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional uint32 time_survived = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _Internal::set_has_time_survived(&has_bits);
          _impl_.time_survived_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional uint32 player_level = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _Internal::set_has_player_level(&has_bits);
          _impl_.player_level_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional uint32 game_result = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _Internal::set_has_game_result(&has_bits);
          _impl_.game_result_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional uint32 gold_earned = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _Internal::set_has_gold_earned(&has_bits);
          _impl_.gold_earned_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .CMsgClientToGCSurvivorsPowerUpTelemetryData powerups = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_powerups(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<42>(ptr));
        } else
          goto handle_unusual;
        continue;
      // optional uint32 difficulty = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _Internal::set_has_difficulty(&has_bits);
          _impl_.difficulty_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional uint32 metaprogression_level = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _Internal::set_has_metaprogression_level(&has_bits);
          _impl_.metaprogression_level_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CMsgClientToGCSurvivorsGameTelemetryData::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CMsgClientToGCSurvivorsGameTelemetryData)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional uint32 time_survived = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_time_survived(), target);
  }

  // optional uint32 player_level = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_player_level(), target);
  }

  // optional uint32 game_result = 3;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_game_result(), target);
  }

  // optional uint32 gold_earned = 4;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(4, this->_internal_gold_earned(), target);
  }

  // repeated .CMsgClientToGCSurvivorsPowerUpTelemetryData powerups = 5;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_powerups_size()); i < n; i++) {
    const auto& repfield = this->_internal_powerups(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(5, repfield, repfield.GetCachedSize(), target, stream);
  }

  // optional uint32 difficulty = 6;
  if (cached_has_bits & 0x00000010u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(6, this->_internal_difficulty(), target);
  }

  // optional uint32 metaprogression_level = 7;
  if (cached_has_bits & 0x00000020u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(7, this->_internal_metaprogression_level(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CMsgClientToGCSurvivorsGameTelemetryData)
  return target;
}

size_t CMsgClientToGCSurvivorsGameTelemetryData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CMsgClientToGCSurvivorsGameTelemetryData)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .CMsgClientToGCSurvivorsPowerUpTelemetryData powerups = 5;
  total_size += 1UL * this->_internal_powerups_size();
  for (const auto& msg : this->_impl_.powerups_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    // optional uint32 time_survived = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_time_survived());
    }

    // optional uint32 player_level = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_player_level());
    }

    // optional uint32 game_result = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_game_result());
    }

    // optional uint32 gold_earned = 4;
    if (cached_has_bits & 0x00000008u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_gold_earned());
    }

    // optional uint32 difficulty = 6;
    if (cached_has_bits & 0x00000010u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_difficulty());
    }

    // optional uint32 metaprogression_level = 7;
    if (cached_has_bits & 0x00000020u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_metaprogression_level());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CMsgClientToGCSurvivorsGameTelemetryData::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CMsgClientToGCSurvivorsGameTelemetryData::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CMsgClientToGCSurvivorsGameTelemetryData::GetClassData() const { return &_class_data_; }


void CMsgClientToGCSurvivorsGameTelemetryData::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CMsgClientToGCSurvivorsGameTelemetryData*>(&to_msg);
  auto& from = static_cast<const CMsgClientToGCSurvivorsGameTelemetryData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:CMsgClientToGCSurvivorsGameTelemetryData)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.powerups_.MergeFrom(from._impl_.powerups_);
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.time_survived_ = from._impl_.time_survived_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.player_level_ = from._impl_.player_level_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.game_result_ = from._impl_.game_result_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.gold_earned_ = from._impl_.gold_earned_;
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_impl_.difficulty_ = from._impl_.difficulty_;
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_impl_.metaprogression_level_ = from._impl_.metaprogression_level_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CMsgClientToGCSurvivorsGameTelemetryData::CopyFrom(const CMsgClientToGCSurvivorsGameTelemetryData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CMsgClientToGCSurvivorsGameTelemetryData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CMsgClientToGCSurvivorsGameTelemetryData::IsInitialized() const {
  return true;
}

void CMsgClientToGCSurvivorsGameTelemetryData::InternalSwap(CMsgClientToGCSurvivorsGameTelemetryData* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.powerups_.InternalSwap(&other->_impl_.powerups_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CMsgClientToGCSurvivorsGameTelemetryData, _impl_.metaprogression_level_)
      + sizeof(CMsgClientToGCSurvivorsGameTelemetryData::_impl_.metaprogression_level_)
      - PROTOBUF_FIELD_OFFSET(CMsgClientToGCSurvivorsGameTelemetryData, _impl_.time_survived_)>(
          reinterpret_cast<char*>(&_impl_.time_survived_),
          reinterpret_cast<char*>(&other->_impl_.time_survived_));
}

::PROTOBUF_NAMESPACE_ID::Metadata CMsgClientToGCSurvivorsGameTelemetryData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_dota_5fgcmessages_5fcommon_5fsurvivors_2eproto_getter, &descriptor_table_dota_5fgcmessages_5fcommon_5fsurvivors_2eproto_once,
      file_level_metadata_dota_5fgcmessages_5fcommon_5fsurvivors_2eproto[3]);
}

// ===================================================================

class CMsgClientToGCSurvivorsGameTelemetryDataResponse::_Internal {
 public:
  using HasBits = decltype(std::declval<CMsgClientToGCSurvivorsGameTelemetryDataResponse>()._impl_._has_bits_);
  static void set_has_response(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

CMsgClientToGCSurvivorsGameTelemetryDataResponse::CMsgClientToGCSurvivorsGameTelemetryDataResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:CMsgClientToGCSurvivorsGameTelemetryDataResponse)
}
CMsgClientToGCSurvivorsGameTelemetryDataResponse::CMsgClientToGCSurvivorsGameTelemetryDataResponse(const CMsgClientToGCSurvivorsGameTelemetryDataResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CMsgClientToGCSurvivorsGameTelemetryDataResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.response_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.response_ = from._impl_.response_;
  // @@protoc_insertion_point(copy_constructor:CMsgClientToGCSurvivorsGameTelemetryDataResponse)
}

inline void CMsgClientToGCSurvivorsGameTelemetryDataResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.response_){0}
  };
}

CMsgClientToGCSurvivorsGameTelemetryDataResponse::~CMsgClientToGCSurvivorsGameTelemetryDataResponse() {
  // @@protoc_insertion_point(destructor:CMsgClientToGCSurvivorsGameTelemetryDataResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CMsgClientToGCSurvivorsGameTelemetryDataResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void CMsgClientToGCSurvivorsGameTelemetryDataResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CMsgClientToGCSurvivorsGameTelemetryDataResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:CMsgClientToGCSurvivorsGameTelemetryDataResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.response_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CMsgClientToGCSurvivorsGameTelemetryDataResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional .CMsgClientToGCSurvivorsGameTelemetryDataResponse.EResponse response = 1 [default = k_eInternalError];
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          if (PROTOBUF_PREDICT_TRUE(::CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse_IsValid(val))) {
            _internal_set_response(static_cast<::CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse>(val));
          } else {
            ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(1, val, mutable_unknown_fields());
          }
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CMsgClientToGCSurvivorsGameTelemetryDataResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CMsgClientToGCSurvivorsGameTelemetryDataResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional .CMsgClientToGCSurvivorsGameTelemetryDataResponse.EResponse response = 1 [default = k_eInternalError];
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_response(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CMsgClientToGCSurvivorsGameTelemetryDataResponse)
  return target;
}

size_t CMsgClientToGCSurvivorsGameTelemetryDataResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CMsgClientToGCSurvivorsGameTelemetryDataResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional .CMsgClientToGCSurvivorsGameTelemetryDataResponse.EResponse response = 1 [default = k_eInternalError];
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_response());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CMsgClientToGCSurvivorsGameTelemetryDataResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CMsgClientToGCSurvivorsGameTelemetryDataResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CMsgClientToGCSurvivorsGameTelemetryDataResponse::GetClassData() const { return &_class_data_; }


void CMsgClientToGCSurvivorsGameTelemetryDataResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CMsgClientToGCSurvivorsGameTelemetryDataResponse*>(&to_msg);
  auto& from = static_cast<const CMsgClientToGCSurvivorsGameTelemetryDataResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:CMsgClientToGCSurvivorsGameTelemetryDataResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_response()) {
    _this->_internal_set_response(from._internal_response());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CMsgClientToGCSurvivorsGameTelemetryDataResponse::CopyFrom(const CMsgClientToGCSurvivorsGameTelemetryDataResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CMsgClientToGCSurvivorsGameTelemetryDataResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CMsgClientToGCSurvivorsGameTelemetryDataResponse::IsInitialized() const {
  return true;
}

void CMsgClientToGCSurvivorsGameTelemetryDataResponse::InternalSwap(CMsgClientToGCSurvivorsGameTelemetryDataResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.response_, other->_impl_.response_);
}

::PROTOBUF_NAMESPACE_ID::Metadata CMsgClientToGCSurvivorsGameTelemetryDataResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_dota_5fgcmessages_5fcommon_5fsurvivors_2eproto_getter, &descriptor_table_dota_5fgcmessages_5fcommon_5fsurvivors_2eproto_once,
      file_level_metadata_dota_5fgcmessages_5fcommon_5fsurvivors_2eproto[4]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::CMsgSurvivorsUserData_AttributeLevelsEntry*
Arena::CreateMaybeMessage< ::CMsgSurvivorsUserData_AttributeLevelsEntry >(Arena* arena) {
  return Arena::CreateMessageInternal< ::CMsgSurvivorsUserData_AttributeLevelsEntry >(arena);
}
template<> PROTOBUF_NOINLINE ::CMsgSurvivorsUserData*
Arena::CreateMaybeMessage< ::CMsgSurvivorsUserData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::CMsgSurvivorsUserData >(arena);
}
template<> PROTOBUF_NOINLINE ::CMsgClientToGCSurvivorsPowerUpTelemetryData*
Arena::CreateMaybeMessage< ::CMsgClientToGCSurvivorsPowerUpTelemetryData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::CMsgClientToGCSurvivorsPowerUpTelemetryData >(arena);
}
template<> PROTOBUF_NOINLINE ::CMsgClientToGCSurvivorsGameTelemetryData*
Arena::CreateMaybeMessage< ::CMsgClientToGCSurvivorsGameTelemetryData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::CMsgClientToGCSurvivorsGameTelemetryData >(arena);
}
template<> PROTOBUF_NOINLINE ::CMsgClientToGCSurvivorsGameTelemetryDataResponse*
Arena::CreateMaybeMessage< ::CMsgClientToGCSurvivorsGameTelemetryDataResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::CMsgClientToGCSurvivorsGameTelemetryDataResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
