// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dota_gcmessages_common_survivors.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_dota_5fgcmessages_5fcommon_5fsurvivors_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_dota_5fgcmessages_5fcommon_5fsurvivors_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021008 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "steammessages.pb.h"
#include "dota_shared_enums.pb.h"
#include "dota_gcmessages_common.pb.h"
#include "gcsdk_gcmessages.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_dota_5fgcmessages_5fcommon_5fsurvivors_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_dota_5fgcmessages_5fcommon_5fsurvivors_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_dota_5fgcmessages_5fcommon_5fsurvivors_2eproto;
class CMsgClientToGCSurvivorsGameTelemetryData;
struct CMsgClientToGCSurvivorsGameTelemetryDataDefaultTypeInternal;
extern CMsgClientToGCSurvivorsGameTelemetryDataDefaultTypeInternal _CMsgClientToGCSurvivorsGameTelemetryData_default_instance_;
class CMsgClientToGCSurvivorsGameTelemetryDataResponse;
struct CMsgClientToGCSurvivorsGameTelemetryDataResponseDefaultTypeInternal;
extern CMsgClientToGCSurvivorsGameTelemetryDataResponseDefaultTypeInternal _CMsgClientToGCSurvivorsGameTelemetryDataResponse_default_instance_;
class CMsgClientToGCSurvivorsPowerUpTelemetryData;
struct CMsgClientToGCSurvivorsPowerUpTelemetryDataDefaultTypeInternal;
extern CMsgClientToGCSurvivorsPowerUpTelemetryDataDefaultTypeInternal _CMsgClientToGCSurvivorsPowerUpTelemetryData_default_instance_;
class CMsgSurvivorsUserData;
struct CMsgSurvivorsUserDataDefaultTypeInternal;
extern CMsgSurvivorsUserDataDefaultTypeInternal _CMsgSurvivorsUserData_default_instance_;
class CMsgSurvivorsUserData_AttributeLevelsEntry;
struct CMsgSurvivorsUserData_AttributeLevelsEntryDefaultTypeInternal;
extern CMsgSurvivorsUserData_AttributeLevelsEntryDefaultTypeInternal _CMsgSurvivorsUserData_AttributeLevelsEntry_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::CMsgClientToGCSurvivorsGameTelemetryData* Arena::CreateMaybeMessage<::CMsgClientToGCSurvivorsGameTelemetryData>(Arena*);
template<> ::CMsgClientToGCSurvivorsGameTelemetryDataResponse* Arena::CreateMaybeMessage<::CMsgClientToGCSurvivorsGameTelemetryDataResponse>(Arena*);
template<> ::CMsgClientToGCSurvivorsPowerUpTelemetryData* Arena::CreateMaybeMessage<::CMsgClientToGCSurvivorsPowerUpTelemetryData>(Arena*);
template<> ::CMsgSurvivorsUserData* Arena::CreateMaybeMessage<::CMsgSurvivorsUserData>(Arena*);
template<> ::CMsgSurvivorsUserData_AttributeLevelsEntry* Arena::CreateMaybeMessage<::CMsgSurvivorsUserData_AttributeLevelsEntry>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

enum CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse : int {
  CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse_k_eInternalError = 0,
  CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse_k_eSuccess = 1,
  CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse_k_eTooBusy = 2,
  CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse_k_eDisabled = 3,
  CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse_k_eTimeout = 4,
  CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse_k_eNotAllowed = 5,
  CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse_k_eInvalidItem = 6
};
bool CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse_IsValid(int value);
constexpr CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse_EResponse_MIN = CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse_k_eInternalError;
constexpr CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse_EResponse_MAX = CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse_k_eInvalidItem;
constexpr int CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse_EResponse_ARRAYSIZE = CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse_EResponse_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse_descriptor();
template<typename T>
inline const std::string& CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse_Name(T enum_t_value) {
  static_assert(::std::is_same<T, CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse_descriptor(), enum_t_value);
}
inline bool CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse>(
    CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse_descriptor(), name, value);
}
// ===================================================================

class CMsgSurvivorsUserData_AttributeLevelsEntry final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:CMsgSurvivorsUserData.AttributeLevelsEntry) */ {
 public:
  inline CMsgSurvivorsUserData_AttributeLevelsEntry() : CMsgSurvivorsUserData_AttributeLevelsEntry(nullptr) {}
  ~CMsgSurvivorsUserData_AttributeLevelsEntry() override;
  explicit PROTOBUF_CONSTEXPR CMsgSurvivorsUserData_AttributeLevelsEntry(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CMsgSurvivorsUserData_AttributeLevelsEntry(const CMsgSurvivorsUserData_AttributeLevelsEntry& from);
  CMsgSurvivorsUserData_AttributeLevelsEntry(CMsgSurvivorsUserData_AttributeLevelsEntry&& from) noexcept
    : CMsgSurvivorsUserData_AttributeLevelsEntry() {
    *this = ::std::move(from);
  }

  inline CMsgSurvivorsUserData_AttributeLevelsEntry& operator=(const CMsgSurvivorsUserData_AttributeLevelsEntry& from) {
    CopyFrom(from);
    return *this;
  }
  inline CMsgSurvivorsUserData_AttributeLevelsEntry& operator=(CMsgSurvivorsUserData_AttributeLevelsEntry&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CMsgSurvivorsUserData_AttributeLevelsEntry& default_instance() {
    return *internal_default_instance();
  }
  static inline const CMsgSurvivorsUserData_AttributeLevelsEntry* internal_default_instance() {
    return reinterpret_cast<const CMsgSurvivorsUserData_AttributeLevelsEntry*>(
               &_CMsgSurvivorsUserData_AttributeLevelsEntry_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CMsgSurvivorsUserData_AttributeLevelsEntry& a, CMsgSurvivorsUserData_AttributeLevelsEntry& b) {
    a.Swap(&b);
  }
  inline void Swap(CMsgSurvivorsUserData_AttributeLevelsEntry* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CMsgSurvivorsUserData_AttributeLevelsEntry* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CMsgSurvivorsUserData_AttributeLevelsEntry* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CMsgSurvivorsUserData_AttributeLevelsEntry>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CMsgSurvivorsUserData_AttributeLevelsEntry& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CMsgSurvivorsUserData_AttributeLevelsEntry& from) {
    CMsgSurvivorsUserData_AttributeLevelsEntry::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CMsgSurvivorsUserData_AttributeLevelsEntry* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "CMsgSurvivorsUserData.AttributeLevelsEntry";
  }
  protected:
  explicit CMsgSurvivorsUserData_AttributeLevelsEntry(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kKeyFieldNumber = 1,
    kValueFieldNumber = 2,
  };
  // optional int32 key = 1;
  bool has_key() const;
  private:
  bool _internal_has_key() const;
  public:
  void clear_key();
  int32_t key() const;
  void set_key(int32_t value);
  private:
  int32_t _internal_key() const;
  void _internal_set_key(int32_t value);
  public:

  // optional uint32 value = 2;
  bool has_value() const;
  private:
  bool _internal_has_value() const;
  public:
  void clear_value();
  uint32_t value() const;
  void set_value(uint32_t value);
  private:
  uint32_t _internal_value() const;
  void _internal_set_value(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:CMsgSurvivorsUserData.AttributeLevelsEntry)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    int32_t key_;
    uint32_t value_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_dota_5fgcmessages_5fcommon_5fsurvivors_2eproto;
};
// -------------------------------------------------------------------

class CMsgSurvivorsUserData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:CMsgSurvivorsUserData) */ {
 public:
  inline CMsgSurvivorsUserData() : CMsgSurvivorsUserData(nullptr) {}
  ~CMsgSurvivorsUserData() override;
  explicit PROTOBUF_CONSTEXPR CMsgSurvivorsUserData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CMsgSurvivorsUserData(const CMsgSurvivorsUserData& from);
  CMsgSurvivorsUserData(CMsgSurvivorsUserData&& from) noexcept
    : CMsgSurvivorsUserData() {
    *this = ::std::move(from);
  }

  inline CMsgSurvivorsUserData& operator=(const CMsgSurvivorsUserData& from) {
    CopyFrom(from);
    return *this;
  }
  inline CMsgSurvivorsUserData& operator=(CMsgSurvivorsUserData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CMsgSurvivorsUserData& default_instance() {
    return *internal_default_instance();
  }
  static inline const CMsgSurvivorsUserData* internal_default_instance() {
    return reinterpret_cast<const CMsgSurvivorsUserData*>(
               &_CMsgSurvivorsUserData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(CMsgSurvivorsUserData& a, CMsgSurvivorsUserData& b) {
    a.Swap(&b);
  }
  inline void Swap(CMsgSurvivorsUserData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CMsgSurvivorsUserData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CMsgSurvivorsUserData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CMsgSurvivorsUserData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CMsgSurvivorsUserData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CMsgSurvivorsUserData& from) {
    CMsgSurvivorsUserData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CMsgSurvivorsUserData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "CMsgSurvivorsUserData";
  }
  protected:
  explicit CMsgSurvivorsUserData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef CMsgSurvivorsUserData_AttributeLevelsEntry AttributeLevelsEntry;

  // accessors -------------------------------------------------------

  enum : int {
    kAttributeLevelsFieldNumber = 1,
    kUnlockedDifficultyFieldNumber = 2,
  };
  // repeated .CMsgSurvivorsUserData.AttributeLevelsEntry attribute_levels = 1;
  int attribute_levels_size() const;
  private:
  int _internal_attribute_levels_size() const;
  public:
  void clear_attribute_levels();
  ::CMsgSurvivorsUserData_AttributeLevelsEntry* mutable_attribute_levels(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CMsgSurvivorsUserData_AttributeLevelsEntry >*
      mutable_attribute_levels();
  private:
  const ::CMsgSurvivorsUserData_AttributeLevelsEntry& _internal_attribute_levels(int index) const;
  ::CMsgSurvivorsUserData_AttributeLevelsEntry* _internal_add_attribute_levels();
  public:
  const ::CMsgSurvivorsUserData_AttributeLevelsEntry& attribute_levels(int index) const;
  ::CMsgSurvivorsUserData_AttributeLevelsEntry* add_attribute_levels();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CMsgSurvivorsUserData_AttributeLevelsEntry >&
      attribute_levels() const;

  // optional uint32 unlocked_difficulty = 2;
  bool has_unlocked_difficulty() const;
  private:
  bool _internal_has_unlocked_difficulty() const;
  public:
  void clear_unlocked_difficulty();
  uint32_t unlocked_difficulty() const;
  void set_unlocked_difficulty(uint32_t value);
  private:
  uint32_t _internal_unlocked_difficulty() const;
  void _internal_set_unlocked_difficulty(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:CMsgSurvivorsUserData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CMsgSurvivorsUserData_AttributeLevelsEntry > attribute_levels_;
    uint32_t unlocked_difficulty_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_dota_5fgcmessages_5fcommon_5fsurvivors_2eproto;
};
// -------------------------------------------------------------------

class CMsgClientToGCSurvivorsPowerUpTelemetryData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:CMsgClientToGCSurvivorsPowerUpTelemetryData) */ {
 public:
  inline CMsgClientToGCSurvivorsPowerUpTelemetryData() : CMsgClientToGCSurvivorsPowerUpTelemetryData(nullptr) {}
  ~CMsgClientToGCSurvivorsPowerUpTelemetryData() override;
  explicit PROTOBUF_CONSTEXPR CMsgClientToGCSurvivorsPowerUpTelemetryData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CMsgClientToGCSurvivorsPowerUpTelemetryData(const CMsgClientToGCSurvivorsPowerUpTelemetryData& from);
  CMsgClientToGCSurvivorsPowerUpTelemetryData(CMsgClientToGCSurvivorsPowerUpTelemetryData&& from) noexcept
    : CMsgClientToGCSurvivorsPowerUpTelemetryData() {
    *this = ::std::move(from);
  }

  inline CMsgClientToGCSurvivorsPowerUpTelemetryData& operator=(const CMsgClientToGCSurvivorsPowerUpTelemetryData& from) {
    CopyFrom(from);
    return *this;
  }
  inline CMsgClientToGCSurvivorsPowerUpTelemetryData& operator=(CMsgClientToGCSurvivorsPowerUpTelemetryData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CMsgClientToGCSurvivorsPowerUpTelemetryData& default_instance() {
    return *internal_default_instance();
  }
  static inline const CMsgClientToGCSurvivorsPowerUpTelemetryData* internal_default_instance() {
    return reinterpret_cast<const CMsgClientToGCSurvivorsPowerUpTelemetryData*>(
               &_CMsgClientToGCSurvivorsPowerUpTelemetryData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(CMsgClientToGCSurvivorsPowerUpTelemetryData& a, CMsgClientToGCSurvivorsPowerUpTelemetryData& b) {
    a.Swap(&b);
  }
  inline void Swap(CMsgClientToGCSurvivorsPowerUpTelemetryData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CMsgClientToGCSurvivorsPowerUpTelemetryData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CMsgClientToGCSurvivorsPowerUpTelemetryData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CMsgClientToGCSurvivorsPowerUpTelemetryData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CMsgClientToGCSurvivorsPowerUpTelemetryData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CMsgClientToGCSurvivorsPowerUpTelemetryData& from) {
    CMsgClientToGCSurvivorsPowerUpTelemetryData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CMsgClientToGCSurvivorsPowerUpTelemetryData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "CMsgClientToGCSurvivorsPowerUpTelemetryData";
  }
  protected:
  explicit CMsgClientToGCSurvivorsPowerUpTelemetryData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPowerupIdFieldNumber = 1,
    kLevelFieldNumber = 2,
    kTimeReceivedFieldNumber = 3,
    kTimeHeldFieldNumber = 4,
    kTotalDamageFieldNumber = 5,
    kDpsFieldNumber = 6,
    kHasScepterFieldNumber = 7,
  };
  // optional uint32 powerup_id = 1;
  bool has_powerup_id() const;
  private:
  bool _internal_has_powerup_id() const;
  public:
  void clear_powerup_id();
  uint32_t powerup_id() const;
  void set_powerup_id(uint32_t value);
  private:
  uint32_t _internal_powerup_id() const;
  void _internal_set_powerup_id(uint32_t value);
  public:

  // optional uint32 level = 2;
  bool has_level() const;
  private:
  bool _internal_has_level() const;
  public:
  void clear_level();
  uint32_t level() const;
  void set_level(uint32_t value);
  private:
  uint32_t _internal_level() const;
  void _internal_set_level(uint32_t value);
  public:

  // optional uint32 time_received = 3;
  bool has_time_received() const;
  private:
  bool _internal_has_time_received() const;
  public:
  void clear_time_received();
  uint32_t time_received() const;
  void set_time_received(uint32_t value);
  private:
  uint32_t _internal_time_received() const;
  void _internal_set_time_received(uint32_t value);
  public:

  // optional uint32 time_held = 4;
  bool has_time_held() const;
  private:
  bool _internal_has_time_held() const;
  public:
  void clear_time_held();
  uint32_t time_held() const;
  void set_time_held(uint32_t value);
  private:
  uint32_t _internal_time_held() const;
  void _internal_set_time_held(uint32_t value);
  public:

  // optional uint64 total_damage = 5;
  bool has_total_damage() const;
  private:
  bool _internal_has_total_damage() const;
  public:
  void clear_total_damage();
  uint64_t total_damage() const;
  void set_total_damage(uint64_t value);
  private:
  uint64_t _internal_total_damage() const;
  void _internal_set_total_damage(uint64_t value);
  public:

  // optional uint32 dps = 6;
  bool has_dps() const;
  private:
  bool _internal_has_dps() const;
  public:
  void clear_dps();
  uint32_t dps() const;
  void set_dps(uint32_t value);
  private:
  uint32_t _internal_dps() const;
  void _internal_set_dps(uint32_t value);
  public:

  // optional uint32 has_scepter = 7;
  bool has_has_scepter() const;
  private:
  bool _internal_has_has_scepter() const;
  public:
  void clear_has_scepter();
  uint32_t has_scepter() const;
  void set_has_scepter(uint32_t value);
  private:
  uint32_t _internal_has_scepter() const;
  void _internal_set_has_scepter(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:CMsgClientToGCSurvivorsPowerUpTelemetryData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t powerup_id_;
    uint32_t level_;
    uint32_t time_received_;
    uint32_t time_held_;
    uint64_t total_damage_;
    uint32_t dps_;
    uint32_t has_scepter_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_dota_5fgcmessages_5fcommon_5fsurvivors_2eproto;
};
// -------------------------------------------------------------------

class CMsgClientToGCSurvivorsGameTelemetryData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:CMsgClientToGCSurvivorsGameTelemetryData) */ {
 public:
  inline CMsgClientToGCSurvivorsGameTelemetryData() : CMsgClientToGCSurvivorsGameTelemetryData(nullptr) {}
  ~CMsgClientToGCSurvivorsGameTelemetryData() override;
  explicit PROTOBUF_CONSTEXPR CMsgClientToGCSurvivorsGameTelemetryData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CMsgClientToGCSurvivorsGameTelemetryData(const CMsgClientToGCSurvivorsGameTelemetryData& from);
  CMsgClientToGCSurvivorsGameTelemetryData(CMsgClientToGCSurvivorsGameTelemetryData&& from) noexcept
    : CMsgClientToGCSurvivorsGameTelemetryData() {
    *this = ::std::move(from);
  }

  inline CMsgClientToGCSurvivorsGameTelemetryData& operator=(const CMsgClientToGCSurvivorsGameTelemetryData& from) {
    CopyFrom(from);
    return *this;
  }
  inline CMsgClientToGCSurvivorsGameTelemetryData& operator=(CMsgClientToGCSurvivorsGameTelemetryData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CMsgClientToGCSurvivorsGameTelemetryData& default_instance() {
    return *internal_default_instance();
  }
  static inline const CMsgClientToGCSurvivorsGameTelemetryData* internal_default_instance() {
    return reinterpret_cast<const CMsgClientToGCSurvivorsGameTelemetryData*>(
               &_CMsgClientToGCSurvivorsGameTelemetryData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(CMsgClientToGCSurvivorsGameTelemetryData& a, CMsgClientToGCSurvivorsGameTelemetryData& b) {
    a.Swap(&b);
  }
  inline void Swap(CMsgClientToGCSurvivorsGameTelemetryData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CMsgClientToGCSurvivorsGameTelemetryData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CMsgClientToGCSurvivorsGameTelemetryData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CMsgClientToGCSurvivorsGameTelemetryData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CMsgClientToGCSurvivorsGameTelemetryData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CMsgClientToGCSurvivorsGameTelemetryData& from) {
    CMsgClientToGCSurvivorsGameTelemetryData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CMsgClientToGCSurvivorsGameTelemetryData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "CMsgClientToGCSurvivorsGameTelemetryData";
  }
  protected:
  explicit CMsgClientToGCSurvivorsGameTelemetryData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPowerupsFieldNumber = 5,
    kTimeSurvivedFieldNumber = 1,
    kPlayerLevelFieldNumber = 2,
    kGameResultFieldNumber = 3,
    kGoldEarnedFieldNumber = 4,
    kDifficultyFieldNumber = 6,
    kMetaprogressionLevelFieldNumber = 7,
  };
  // repeated .CMsgClientToGCSurvivorsPowerUpTelemetryData powerups = 5;
  int powerups_size() const;
  private:
  int _internal_powerups_size() const;
  public:
  void clear_powerups();
  ::CMsgClientToGCSurvivorsPowerUpTelemetryData* mutable_powerups(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CMsgClientToGCSurvivorsPowerUpTelemetryData >*
      mutable_powerups();
  private:
  const ::CMsgClientToGCSurvivorsPowerUpTelemetryData& _internal_powerups(int index) const;
  ::CMsgClientToGCSurvivorsPowerUpTelemetryData* _internal_add_powerups();
  public:
  const ::CMsgClientToGCSurvivorsPowerUpTelemetryData& powerups(int index) const;
  ::CMsgClientToGCSurvivorsPowerUpTelemetryData* add_powerups();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CMsgClientToGCSurvivorsPowerUpTelemetryData >&
      powerups() const;

  // optional uint32 time_survived = 1;
  bool has_time_survived() const;
  private:
  bool _internal_has_time_survived() const;
  public:
  void clear_time_survived();
  uint32_t time_survived() const;
  void set_time_survived(uint32_t value);
  private:
  uint32_t _internal_time_survived() const;
  void _internal_set_time_survived(uint32_t value);
  public:

  // optional uint32 player_level = 2;
  bool has_player_level() const;
  private:
  bool _internal_has_player_level() const;
  public:
  void clear_player_level();
  uint32_t player_level() const;
  void set_player_level(uint32_t value);
  private:
  uint32_t _internal_player_level() const;
  void _internal_set_player_level(uint32_t value);
  public:

  // optional uint32 game_result = 3;
  bool has_game_result() const;
  private:
  bool _internal_has_game_result() const;
  public:
  void clear_game_result();
  uint32_t game_result() const;
  void set_game_result(uint32_t value);
  private:
  uint32_t _internal_game_result() const;
  void _internal_set_game_result(uint32_t value);
  public:

  // optional uint32 gold_earned = 4;
  bool has_gold_earned() const;
  private:
  bool _internal_has_gold_earned() const;
  public:
  void clear_gold_earned();
  uint32_t gold_earned() const;
  void set_gold_earned(uint32_t value);
  private:
  uint32_t _internal_gold_earned() const;
  void _internal_set_gold_earned(uint32_t value);
  public:

  // optional uint32 difficulty = 6;
  bool has_difficulty() const;
  private:
  bool _internal_has_difficulty() const;
  public:
  void clear_difficulty();
  uint32_t difficulty() const;
  void set_difficulty(uint32_t value);
  private:
  uint32_t _internal_difficulty() const;
  void _internal_set_difficulty(uint32_t value);
  public:

  // optional uint32 metaprogression_level = 7;
  bool has_metaprogression_level() const;
  private:
  bool _internal_has_metaprogression_level() const;
  public:
  void clear_metaprogression_level();
  uint32_t metaprogression_level() const;
  void set_metaprogression_level(uint32_t value);
  private:
  uint32_t _internal_metaprogression_level() const;
  void _internal_set_metaprogression_level(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:CMsgClientToGCSurvivorsGameTelemetryData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CMsgClientToGCSurvivorsPowerUpTelemetryData > powerups_;
    uint32_t time_survived_;
    uint32_t player_level_;
    uint32_t game_result_;
    uint32_t gold_earned_;
    uint32_t difficulty_;
    uint32_t metaprogression_level_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_dota_5fgcmessages_5fcommon_5fsurvivors_2eproto;
};
// -------------------------------------------------------------------

class CMsgClientToGCSurvivorsGameTelemetryDataResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:CMsgClientToGCSurvivorsGameTelemetryDataResponse) */ {
 public:
  inline CMsgClientToGCSurvivorsGameTelemetryDataResponse() : CMsgClientToGCSurvivorsGameTelemetryDataResponse(nullptr) {}
  ~CMsgClientToGCSurvivorsGameTelemetryDataResponse() override;
  explicit PROTOBUF_CONSTEXPR CMsgClientToGCSurvivorsGameTelemetryDataResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CMsgClientToGCSurvivorsGameTelemetryDataResponse(const CMsgClientToGCSurvivorsGameTelemetryDataResponse& from);
  CMsgClientToGCSurvivorsGameTelemetryDataResponse(CMsgClientToGCSurvivorsGameTelemetryDataResponse&& from) noexcept
    : CMsgClientToGCSurvivorsGameTelemetryDataResponse() {
    *this = ::std::move(from);
  }

  inline CMsgClientToGCSurvivorsGameTelemetryDataResponse& operator=(const CMsgClientToGCSurvivorsGameTelemetryDataResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline CMsgClientToGCSurvivorsGameTelemetryDataResponse& operator=(CMsgClientToGCSurvivorsGameTelemetryDataResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CMsgClientToGCSurvivorsGameTelemetryDataResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const CMsgClientToGCSurvivorsGameTelemetryDataResponse* internal_default_instance() {
    return reinterpret_cast<const CMsgClientToGCSurvivorsGameTelemetryDataResponse*>(
               &_CMsgClientToGCSurvivorsGameTelemetryDataResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(CMsgClientToGCSurvivorsGameTelemetryDataResponse& a, CMsgClientToGCSurvivorsGameTelemetryDataResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(CMsgClientToGCSurvivorsGameTelemetryDataResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CMsgClientToGCSurvivorsGameTelemetryDataResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CMsgClientToGCSurvivorsGameTelemetryDataResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CMsgClientToGCSurvivorsGameTelemetryDataResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CMsgClientToGCSurvivorsGameTelemetryDataResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CMsgClientToGCSurvivorsGameTelemetryDataResponse& from) {
    CMsgClientToGCSurvivorsGameTelemetryDataResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CMsgClientToGCSurvivorsGameTelemetryDataResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "CMsgClientToGCSurvivorsGameTelemetryDataResponse";
  }
  protected:
  explicit CMsgClientToGCSurvivorsGameTelemetryDataResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse EResponse;
  static constexpr EResponse k_eInternalError =
    CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse_k_eInternalError;
  static constexpr EResponse k_eSuccess =
    CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse_k_eSuccess;
  static constexpr EResponse k_eTooBusy =
    CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse_k_eTooBusy;
  static constexpr EResponse k_eDisabled =
    CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse_k_eDisabled;
  static constexpr EResponse k_eTimeout =
    CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse_k_eTimeout;
  static constexpr EResponse k_eNotAllowed =
    CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse_k_eNotAllowed;
  static constexpr EResponse k_eInvalidItem =
    CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse_k_eInvalidItem;
  static inline bool EResponse_IsValid(int value) {
    return CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse_IsValid(value);
  }
  static constexpr EResponse EResponse_MIN =
    CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse_EResponse_MIN;
  static constexpr EResponse EResponse_MAX =
    CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse_EResponse_MAX;
  static constexpr int EResponse_ARRAYSIZE =
    CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse_EResponse_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  EResponse_descriptor() {
    return CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse_descriptor();
  }
  template<typename T>
  static inline const std::string& EResponse_Name(T enum_t_value) {
    static_assert(::std::is_same<T, EResponse>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function EResponse_Name.");
    return CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse_Name(enum_t_value);
  }
  static inline bool EResponse_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      EResponse* value) {
    return CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kResponseFieldNumber = 1,
  };
  // optional .CMsgClientToGCSurvivorsGameTelemetryDataResponse.EResponse response = 1 [default = k_eInternalError];
  bool has_response() const;
  private:
  bool _internal_has_response() const;
  public:
  void clear_response();
  ::CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse response() const;
  void set_response(::CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse value);
  private:
  ::CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse _internal_response() const;
  void _internal_set_response(::CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse value);
  public:

  // @@protoc_insertion_point(class_scope:CMsgClientToGCSurvivorsGameTelemetryDataResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    int response_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_dota_5fgcmessages_5fcommon_5fsurvivors_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CMsgSurvivorsUserData_AttributeLevelsEntry

// optional int32 key = 1;
inline bool CMsgSurvivorsUserData_AttributeLevelsEntry::_internal_has_key() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool CMsgSurvivorsUserData_AttributeLevelsEntry::has_key() const {
  return _internal_has_key();
}
inline void CMsgSurvivorsUserData_AttributeLevelsEntry::clear_key() {
  _impl_.key_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline int32_t CMsgSurvivorsUserData_AttributeLevelsEntry::_internal_key() const {
  return _impl_.key_;
}
inline int32_t CMsgSurvivorsUserData_AttributeLevelsEntry::key() const {
  // @@protoc_insertion_point(field_get:CMsgSurvivorsUserData.AttributeLevelsEntry.key)
  return _internal_key();
}
inline void CMsgSurvivorsUserData_AttributeLevelsEntry::_internal_set_key(int32_t value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.key_ = value;
}
inline void CMsgSurvivorsUserData_AttributeLevelsEntry::set_key(int32_t value) {
  _internal_set_key(value);
  // @@protoc_insertion_point(field_set:CMsgSurvivorsUserData.AttributeLevelsEntry.key)
}

// optional uint32 value = 2;
inline bool CMsgSurvivorsUserData_AttributeLevelsEntry::_internal_has_value() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool CMsgSurvivorsUserData_AttributeLevelsEntry::has_value() const {
  return _internal_has_value();
}
inline void CMsgSurvivorsUserData_AttributeLevelsEntry::clear_value() {
  _impl_.value_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline uint32_t CMsgSurvivorsUserData_AttributeLevelsEntry::_internal_value() const {
  return _impl_.value_;
}
inline uint32_t CMsgSurvivorsUserData_AttributeLevelsEntry::value() const {
  // @@protoc_insertion_point(field_get:CMsgSurvivorsUserData.AttributeLevelsEntry.value)
  return _internal_value();
}
inline void CMsgSurvivorsUserData_AttributeLevelsEntry::_internal_set_value(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.value_ = value;
}
inline void CMsgSurvivorsUserData_AttributeLevelsEntry::set_value(uint32_t value) {
  _internal_set_value(value);
  // @@protoc_insertion_point(field_set:CMsgSurvivorsUserData.AttributeLevelsEntry.value)
}

// -------------------------------------------------------------------

// CMsgSurvivorsUserData

// repeated .CMsgSurvivorsUserData.AttributeLevelsEntry attribute_levels = 1;
inline int CMsgSurvivorsUserData::_internal_attribute_levels_size() const {
  return _impl_.attribute_levels_.size();
}
inline int CMsgSurvivorsUserData::attribute_levels_size() const {
  return _internal_attribute_levels_size();
}
inline void CMsgSurvivorsUserData::clear_attribute_levels() {
  _impl_.attribute_levels_.Clear();
}
inline ::CMsgSurvivorsUserData_AttributeLevelsEntry* CMsgSurvivorsUserData::mutable_attribute_levels(int index) {
  // @@protoc_insertion_point(field_mutable:CMsgSurvivorsUserData.attribute_levels)
  return _impl_.attribute_levels_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CMsgSurvivorsUserData_AttributeLevelsEntry >*
CMsgSurvivorsUserData::mutable_attribute_levels() {
  // @@protoc_insertion_point(field_mutable_list:CMsgSurvivorsUserData.attribute_levels)
  return &_impl_.attribute_levels_;
}
inline const ::CMsgSurvivorsUserData_AttributeLevelsEntry& CMsgSurvivorsUserData::_internal_attribute_levels(int index) const {
  return _impl_.attribute_levels_.Get(index);
}
inline const ::CMsgSurvivorsUserData_AttributeLevelsEntry& CMsgSurvivorsUserData::attribute_levels(int index) const {
  // @@protoc_insertion_point(field_get:CMsgSurvivorsUserData.attribute_levels)
  return _internal_attribute_levels(index);
}
inline ::CMsgSurvivorsUserData_AttributeLevelsEntry* CMsgSurvivorsUserData::_internal_add_attribute_levels() {
  return _impl_.attribute_levels_.Add();
}
inline ::CMsgSurvivorsUserData_AttributeLevelsEntry* CMsgSurvivorsUserData::add_attribute_levels() {
  ::CMsgSurvivorsUserData_AttributeLevelsEntry* _add = _internal_add_attribute_levels();
  // @@protoc_insertion_point(field_add:CMsgSurvivorsUserData.attribute_levels)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CMsgSurvivorsUserData_AttributeLevelsEntry >&
CMsgSurvivorsUserData::attribute_levels() const {
  // @@protoc_insertion_point(field_list:CMsgSurvivorsUserData.attribute_levels)
  return _impl_.attribute_levels_;
}

// optional uint32 unlocked_difficulty = 2;
inline bool CMsgSurvivorsUserData::_internal_has_unlocked_difficulty() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool CMsgSurvivorsUserData::has_unlocked_difficulty() const {
  return _internal_has_unlocked_difficulty();
}
inline void CMsgSurvivorsUserData::clear_unlocked_difficulty() {
  _impl_.unlocked_difficulty_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline uint32_t CMsgSurvivorsUserData::_internal_unlocked_difficulty() const {
  return _impl_.unlocked_difficulty_;
}
inline uint32_t CMsgSurvivorsUserData::unlocked_difficulty() const {
  // @@protoc_insertion_point(field_get:CMsgSurvivorsUserData.unlocked_difficulty)
  return _internal_unlocked_difficulty();
}
inline void CMsgSurvivorsUserData::_internal_set_unlocked_difficulty(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.unlocked_difficulty_ = value;
}
inline void CMsgSurvivorsUserData::set_unlocked_difficulty(uint32_t value) {
  _internal_set_unlocked_difficulty(value);
  // @@protoc_insertion_point(field_set:CMsgSurvivorsUserData.unlocked_difficulty)
}

// -------------------------------------------------------------------

// CMsgClientToGCSurvivorsPowerUpTelemetryData

// optional uint32 powerup_id = 1;
inline bool CMsgClientToGCSurvivorsPowerUpTelemetryData::_internal_has_powerup_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool CMsgClientToGCSurvivorsPowerUpTelemetryData::has_powerup_id() const {
  return _internal_has_powerup_id();
}
inline void CMsgClientToGCSurvivorsPowerUpTelemetryData::clear_powerup_id() {
  _impl_.powerup_id_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline uint32_t CMsgClientToGCSurvivorsPowerUpTelemetryData::_internal_powerup_id() const {
  return _impl_.powerup_id_;
}
inline uint32_t CMsgClientToGCSurvivorsPowerUpTelemetryData::powerup_id() const {
  // @@protoc_insertion_point(field_get:CMsgClientToGCSurvivorsPowerUpTelemetryData.powerup_id)
  return _internal_powerup_id();
}
inline void CMsgClientToGCSurvivorsPowerUpTelemetryData::_internal_set_powerup_id(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.powerup_id_ = value;
}
inline void CMsgClientToGCSurvivorsPowerUpTelemetryData::set_powerup_id(uint32_t value) {
  _internal_set_powerup_id(value);
  // @@protoc_insertion_point(field_set:CMsgClientToGCSurvivorsPowerUpTelemetryData.powerup_id)
}

// optional uint32 level = 2;
inline bool CMsgClientToGCSurvivorsPowerUpTelemetryData::_internal_has_level() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool CMsgClientToGCSurvivorsPowerUpTelemetryData::has_level() const {
  return _internal_has_level();
}
inline void CMsgClientToGCSurvivorsPowerUpTelemetryData::clear_level() {
  _impl_.level_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline uint32_t CMsgClientToGCSurvivorsPowerUpTelemetryData::_internal_level() const {
  return _impl_.level_;
}
inline uint32_t CMsgClientToGCSurvivorsPowerUpTelemetryData::level() const {
  // @@protoc_insertion_point(field_get:CMsgClientToGCSurvivorsPowerUpTelemetryData.level)
  return _internal_level();
}
inline void CMsgClientToGCSurvivorsPowerUpTelemetryData::_internal_set_level(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.level_ = value;
}
inline void CMsgClientToGCSurvivorsPowerUpTelemetryData::set_level(uint32_t value) {
  _internal_set_level(value);
  // @@protoc_insertion_point(field_set:CMsgClientToGCSurvivorsPowerUpTelemetryData.level)
}

// optional uint32 time_received = 3;
inline bool CMsgClientToGCSurvivorsPowerUpTelemetryData::_internal_has_time_received() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool CMsgClientToGCSurvivorsPowerUpTelemetryData::has_time_received() const {
  return _internal_has_time_received();
}
inline void CMsgClientToGCSurvivorsPowerUpTelemetryData::clear_time_received() {
  _impl_.time_received_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline uint32_t CMsgClientToGCSurvivorsPowerUpTelemetryData::_internal_time_received() const {
  return _impl_.time_received_;
}
inline uint32_t CMsgClientToGCSurvivorsPowerUpTelemetryData::time_received() const {
  // @@protoc_insertion_point(field_get:CMsgClientToGCSurvivorsPowerUpTelemetryData.time_received)
  return _internal_time_received();
}
inline void CMsgClientToGCSurvivorsPowerUpTelemetryData::_internal_set_time_received(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.time_received_ = value;
}
inline void CMsgClientToGCSurvivorsPowerUpTelemetryData::set_time_received(uint32_t value) {
  _internal_set_time_received(value);
  // @@protoc_insertion_point(field_set:CMsgClientToGCSurvivorsPowerUpTelemetryData.time_received)
}

// optional uint32 time_held = 4;
inline bool CMsgClientToGCSurvivorsPowerUpTelemetryData::_internal_has_time_held() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool CMsgClientToGCSurvivorsPowerUpTelemetryData::has_time_held() const {
  return _internal_has_time_held();
}
inline void CMsgClientToGCSurvivorsPowerUpTelemetryData::clear_time_held() {
  _impl_.time_held_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline uint32_t CMsgClientToGCSurvivorsPowerUpTelemetryData::_internal_time_held() const {
  return _impl_.time_held_;
}
inline uint32_t CMsgClientToGCSurvivorsPowerUpTelemetryData::time_held() const {
  // @@protoc_insertion_point(field_get:CMsgClientToGCSurvivorsPowerUpTelemetryData.time_held)
  return _internal_time_held();
}
inline void CMsgClientToGCSurvivorsPowerUpTelemetryData::_internal_set_time_held(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.time_held_ = value;
}
inline void CMsgClientToGCSurvivorsPowerUpTelemetryData::set_time_held(uint32_t value) {
  _internal_set_time_held(value);
  // @@protoc_insertion_point(field_set:CMsgClientToGCSurvivorsPowerUpTelemetryData.time_held)
}

// optional uint64 total_damage = 5;
inline bool CMsgClientToGCSurvivorsPowerUpTelemetryData::_internal_has_total_damage() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool CMsgClientToGCSurvivorsPowerUpTelemetryData::has_total_damage() const {
  return _internal_has_total_damage();
}
inline void CMsgClientToGCSurvivorsPowerUpTelemetryData::clear_total_damage() {
  _impl_.total_damage_ = uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline uint64_t CMsgClientToGCSurvivorsPowerUpTelemetryData::_internal_total_damage() const {
  return _impl_.total_damage_;
}
inline uint64_t CMsgClientToGCSurvivorsPowerUpTelemetryData::total_damage() const {
  // @@protoc_insertion_point(field_get:CMsgClientToGCSurvivorsPowerUpTelemetryData.total_damage)
  return _internal_total_damage();
}
inline void CMsgClientToGCSurvivorsPowerUpTelemetryData::_internal_set_total_damage(uint64_t value) {
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.total_damage_ = value;
}
inline void CMsgClientToGCSurvivorsPowerUpTelemetryData::set_total_damage(uint64_t value) {
  _internal_set_total_damage(value);
  // @@protoc_insertion_point(field_set:CMsgClientToGCSurvivorsPowerUpTelemetryData.total_damage)
}

// optional uint32 dps = 6;
inline bool CMsgClientToGCSurvivorsPowerUpTelemetryData::_internal_has_dps() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool CMsgClientToGCSurvivorsPowerUpTelemetryData::has_dps() const {
  return _internal_has_dps();
}
inline void CMsgClientToGCSurvivorsPowerUpTelemetryData::clear_dps() {
  _impl_.dps_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline uint32_t CMsgClientToGCSurvivorsPowerUpTelemetryData::_internal_dps() const {
  return _impl_.dps_;
}
inline uint32_t CMsgClientToGCSurvivorsPowerUpTelemetryData::dps() const {
  // @@protoc_insertion_point(field_get:CMsgClientToGCSurvivorsPowerUpTelemetryData.dps)
  return _internal_dps();
}
inline void CMsgClientToGCSurvivorsPowerUpTelemetryData::_internal_set_dps(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000020u;
  _impl_.dps_ = value;
}
inline void CMsgClientToGCSurvivorsPowerUpTelemetryData::set_dps(uint32_t value) {
  _internal_set_dps(value);
  // @@protoc_insertion_point(field_set:CMsgClientToGCSurvivorsPowerUpTelemetryData.dps)
}

// optional uint32 has_scepter = 7;
inline bool CMsgClientToGCSurvivorsPowerUpTelemetryData::_internal_has_has_scepter() const {
  bool value = (_impl_._has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool CMsgClientToGCSurvivorsPowerUpTelemetryData::has_has_scepter() const {
  return _internal_has_has_scepter();
}
inline void CMsgClientToGCSurvivorsPowerUpTelemetryData::clear_has_scepter() {
  _impl_.has_scepter_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000040u;
}
inline uint32_t CMsgClientToGCSurvivorsPowerUpTelemetryData::_internal_has_scepter() const {
  return _impl_.has_scepter_;
}
inline uint32_t CMsgClientToGCSurvivorsPowerUpTelemetryData::has_scepter() const {
  // @@protoc_insertion_point(field_get:CMsgClientToGCSurvivorsPowerUpTelemetryData.has_scepter)
  return _internal_has_scepter();
}
inline void CMsgClientToGCSurvivorsPowerUpTelemetryData::_internal_set_has_scepter(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000040u;
  _impl_.has_scepter_ = value;
}
inline void CMsgClientToGCSurvivorsPowerUpTelemetryData::set_has_scepter(uint32_t value) {
  _internal_set_has_scepter(value);
  // @@protoc_insertion_point(field_set:CMsgClientToGCSurvivorsPowerUpTelemetryData.has_scepter)
}

// -------------------------------------------------------------------

// CMsgClientToGCSurvivorsGameTelemetryData

// optional uint32 time_survived = 1;
inline bool CMsgClientToGCSurvivorsGameTelemetryData::_internal_has_time_survived() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool CMsgClientToGCSurvivorsGameTelemetryData::has_time_survived() const {
  return _internal_has_time_survived();
}
inline void CMsgClientToGCSurvivorsGameTelemetryData::clear_time_survived() {
  _impl_.time_survived_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline uint32_t CMsgClientToGCSurvivorsGameTelemetryData::_internal_time_survived() const {
  return _impl_.time_survived_;
}
inline uint32_t CMsgClientToGCSurvivorsGameTelemetryData::time_survived() const {
  // @@protoc_insertion_point(field_get:CMsgClientToGCSurvivorsGameTelemetryData.time_survived)
  return _internal_time_survived();
}
inline void CMsgClientToGCSurvivorsGameTelemetryData::_internal_set_time_survived(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.time_survived_ = value;
}
inline void CMsgClientToGCSurvivorsGameTelemetryData::set_time_survived(uint32_t value) {
  _internal_set_time_survived(value);
  // @@protoc_insertion_point(field_set:CMsgClientToGCSurvivorsGameTelemetryData.time_survived)
}

// optional uint32 player_level = 2;
inline bool CMsgClientToGCSurvivorsGameTelemetryData::_internal_has_player_level() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool CMsgClientToGCSurvivorsGameTelemetryData::has_player_level() const {
  return _internal_has_player_level();
}
inline void CMsgClientToGCSurvivorsGameTelemetryData::clear_player_level() {
  _impl_.player_level_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline uint32_t CMsgClientToGCSurvivorsGameTelemetryData::_internal_player_level() const {
  return _impl_.player_level_;
}
inline uint32_t CMsgClientToGCSurvivorsGameTelemetryData::player_level() const {
  // @@protoc_insertion_point(field_get:CMsgClientToGCSurvivorsGameTelemetryData.player_level)
  return _internal_player_level();
}
inline void CMsgClientToGCSurvivorsGameTelemetryData::_internal_set_player_level(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.player_level_ = value;
}
inline void CMsgClientToGCSurvivorsGameTelemetryData::set_player_level(uint32_t value) {
  _internal_set_player_level(value);
  // @@protoc_insertion_point(field_set:CMsgClientToGCSurvivorsGameTelemetryData.player_level)
}

// optional uint32 game_result = 3;
inline bool CMsgClientToGCSurvivorsGameTelemetryData::_internal_has_game_result() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool CMsgClientToGCSurvivorsGameTelemetryData::has_game_result() const {
  return _internal_has_game_result();
}
inline void CMsgClientToGCSurvivorsGameTelemetryData::clear_game_result() {
  _impl_.game_result_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline uint32_t CMsgClientToGCSurvivorsGameTelemetryData::_internal_game_result() const {
  return _impl_.game_result_;
}
inline uint32_t CMsgClientToGCSurvivorsGameTelemetryData::game_result() const {
  // @@protoc_insertion_point(field_get:CMsgClientToGCSurvivorsGameTelemetryData.game_result)
  return _internal_game_result();
}
inline void CMsgClientToGCSurvivorsGameTelemetryData::_internal_set_game_result(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.game_result_ = value;
}
inline void CMsgClientToGCSurvivorsGameTelemetryData::set_game_result(uint32_t value) {
  _internal_set_game_result(value);
  // @@protoc_insertion_point(field_set:CMsgClientToGCSurvivorsGameTelemetryData.game_result)
}

// optional uint32 gold_earned = 4;
inline bool CMsgClientToGCSurvivorsGameTelemetryData::_internal_has_gold_earned() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool CMsgClientToGCSurvivorsGameTelemetryData::has_gold_earned() const {
  return _internal_has_gold_earned();
}
inline void CMsgClientToGCSurvivorsGameTelemetryData::clear_gold_earned() {
  _impl_.gold_earned_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline uint32_t CMsgClientToGCSurvivorsGameTelemetryData::_internal_gold_earned() const {
  return _impl_.gold_earned_;
}
inline uint32_t CMsgClientToGCSurvivorsGameTelemetryData::gold_earned() const {
  // @@protoc_insertion_point(field_get:CMsgClientToGCSurvivorsGameTelemetryData.gold_earned)
  return _internal_gold_earned();
}
inline void CMsgClientToGCSurvivorsGameTelemetryData::_internal_set_gold_earned(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.gold_earned_ = value;
}
inline void CMsgClientToGCSurvivorsGameTelemetryData::set_gold_earned(uint32_t value) {
  _internal_set_gold_earned(value);
  // @@protoc_insertion_point(field_set:CMsgClientToGCSurvivorsGameTelemetryData.gold_earned)
}

// repeated .CMsgClientToGCSurvivorsPowerUpTelemetryData powerups = 5;
inline int CMsgClientToGCSurvivorsGameTelemetryData::_internal_powerups_size() const {
  return _impl_.powerups_.size();
}
inline int CMsgClientToGCSurvivorsGameTelemetryData::powerups_size() const {
  return _internal_powerups_size();
}
inline void CMsgClientToGCSurvivorsGameTelemetryData::clear_powerups() {
  _impl_.powerups_.Clear();
}
inline ::CMsgClientToGCSurvivorsPowerUpTelemetryData* CMsgClientToGCSurvivorsGameTelemetryData::mutable_powerups(int index) {
  // @@protoc_insertion_point(field_mutable:CMsgClientToGCSurvivorsGameTelemetryData.powerups)
  return _impl_.powerups_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CMsgClientToGCSurvivorsPowerUpTelemetryData >*
CMsgClientToGCSurvivorsGameTelemetryData::mutable_powerups() {
  // @@protoc_insertion_point(field_mutable_list:CMsgClientToGCSurvivorsGameTelemetryData.powerups)
  return &_impl_.powerups_;
}
inline const ::CMsgClientToGCSurvivorsPowerUpTelemetryData& CMsgClientToGCSurvivorsGameTelemetryData::_internal_powerups(int index) const {
  return _impl_.powerups_.Get(index);
}
inline const ::CMsgClientToGCSurvivorsPowerUpTelemetryData& CMsgClientToGCSurvivorsGameTelemetryData::powerups(int index) const {
  // @@protoc_insertion_point(field_get:CMsgClientToGCSurvivorsGameTelemetryData.powerups)
  return _internal_powerups(index);
}
inline ::CMsgClientToGCSurvivorsPowerUpTelemetryData* CMsgClientToGCSurvivorsGameTelemetryData::_internal_add_powerups() {
  return _impl_.powerups_.Add();
}
inline ::CMsgClientToGCSurvivorsPowerUpTelemetryData* CMsgClientToGCSurvivorsGameTelemetryData::add_powerups() {
  ::CMsgClientToGCSurvivorsPowerUpTelemetryData* _add = _internal_add_powerups();
  // @@protoc_insertion_point(field_add:CMsgClientToGCSurvivorsGameTelemetryData.powerups)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CMsgClientToGCSurvivorsPowerUpTelemetryData >&
CMsgClientToGCSurvivorsGameTelemetryData::powerups() const {
  // @@protoc_insertion_point(field_list:CMsgClientToGCSurvivorsGameTelemetryData.powerups)
  return _impl_.powerups_;
}

// optional uint32 difficulty = 6;
inline bool CMsgClientToGCSurvivorsGameTelemetryData::_internal_has_difficulty() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool CMsgClientToGCSurvivorsGameTelemetryData::has_difficulty() const {
  return _internal_has_difficulty();
}
inline void CMsgClientToGCSurvivorsGameTelemetryData::clear_difficulty() {
  _impl_.difficulty_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline uint32_t CMsgClientToGCSurvivorsGameTelemetryData::_internal_difficulty() const {
  return _impl_.difficulty_;
}
inline uint32_t CMsgClientToGCSurvivorsGameTelemetryData::difficulty() const {
  // @@protoc_insertion_point(field_get:CMsgClientToGCSurvivorsGameTelemetryData.difficulty)
  return _internal_difficulty();
}
inline void CMsgClientToGCSurvivorsGameTelemetryData::_internal_set_difficulty(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.difficulty_ = value;
}
inline void CMsgClientToGCSurvivorsGameTelemetryData::set_difficulty(uint32_t value) {
  _internal_set_difficulty(value);
  // @@protoc_insertion_point(field_set:CMsgClientToGCSurvivorsGameTelemetryData.difficulty)
}

// optional uint32 metaprogression_level = 7;
inline bool CMsgClientToGCSurvivorsGameTelemetryData::_internal_has_metaprogression_level() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool CMsgClientToGCSurvivorsGameTelemetryData::has_metaprogression_level() const {
  return _internal_has_metaprogression_level();
}
inline void CMsgClientToGCSurvivorsGameTelemetryData::clear_metaprogression_level() {
  _impl_.metaprogression_level_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline uint32_t CMsgClientToGCSurvivorsGameTelemetryData::_internal_metaprogression_level() const {
  return _impl_.metaprogression_level_;
}
inline uint32_t CMsgClientToGCSurvivorsGameTelemetryData::metaprogression_level() const {
  // @@protoc_insertion_point(field_get:CMsgClientToGCSurvivorsGameTelemetryData.metaprogression_level)
  return _internal_metaprogression_level();
}
inline void CMsgClientToGCSurvivorsGameTelemetryData::_internal_set_metaprogression_level(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000020u;
  _impl_.metaprogression_level_ = value;
}
inline void CMsgClientToGCSurvivorsGameTelemetryData::set_metaprogression_level(uint32_t value) {
  _internal_set_metaprogression_level(value);
  // @@protoc_insertion_point(field_set:CMsgClientToGCSurvivorsGameTelemetryData.metaprogression_level)
}

// -------------------------------------------------------------------

// CMsgClientToGCSurvivorsGameTelemetryDataResponse

// optional .CMsgClientToGCSurvivorsGameTelemetryDataResponse.EResponse response = 1 [default = k_eInternalError];
inline bool CMsgClientToGCSurvivorsGameTelemetryDataResponse::_internal_has_response() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool CMsgClientToGCSurvivorsGameTelemetryDataResponse::has_response() const {
  return _internal_has_response();
}
inline void CMsgClientToGCSurvivorsGameTelemetryDataResponse::clear_response() {
  _impl_.response_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse CMsgClientToGCSurvivorsGameTelemetryDataResponse::_internal_response() const {
  return static_cast< ::CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse >(_impl_.response_);
}
inline ::CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse CMsgClientToGCSurvivorsGameTelemetryDataResponse::response() const {
  // @@protoc_insertion_point(field_get:CMsgClientToGCSurvivorsGameTelemetryDataResponse.response)
  return _internal_response();
}
inline void CMsgClientToGCSurvivorsGameTelemetryDataResponse::_internal_set_response(::CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse value) {
  assert(::CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse_IsValid(value));
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.response_ = value;
}
inline void CMsgClientToGCSurvivorsGameTelemetryDataResponse::set_response(::CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse value) {
  _internal_set_response(value);
  // @@protoc_insertion_point(field_set:CMsgClientToGCSurvivorsGameTelemetryDataResponse.response)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse>() {
  return ::CMsgClientToGCSurvivorsGameTelemetryDataResponse_EResponse_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_dota_5fgcmessages_5fcommon_5fsurvivors_2eproto
