// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dota_gcmessages_common_craftworks.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_dota_5fgcmessages_5fcommon_5fcraftworks_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_dota_5fgcmessages_5fcommon_5fcraftworks_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021008 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "steammessages.pb.h"
#include "dota_shared_enums.pb.h"
#include "gcsdk_gcmessages.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_dota_5fgcmessages_5fcommon_5fcraftworks_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_dota_5fgcmessages_5fcommon_5fcraftworks_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_dota_5fgcmessages_5fcommon_5fcraftworks_2eproto;
class CMsgCraftworksComponents;
struct CMsgCraftworksComponentsDefaultTypeInternal;
extern CMsgCraftworksComponentsDefaultTypeInternal _CMsgCraftworksComponents_default_instance_;
class CMsgCraftworksComponents_ComponentQuantitiesEntry;
struct CMsgCraftworksComponents_ComponentQuantitiesEntryDefaultTypeInternal;
extern CMsgCraftworksComponents_ComponentQuantitiesEntryDefaultTypeInternal _CMsgCraftworksComponents_ComponentQuantitiesEntry_default_instance_;
class CMsgCraftworksQuestReward;
struct CMsgCraftworksQuestRewardDefaultTypeInternal;
extern CMsgCraftworksQuestRewardDefaultTypeInternal _CMsgCraftworksQuestReward_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::CMsgCraftworksComponents* Arena::CreateMaybeMessage<::CMsgCraftworksComponents>(Arena*);
template<> ::CMsgCraftworksComponents_ComponentQuantitiesEntry* Arena::CreateMaybeMessage<::CMsgCraftworksComponents_ComponentQuantitiesEntry>(Arena*);
template<> ::CMsgCraftworksQuestReward* Arena::CreateMaybeMessage<::CMsgCraftworksQuestReward>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

enum ECraftworksAuditAction : int {
  k_eInvalid = 0,
  k_eRecipeCrafted = 1,
  k_eMatchRewards = 2,
  k_eMatchRewardsTurbo = 3
};
bool ECraftworksAuditAction_IsValid(int value);
constexpr ECraftworksAuditAction ECraftworksAuditAction_MIN = k_eInvalid;
constexpr ECraftworksAuditAction ECraftworksAuditAction_MAX = k_eMatchRewardsTurbo;
constexpr int ECraftworksAuditAction_ARRAYSIZE = ECraftworksAuditAction_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ECraftworksAuditAction_descriptor();
template<typename T>
inline const std::string& ECraftworksAuditAction_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ECraftworksAuditAction>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ECraftworksAuditAction_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ECraftworksAuditAction_descriptor(), enum_t_value);
}
inline bool ECraftworksAuditAction_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ECraftworksAuditAction* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ECraftworksAuditAction>(
    ECraftworksAuditAction_descriptor(), name, value);
}
// ===================================================================

class CMsgCraftworksComponents_ComponentQuantitiesEntry final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:CMsgCraftworksComponents.ComponentQuantitiesEntry) */ {
 public:
  inline CMsgCraftworksComponents_ComponentQuantitiesEntry() : CMsgCraftworksComponents_ComponentQuantitiesEntry(nullptr) {}
  ~CMsgCraftworksComponents_ComponentQuantitiesEntry() override;
  explicit PROTOBUF_CONSTEXPR CMsgCraftworksComponents_ComponentQuantitiesEntry(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CMsgCraftworksComponents_ComponentQuantitiesEntry(const CMsgCraftworksComponents_ComponentQuantitiesEntry& from);
  CMsgCraftworksComponents_ComponentQuantitiesEntry(CMsgCraftworksComponents_ComponentQuantitiesEntry&& from) noexcept
    : CMsgCraftworksComponents_ComponentQuantitiesEntry() {
    *this = ::std::move(from);
  }

  inline CMsgCraftworksComponents_ComponentQuantitiesEntry& operator=(const CMsgCraftworksComponents_ComponentQuantitiesEntry& from) {
    CopyFrom(from);
    return *this;
  }
  inline CMsgCraftworksComponents_ComponentQuantitiesEntry& operator=(CMsgCraftworksComponents_ComponentQuantitiesEntry&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CMsgCraftworksComponents_ComponentQuantitiesEntry& default_instance() {
    return *internal_default_instance();
  }
  static inline const CMsgCraftworksComponents_ComponentQuantitiesEntry* internal_default_instance() {
    return reinterpret_cast<const CMsgCraftworksComponents_ComponentQuantitiesEntry*>(
               &_CMsgCraftworksComponents_ComponentQuantitiesEntry_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CMsgCraftworksComponents_ComponentQuantitiesEntry& a, CMsgCraftworksComponents_ComponentQuantitiesEntry& b) {
    a.Swap(&b);
  }
  inline void Swap(CMsgCraftworksComponents_ComponentQuantitiesEntry* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CMsgCraftworksComponents_ComponentQuantitiesEntry* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CMsgCraftworksComponents_ComponentQuantitiesEntry* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CMsgCraftworksComponents_ComponentQuantitiesEntry>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CMsgCraftworksComponents_ComponentQuantitiesEntry& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CMsgCraftworksComponents_ComponentQuantitiesEntry& from) {
    CMsgCraftworksComponents_ComponentQuantitiesEntry::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CMsgCraftworksComponents_ComponentQuantitiesEntry* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "CMsgCraftworksComponents.ComponentQuantitiesEntry";
  }
  protected:
  explicit CMsgCraftworksComponents_ComponentQuantitiesEntry(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kKeyFieldNumber = 1,
    kValueFieldNumber = 2,
  };
  // optional uint32 key = 1;
  bool has_key() const;
  private:
  bool _internal_has_key() const;
  public:
  void clear_key();
  uint32_t key() const;
  void set_key(uint32_t value);
  private:
  uint32_t _internal_key() const;
  void _internal_set_key(uint32_t value);
  public:

  // optional uint32 value = 2;
  bool has_value() const;
  private:
  bool _internal_has_value() const;
  public:
  void clear_value();
  uint32_t value() const;
  void set_value(uint32_t value);
  private:
  uint32_t _internal_value() const;
  void _internal_set_value(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:CMsgCraftworksComponents.ComponentQuantitiesEntry)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t key_;
    uint32_t value_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_dota_5fgcmessages_5fcommon_5fcraftworks_2eproto;
};
// -------------------------------------------------------------------

class CMsgCraftworksComponents final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:CMsgCraftworksComponents) */ {
 public:
  inline CMsgCraftworksComponents() : CMsgCraftworksComponents(nullptr) {}
  ~CMsgCraftworksComponents() override;
  explicit PROTOBUF_CONSTEXPR CMsgCraftworksComponents(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CMsgCraftworksComponents(const CMsgCraftworksComponents& from);
  CMsgCraftworksComponents(CMsgCraftworksComponents&& from) noexcept
    : CMsgCraftworksComponents() {
    *this = ::std::move(from);
  }

  inline CMsgCraftworksComponents& operator=(const CMsgCraftworksComponents& from) {
    CopyFrom(from);
    return *this;
  }
  inline CMsgCraftworksComponents& operator=(CMsgCraftworksComponents&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CMsgCraftworksComponents& default_instance() {
    return *internal_default_instance();
  }
  static inline const CMsgCraftworksComponents* internal_default_instance() {
    return reinterpret_cast<const CMsgCraftworksComponents*>(
               &_CMsgCraftworksComponents_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(CMsgCraftworksComponents& a, CMsgCraftworksComponents& b) {
    a.Swap(&b);
  }
  inline void Swap(CMsgCraftworksComponents* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CMsgCraftworksComponents* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CMsgCraftworksComponents* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CMsgCraftworksComponents>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CMsgCraftworksComponents& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CMsgCraftworksComponents& from) {
    CMsgCraftworksComponents::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CMsgCraftworksComponents* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "CMsgCraftworksComponents";
  }
  protected:
  explicit CMsgCraftworksComponents(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef CMsgCraftworksComponents_ComponentQuantitiesEntry ComponentQuantitiesEntry;

  // accessors -------------------------------------------------------

  enum : int {
    kComponentQuantitiesFieldNumber = 1,
  };
  // repeated .CMsgCraftworksComponents.ComponentQuantitiesEntry component_quantities = 1;
  int component_quantities_size() const;
  private:
  int _internal_component_quantities_size() const;
  public:
  void clear_component_quantities();
  ::CMsgCraftworksComponents_ComponentQuantitiesEntry* mutable_component_quantities(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CMsgCraftworksComponents_ComponentQuantitiesEntry >*
      mutable_component_quantities();
  private:
  const ::CMsgCraftworksComponents_ComponentQuantitiesEntry& _internal_component_quantities(int index) const;
  ::CMsgCraftworksComponents_ComponentQuantitiesEntry* _internal_add_component_quantities();
  public:
  const ::CMsgCraftworksComponents_ComponentQuantitiesEntry& component_quantities(int index) const;
  ::CMsgCraftworksComponents_ComponentQuantitiesEntry* add_component_quantities();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CMsgCraftworksComponents_ComponentQuantitiesEntry >&
      component_quantities() const;

  // @@protoc_insertion_point(class_scope:CMsgCraftworksComponents)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CMsgCraftworksComponents_ComponentQuantitiesEntry > component_quantities_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_dota_5fgcmessages_5fcommon_5fcraftworks_2eproto;
};
// -------------------------------------------------------------------

class CMsgCraftworksQuestReward final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:CMsgCraftworksQuestReward) */ {
 public:
  inline CMsgCraftworksQuestReward() : CMsgCraftworksQuestReward(nullptr) {}
  ~CMsgCraftworksQuestReward() override;
  explicit PROTOBUF_CONSTEXPR CMsgCraftworksQuestReward(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CMsgCraftworksQuestReward(const CMsgCraftworksQuestReward& from);
  CMsgCraftworksQuestReward(CMsgCraftworksQuestReward&& from) noexcept
    : CMsgCraftworksQuestReward() {
    *this = ::std::move(from);
  }

  inline CMsgCraftworksQuestReward& operator=(const CMsgCraftworksQuestReward& from) {
    CopyFrom(from);
    return *this;
  }
  inline CMsgCraftworksQuestReward& operator=(CMsgCraftworksQuestReward&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CMsgCraftworksQuestReward& default_instance() {
    return *internal_default_instance();
  }
  static inline const CMsgCraftworksQuestReward* internal_default_instance() {
    return reinterpret_cast<const CMsgCraftworksQuestReward*>(
               &_CMsgCraftworksQuestReward_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(CMsgCraftworksQuestReward& a, CMsgCraftworksQuestReward& b) {
    a.Swap(&b);
  }
  inline void Swap(CMsgCraftworksQuestReward* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CMsgCraftworksQuestReward* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CMsgCraftworksQuestReward* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CMsgCraftworksQuestReward>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CMsgCraftworksQuestReward& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CMsgCraftworksQuestReward& from) {
    CMsgCraftworksQuestReward::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CMsgCraftworksQuestReward* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "CMsgCraftworksQuestReward";
  }
  protected:
  explicit CMsgCraftworksQuestReward(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRewardComponentsFieldNumber = 2,
    kQuestIdFieldNumber = 1,
    kStatValueFieldNumber = 3,
  };
  // optional .CMsgCraftworksComponents reward_components = 2;
  bool has_reward_components() const;
  private:
  bool _internal_has_reward_components() const;
  public:
  void clear_reward_components();
  const ::CMsgCraftworksComponents& reward_components() const;
  PROTOBUF_NODISCARD ::CMsgCraftworksComponents* release_reward_components();
  ::CMsgCraftworksComponents* mutable_reward_components();
  void set_allocated_reward_components(::CMsgCraftworksComponents* reward_components);
  private:
  const ::CMsgCraftworksComponents& _internal_reward_components() const;
  ::CMsgCraftworksComponents* _internal_mutable_reward_components();
  public:
  void unsafe_arena_set_allocated_reward_components(
      ::CMsgCraftworksComponents* reward_components);
  ::CMsgCraftworksComponents* unsafe_arena_release_reward_components();

  // optional uint32 quest_id = 1;
  bool has_quest_id() const;
  private:
  bool _internal_has_quest_id() const;
  public:
  void clear_quest_id();
  uint32_t quest_id() const;
  void set_quest_id(uint32_t value);
  private:
  uint32_t _internal_quest_id() const;
  void _internal_set_quest_id(uint32_t value);
  public:

  // optional uint32 stat_value = 3;
  bool has_stat_value() const;
  private:
  bool _internal_has_stat_value() const;
  public:
  void clear_stat_value();
  uint32_t stat_value() const;
  void set_stat_value(uint32_t value);
  private:
  uint32_t _internal_stat_value() const;
  void _internal_set_stat_value(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:CMsgCraftworksQuestReward)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::CMsgCraftworksComponents* reward_components_;
    uint32_t quest_id_;
    uint32_t stat_value_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_dota_5fgcmessages_5fcommon_5fcraftworks_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CMsgCraftworksComponents_ComponentQuantitiesEntry

// optional uint32 key = 1;
inline bool CMsgCraftworksComponents_ComponentQuantitiesEntry::_internal_has_key() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool CMsgCraftworksComponents_ComponentQuantitiesEntry::has_key() const {
  return _internal_has_key();
}
inline void CMsgCraftworksComponents_ComponentQuantitiesEntry::clear_key() {
  _impl_.key_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline uint32_t CMsgCraftworksComponents_ComponentQuantitiesEntry::_internal_key() const {
  return _impl_.key_;
}
inline uint32_t CMsgCraftworksComponents_ComponentQuantitiesEntry::key() const {
  // @@protoc_insertion_point(field_get:CMsgCraftworksComponents.ComponentQuantitiesEntry.key)
  return _internal_key();
}
inline void CMsgCraftworksComponents_ComponentQuantitiesEntry::_internal_set_key(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.key_ = value;
}
inline void CMsgCraftworksComponents_ComponentQuantitiesEntry::set_key(uint32_t value) {
  _internal_set_key(value);
  // @@protoc_insertion_point(field_set:CMsgCraftworksComponents.ComponentQuantitiesEntry.key)
}

// optional uint32 value = 2;
inline bool CMsgCraftworksComponents_ComponentQuantitiesEntry::_internal_has_value() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool CMsgCraftworksComponents_ComponentQuantitiesEntry::has_value() const {
  return _internal_has_value();
}
inline void CMsgCraftworksComponents_ComponentQuantitiesEntry::clear_value() {
  _impl_.value_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline uint32_t CMsgCraftworksComponents_ComponentQuantitiesEntry::_internal_value() const {
  return _impl_.value_;
}
inline uint32_t CMsgCraftworksComponents_ComponentQuantitiesEntry::value() const {
  // @@protoc_insertion_point(field_get:CMsgCraftworksComponents.ComponentQuantitiesEntry.value)
  return _internal_value();
}
inline void CMsgCraftworksComponents_ComponentQuantitiesEntry::_internal_set_value(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.value_ = value;
}
inline void CMsgCraftworksComponents_ComponentQuantitiesEntry::set_value(uint32_t value) {
  _internal_set_value(value);
  // @@protoc_insertion_point(field_set:CMsgCraftworksComponents.ComponentQuantitiesEntry.value)
}

// -------------------------------------------------------------------

// CMsgCraftworksComponents

// repeated .CMsgCraftworksComponents.ComponentQuantitiesEntry component_quantities = 1;
inline int CMsgCraftworksComponents::_internal_component_quantities_size() const {
  return _impl_.component_quantities_.size();
}
inline int CMsgCraftworksComponents::component_quantities_size() const {
  return _internal_component_quantities_size();
}
inline void CMsgCraftworksComponents::clear_component_quantities() {
  _impl_.component_quantities_.Clear();
}
inline ::CMsgCraftworksComponents_ComponentQuantitiesEntry* CMsgCraftworksComponents::mutable_component_quantities(int index) {
  // @@protoc_insertion_point(field_mutable:CMsgCraftworksComponents.component_quantities)
  return _impl_.component_quantities_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CMsgCraftworksComponents_ComponentQuantitiesEntry >*
CMsgCraftworksComponents::mutable_component_quantities() {
  // @@protoc_insertion_point(field_mutable_list:CMsgCraftworksComponents.component_quantities)
  return &_impl_.component_quantities_;
}
inline const ::CMsgCraftworksComponents_ComponentQuantitiesEntry& CMsgCraftworksComponents::_internal_component_quantities(int index) const {
  return _impl_.component_quantities_.Get(index);
}
inline const ::CMsgCraftworksComponents_ComponentQuantitiesEntry& CMsgCraftworksComponents::component_quantities(int index) const {
  // @@protoc_insertion_point(field_get:CMsgCraftworksComponents.component_quantities)
  return _internal_component_quantities(index);
}
inline ::CMsgCraftworksComponents_ComponentQuantitiesEntry* CMsgCraftworksComponents::_internal_add_component_quantities() {
  return _impl_.component_quantities_.Add();
}
inline ::CMsgCraftworksComponents_ComponentQuantitiesEntry* CMsgCraftworksComponents::add_component_quantities() {
  ::CMsgCraftworksComponents_ComponentQuantitiesEntry* _add = _internal_add_component_quantities();
  // @@protoc_insertion_point(field_add:CMsgCraftworksComponents.component_quantities)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CMsgCraftworksComponents_ComponentQuantitiesEntry >&
CMsgCraftworksComponents::component_quantities() const {
  // @@protoc_insertion_point(field_list:CMsgCraftworksComponents.component_quantities)
  return _impl_.component_quantities_;
}

// -------------------------------------------------------------------

// CMsgCraftworksQuestReward

// optional uint32 quest_id = 1;
inline bool CMsgCraftworksQuestReward::_internal_has_quest_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool CMsgCraftworksQuestReward::has_quest_id() const {
  return _internal_has_quest_id();
}
inline void CMsgCraftworksQuestReward::clear_quest_id() {
  _impl_.quest_id_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline uint32_t CMsgCraftworksQuestReward::_internal_quest_id() const {
  return _impl_.quest_id_;
}
inline uint32_t CMsgCraftworksQuestReward::quest_id() const {
  // @@protoc_insertion_point(field_get:CMsgCraftworksQuestReward.quest_id)
  return _internal_quest_id();
}
inline void CMsgCraftworksQuestReward::_internal_set_quest_id(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.quest_id_ = value;
}
inline void CMsgCraftworksQuestReward::set_quest_id(uint32_t value) {
  _internal_set_quest_id(value);
  // @@protoc_insertion_point(field_set:CMsgCraftworksQuestReward.quest_id)
}

// optional .CMsgCraftworksComponents reward_components = 2;
inline bool CMsgCraftworksQuestReward::_internal_has_reward_components() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.reward_components_ != nullptr);
  return value;
}
inline bool CMsgCraftworksQuestReward::has_reward_components() const {
  return _internal_has_reward_components();
}
inline void CMsgCraftworksQuestReward::clear_reward_components() {
  if (_impl_.reward_components_ != nullptr) _impl_.reward_components_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::CMsgCraftworksComponents& CMsgCraftworksQuestReward::_internal_reward_components() const {
  const ::CMsgCraftworksComponents* p = _impl_.reward_components_;
  return p != nullptr ? *p : reinterpret_cast<const ::CMsgCraftworksComponents&>(
      ::_CMsgCraftworksComponents_default_instance_);
}
inline const ::CMsgCraftworksComponents& CMsgCraftworksQuestReward::reward_components() const {
  // @@protoc_insertion_point(field_get:CMsgCraftworksQuestReward.reward_components)
  return _internal_reward_components();
}
inline void CMsgCraftworksQuestReward::unsafe_arena_set_allocated_reward_components(
    ::CMsgCraftworksComponents* reward_components) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.reward_components_);
  }
  _impl_.reward_components_ = reward_components;
  if (reward_components) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:CMsgCraftworksQuestReward.reward_components)
}
inline ::CMsgCraftworksComponents* CMsgCraftworksQuestReward::release_reward_components() {
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::CMsgCraftworksComponents* temp = _impl_.reward_components_;
  _impl_.reward_components_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::CMsgCraftworksComponents* CMsgCraftworksQuestReward::unsafe_arena_release_reward_components() {
  // @@protoc_insertion_point(field_release:CMsgCraftworksQuestReward.reward_components)
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::CMsgCraftworksComponents* temp = _impl_.reward_components_;
  _impl_.reward_components_ = nullptr;
  return temp;
}
inline ::CMsgCraftworksComponents* CMsgCraftworksQuestReward::_internal_mutable_reward_components() {
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.reward_components_ == nullptr) {
    auto* p = CreateMaybeMessage<::CMsgCraftworksComponents>(GetArenaForAllocation());
    _impl_.reward_components_ = p;
  }
  return _impl_.reward_components_;
}
inline ::CMsgCraftworksComponents* CMsgCraftworksQuestReward::mutable_reward_components() {
  ::CMsgCraftworksComponents* _msg = _internal_mutable_reward_components();
  // @@protoc_insertion_point(field_mutable:CMsgCraftworksQuestReward.reward_components)
  return _msg;
}
inline void CMsgCraftworksQuestReward::set_allocated_reward_components(::CMsgCraftworksComponents* reward_components) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.reward_components_;
  }
  if (reward_components) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(reward_components);
    if (message_arena != submessage_arena) {
      reward_components = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, reward_components, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.reward_components_ = reward_components;
  // @@protoc_insertion_point(field_set_allocated:CMsgCraftworksQuestReward.reward_components)
}

// optional uint32 stat_value = 3;
inline bool CMsgCraftworksQuestReward::_internal_has_stat_value() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool CMsgCraftworksQuestReward::has_stat_value() const {
  return _internal_has_stat_value();
}
inline void CMsgCraftworksQuestReward::clear_stat_value() {
  _impl_.stat_value_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline uint32_t CMsgCraftworksQuestReward::_internal_stat_value() const {
  return _impl_.stat_value_;
}
inline uint32_t CMsgCraftworksQuestReward::stat_value() const {
  // @@protoc_insertion_point(field_get:CMsgCraftworksQuestReward.stat_value)
  return _internal_stat_value();
}
inline void CMsgCraftworksQuestReward::_internal_set_stat_value(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.stat_value_ = value;
}
inline void CMsgCraftworksQuestReward::set_stat_value(uint32_t value) {
  _internal_set_stat_value(value);
  // @@protoc_insertion_point(field_set:CMsgCraftworksQuestReward.stat_value)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::ECraftworksAuditAction> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ECraftworksAuditAction>() {
  return ::ECraftworksAuditAction_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_dota_5fgcmessages_5fcommon_5fcraftworks_2eproto
